### ISSUE TITLE
Knowing Your Own Strength HP pricing [BUG]

### ISSUE THREAD

**Issue by marcellraba** [richardwilkes/gcs#100]
Currently if using KYOS (set in preferences) the pricing of HP changes with Size Modifier as if it was using Basic Set rules.

How it should be:

"Hit Points: Cost is unchanged at ±2 points per level above
or below ST, but the Size limitation no longer applies. That
12,000-lb. elephant with ST 33 and 45 HP would also buy +12
HP for 24 points, making its final ST and HP cost 230 + 24 =
254 points."

To illustrate the issue

![Screenshot from 2019-05-22 22-31-35](https://user-images.githubusercontent.com/50235155/58206904-ebf99900-7ce1-11e9-91c4-5fb1b3f6732c.png)

**Comment by richardwilkes** [comment]
Fixed in commit 53f7ef5
