### ISSUE TITLE
Skills not calculated correctly

### ISSUE THREAD

**Issue by Yetanotherperson** [richardwilkes/gcs#102]
GCP is telling me that 24 points in a melee weapon skill is DX+7 for Axe/Mace, DX+10 for Broadsword, and DX+12 for two handed sword. Until recently, these values were lower but still wrong.

I'm loading Knight skills from Dungeon Fantasy. They seemed to load fine before. On the Knight Template, these all show as DX+6 as they should be, but when I take then to the character sheet, I get these weird values.

**Comment by richardwilkes** [comment]
Please attach a sheet illustrating the issue. Either the data files have some bad entries and need to be corrected, or your sheet just has other things on it that are also affecting the values in question.

**Comment by Yetanotherperson** [comment]
I tried draging and dropping the saved file here, but it says "We don't support that file type".

**Comment by Yetanotherperson** [comment]
The problem disappeared when I removed the other "single weapon" options. Thanks for your willingness to help. Awesome program!
