### ISSUE TITLE
Skill defaults not correctly accounting for talents

### ISSUE THREAD

**Issue by Xavion3** [richardwilkes/gcs#12]
Skills appear to default off whatever would work best, if you incorporate any bonuses from talents to the skill it's defaulting off. It correctly calculates skill level ignoring talents, but it does not correctly work out which skill to default off.

**Comment by angelforest** [comment]
[test defaults and talent.zip.gz](https://github.com/richardwilkes/gcs/files/933593/test.defaults.and.talent.zip.gz) (github acting weird with zip resolution)
Here is file demonstrating issue. Try to switch advantage on and off and see how it affects skills.

I made quick fix but I am not sure if it will have any unintended side-effects: https://github.com/angelforest/gcs/commit/4d8a12b729bf6632c08be30a47e58916277c0829

**Comment by richardwilkes** [comment]
I think @angelforest 's change is appropriate and I've incorporated it in  commit cf9b14350801ce357c88567bf78aeefe1f0657b5
