### ISSUE TITLE
Allow "User Descriptions" for Advantages on character sheet

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#120]
When using any of the "Powers as Magic" systems (Powers - Divine Favor, Thaumatology - Sorcery, etc.), your character will start to collect a lot of "powers" (Advantages with modifiers).

In most cases, you want to be able to describe how the spell works, and what it does.  For example: 

"Confundus Charm; causes the victim to become confused and disoriented.  Contest your Will (-1 per hex) vs their HT or become “Dazed” for margin of failure minutes."

Which you can add to the Notes field of the Advantage, and it will display with the Advantage (and any Melee/Ranged attacks that you define with it).

You can see the Advantage "Confundo" highlighted in this picture, and you can see that the Confundo Ranged Attack (which includes the Notes) on the left side:
![image](https://user-images.githubusercontent.com/8931036/61596368-7e2df880-abd0-11e9-8ee7-5c794c46bfbd.png)

But the real problem comes when the spell description isn't a simple 1-liner, but instead something like this:

"The druid can direct existing vegetation, roots, etc. to entangle and restrain everyone within an area.  Roll against Innate Attack (Gaze) to target a hex. If you miss, see Scatter (p. B414). The binding lasts for 10 seconds, continuing to entangle new people who blunder into it.  Victims inside the area may try to Dive (+3 Dodge, then Prone) or Retreat (+3 Dodge, 1 step back), to get out of the area of effect.  Anyone still inside the area is grappled (see p. 370) and rooted in place.  They cannot select the Move or Change Posture maneuvers or change facing, and is at -4 to DX.   To break free, the victim must win a Quick Contest of ST or Escape skill against the ST of your Binding. Each attempt takes one second. If the victim fails to break free, he loses 1 FP but may try again.   Those that do not break free grow more tightly entangled, with +1 to the ST of their bonds for each additional second they remain grappled."

Trying to add this to the Notes field results in this:
![image](https://user-images.githubusercontent.com/8931036/61596384-da911800-abd0-11e9-9b6c-49d1791506bd.png)

It would be nice if we could a define a separate text field to contain "larger than 1 line" text.    And optionally display it in a tooltip using the new Tooltip feature (https://github.com/richardwilkes/gcs/pull/112, https://github.com/richardwilkes/gcs/pull/113 & https://github.com/richardwilkes/gcs/pull/115), and allow it to be exported as part of the text output feature.

**Comment by richardwilkes** [comment]
I believe this has been addressed as part of @crnormand recent changes. If that's not the case, feel free to re-open and point out what still needs to be done.
