### ISSUE TITLE
No visible support for Improving Skills from Default (B173) for Innate Attack?

### ISSUE THREAD

**Issue by AndyDeck** [richardwilkes/gcs#130]
My test mage has IA(Projectile) at DX+4 for 12 points. With no points spent, IA(Beam) is at DX+2, 16. Adding 1 point to IA(Beam) changes it to DX+0, 14. 2 points, DX+1.  Other similar skills (Guns, for instance) appear to use Improving Skills from Default correctly.

I think I see the issue, actually - Guns(Pistol) lists the other specializations that it defaults from explicitly, while IA(Beam) only lists IA(no spec) for the default. Adding the other 3 specialties does fix the Improving Skills from Default issue, although it has no effect on Bug#76, Attacks won't base their level off of defaulted skills.

**Comment by richardwilkes** [comment]
Closing this, as it is a data issue, not a code issue.
