### ISSUE TITLE
Editing long lists like an Advantage library causes entries to jump around

### ISSUE THREAD

**Issue by mjeffw** [richardwilkes/gcs#132]
I'm on the Mac (currently Catalina, 10.15.1, but true for earlier versions of the OS as well).

Dragging a entry into a new position doesn't properly track the mouse. For example open the Basic Set Advantage library, unlock it, and scroll down a ways. Select an advantage in the list and drag it to a new position. When you drop it, the item is inserted into a completely different location (almost always closer to the top of the container).

**Comment by richardwilkes** [comment]
This has been fixed in the unreleased version. I hope to make a release before the end of the year that will contain this fix, among others. If you can't wait, you can always checkout the source and build it yourself, though.
