### ISSUE TITLE
Add Copy/Clone option to Item's Ranged Weapon/Melee Weapon lines to create duplicates of already present lines.

### ISSUE THREAD

**Issue by FatBaldBastard** [richardwilkes/gcs#140]
See title, enable the ability to clone already present weapon statistic lines to allow quickly adding new ammo types to firearms, ways to attack with a melee weapon etc.

**Comment by vilobion** [comment]
Additional Suggestion:
Also have it use the CTRL+U Hotkey for duplication that already exists in the Character Sheet space.
