### ISSUE TITLE
Skill levels

### ISSUE THREAD

**Issue by Guimdefreitas** [richardwilkes/gcs#141]
When I attach a new skill to a sheet, it automaticaly get a bonus, as an Average skill gets +3 for nothing and I can't change the value of the skill value directly, making me stay with the wrong number in the SL space. I also have to say that I'm a new user to the program and am still learning the ropes. Thank you.

**Comment by richardwilkes** [comment]
If you're getting a bonus, it is coming from something on the sheet. Please attach an example sheet and point out the specific thing you think is wrong so I can take a look.

**Comment by Guimdefreitas** [comment]
Just figured what it was. Had set an advantage wrongly and it was giving the bonus to every skill I had, sorry for the trouble. Thanks for the quick response and am really loving the program!
