### ISSUE TITLE
Saving files and creating new folders in GCS Library

### ISSUE THREAD

**Issue by Dragongunblade55** [richardwilkes/gcs#144]
I recently updated to 4.13.4 and I am having an issue saving GCS files. Also, any new folders I create in the GCS library does not appear. I have double-checked and I have the correct file location. Whenever I try to save a GCS file in the program library I receive an error message that says an error has occurred while trying to save your file.

**Comment by richardwilkes** [comment]
Sound like permission problems. You need to make sure the Library folder and its sub-directories/files are writable by your user account. If not, GCS won't be able to make changes.

**Comment by Dragongunblade55** [comment]
So I just checked the file permissions and yes it was a permission issue where while the administrator had full control the user did not. Thank you for your help
