### ISSUE TITLE
Support for customizable attribute cost from Power-Ups 9, Alternate Attributes 

### ISSUE THREAD

**Issue by Ghostwalker7** [richardwilkes/gcs#146]
Hi!

In the new PowerUps PDF, Alternate Attributes, there are a number of optional rules on how to change system attributes. One of them I think might not be difficult to implement, which is being able to change the cost of the attribute per level (such as ST costing cheaper on higher TLs or Supers games). ST, for example, could cost 5/level in TL 9 games.

Perhaps this could be done through a menu within the Options menu, to enter which value per level will be used in the campaign. 

The other optional rules are too radical to implement, so I don't even expect it to be supported, but this variable cost may be interesting.

Anyway, thank you for your amazing app!

**Comment by richardwilkes** [comment]
Yes, changing the per-level cost of an attribute isn't hard at all and could be made into a preference. I'll definitely consider adding this in the (hopefully) near future.

**Comment by richardwilkes** [comment]
Until I get around to this, you should be able to mimic the effect for most cases by giving characters an advantage with a feature that reduces the cost of the attribute(s) that need to be adjusted for your campaign. This also makes it very clear when such a change has been applied to the character.

**Comment by richardwilkes** [comment]
Custom attributes or even altering the existing attributes has now been implemented and will be in the next release.
