### ISSUE TITLE
Skill defaults and specializations do not function as expected

### ISSUE THREAD

**Issue by RevenantBob** [richardwilkes/gcs#147]
GCS has automatic use of _Improving Skills from Default_ (B.173). However, the expected behavior of skills which default to other skills that have specializations is ambiguous.

The following example demonstrates the ambiguity.

1. Create a new Character
2. Open Basic Set Skills Library
3. Drag _Beam Weapons/TL (Rifle)_ to character sheet
4. Set point Value to 100 points
5. Drag _Beam Weapons/TL (Pistol)_ to Character Sheet
6. Set Point value to 1 Point

**Expected Behavior**

Beam Weapons (Pistol) should use Improving Skills from Default rule and be skill level 32.

**Observed Behavior**

Beam Weapons (Pistol) does not use skills from default and is therefore skill level 10.

This is because a blank specialization in the default list does not match the specialization "Rifle". Should this be considered a wildcard match if there is no specialization specified or should this only match other skills without specialization? That is the ambiguity.

**Comment by richardwilkes** [comment]
So this is an issue with the data file. If you want to default from something with a specialization, you must specify the specialization. Right now, GCS has no information on whether a specialty is required or not (in this case, it *is* required and is marked as such in the basic book), so the code takes the stance that it must match (i.e. leaving it blank isn't the same as saying it matches to all -- it says it specifically matches to those skills with the associated name and *no* specialization). This is a shortfall that should be improved at some point. Until that time, though, you need to be explicit.

**Comment by richardwilkes** [comment]
Closing, since this is an issue that can and should be addressed in the data file by adding relevant fallback possibilities, not in GCS itself.
