### ISSUE TITLE
Unable to save items to Library objects.

### ISSUE THREAD

**Issue by 5crownik007** [richardwilkes/gcs#149]
Adding entries to the library objects included with GCS is possible, but the save function throws up a vague error message:
"An error occurred while trying to save the file."

**Comment by richardwilkes** [comment]
Most likely you don't have write permission to the library directory. Use the Help > Show GCS Library on Disk menu item to have it show you the directory, then make sure you have write permissions to that directory and its contents. Each OS is different on how that is done -- you should be able to google for how to set permissions if you're not aware of how to do this for your OS.

**Comment by 5crownik007** [comment]
Ah, you were right. I fixed it just a minute ago and it worked fine. Thank you for your help!
