### ISSUE TITLE
Window scrolling issues

### ISSUE THREAD

**Issue by wildj79** [richardwilkes/gcs#152]
When you open a page from the library explorer and apply a category filter the scroll functionally stops functioning correctly. For instance, if you open up `Advantages > Basic Set`, and then set the category filter to `Disadvantage`, you can scroll down the page just fine, but when you try to scroll back up, it only scrolls a couple of pixels and then stops. You have to grab the scroll bar with the cursor to move it back up to to top. Scrolling seems to work fine if you reset it back to `Any Category`. I've tried this with a couple of pages form the Library Explorer, and have had the same result with any category that has a long list of items that requires scrolling.

I've noticed this issue on both Windows 10 and on macOS 10.14
GCS Version 4.14

**Comment by richardwilkes** [comment]
Yes, this has been an issue (on all platforms) since the filtering capability was introduced. There is no easy solution at the moment, thanks to the way the filtering has been implemented.
