### ISSUE TITLE
Base10 breaks Skill lists

### ISSUE THREAD

**Issue by MartinLeist** [richardwilkes/gcs#153]
Hi,

I'm having a problem putting my own system into skill lists. Most of my new skills are based on 10 and not on an attribute. The moment you add a skill based on 10 to a skill list, GCS will not be able to open it anymore. Instead I get an error, that the file can't be opened, every time i try. When I change the Base10 value to IQ for instance, the file has no problems.

[NotWorking.zip](https://github.com/richardwilkes/gcs/files/4200281/NotWorking.zip)
I've attached a simple file that contains one of those not working skills. Is there a way around this? Characters containing those skills do not have any problems.

greets
Martin

**Comment by MartinLeist** [comment]
I wasn't using the most recent version.

**Comment by richardwilkes** [comment]
Hmm… opens fine for me in the current version of GCS (4.14). If you’re not using that version, try upgrading. If you are… I’ll need to get the specific error message you’re seeing.

- Rich

**Comment by richardwilkes** [comment]
Ah... good to hear.
