### ISSUE TITLE
German Translation gone

### ISSUE THREAD

**Issue by MartinLeist** [richardwilkes/gcs#154]
Hi,

I've been using GCS for quite some time now and I also have translated quite a few parts of the GURPS rules to german. I had used 4.9 and it showed me a german UI and more importantly a german character sheet. After updating to 4.14 there is no translation anymore. Was this translation removed? Am I missing a plugin that I installed to the old one but forgot?

greets
Martin

**Comment by richardwilkes** [comment]
Yes. See the release notes for version 4.12: https://github.com/richardwilkes/gcs/releases/tag/v4.12.0

You can add translations back easily enough, as they are now external to the program. Given the fact that I only speak/read english and the translations I got from others, while well-intended, were always one-offs and inevitably degrade over time as the software is changed, I don't plan to incorporate them directly into the releases anymore. Would be a good project for someone to undertake as a separate thing though.

**Comment by MartinLeist** [comment]
Great, thanks. That's what I needed. If I get the whole file translated, is there a place I should post it?

**Comment by richardwilkes** [comment]
I could create a repo for them and add links to it on the GCS site as well as add info about it in GCS in a future release (i.e. in the help menu, an item that takes you to the repo so you can download a translation file to install), if you're interested in being the point man on it.

**Comment by Ladeia** [comment]
Hello @richardwilkes, where I can fount i18n folder? I want restart pt-BR translation.

**Comment by MartinLeist** [comment]
@richardwilkes let's first see how well I get through with it, but I already started translating. If I have questions about where a phrase is used, shall I just ask here or do you prefer some other way?

@Ladeia in the GCS folder is a folder named app. in this folder is the i18n folder.

**Comment by Ladeia** [comment]
@MartinLeist  Sorry, but I dont see these folder in repository, I need build app first?

**Comment by MartinLeist** [comment]
@Ladeia I have looked in the installed version, not the source. The translations I put there are also used in the programm when restarting it.

**Comment by richardwilkes** [comment]
@MartinLeist Sounds good.

@MartinLeist is correct, @Ladeia -- the files are in your local installation of GCS, not in the repository.
