### ISSUE TITLE
Spells set to use other Attributes reset to IQ

### ISSUE THREAD

**Issue by darkband** [richardwilkes/gcs#156]
When Spells are set to function off of an attribute other than IQ they reset to use IQ after the Character Sheet or Spell Library is closed. I have noticed this issue only recently while doing a home brew conversion of Vampire the Masquerade in 4th Edition where I want the Disciplines to function like Spells but be based on various Attributes. I noticed this issue first in 4.11 then upgraded to 4.14 and the issue was still there

**Comment by richardwilkes** [comment]
Thanks for the report. I've fixed it in the source and it will be part of the next release that I make.
