### ISSUE TITLE
Contained Weight Reverses Kilogram to Pound Conversion

### ISSUE THREAD

**Issue by CaraiseLink** [richardwilkes/gcs#158]
If kilograms are entered into the contained weight prerequisite, GCS treats them as being worth roughly 20.7% of their actual mass. This is suspiciously close to 1 / (2.2 ^ 2), which makes me guess the program trying to convert them to an equivalent weight in pounds but mistakenly using a reversed formula, causing them to be worth 1 / 2.2 of a pound rather than 2.2 pounds.

**Comment by richardwilkes** [comment]
Thanks for the bug report. You're right, the "normalization" logic was inverted. I've fixed this and it will be part of the next release, whenever that is.
