### ISSUE TITLE
Edit menu too long for laptop screen

### ISSUE THREAD

**Issue by daliin** [richardwilkes/gcs#163]
I'm running GCS 4.14 on a Windows 10 laptop (Lenovo Thinkpad). My native screen resolution is 1920x1080. In GCS, I can no longer see the bottom of the Edit menu and it won't scroll down. See the screenshot below. 

![image](https://user-images.githubusercontent.com/35744059/77254395-bb9ac800-6c2e-11ea-9658-6c978a36e74e.png)

It's not insurmountable, but is quite annoying. I've dealt with it by switching to portrait mode which gives me a longer screen. Or attaching an external monitor. Or changing the Windows 10 "Scale and Layout" factor from 150% (the recommended default) to a lower value.

**Comment by richardwilkes** [comment]
I would recommend looking at some of the system options for controlling how menus are displayed/interacted with on your Windows system. GCS just uses the system menu controls so doesn't have any control over how they are displayed/interacted with by the user.

**Comment by richardwilkes** [comment]
While I believe this is merely a matter of system option adjustments on Windows, I could potentially reduce the length of the edit menu by moving some of those items into a different menu or a sub-menu. I'll consider that.

**Comment by richardwilkes** [comment]
I've reorganized the menus a bit for the upcoming release. While this should be handled by your OS, if your OS is refusing to do so for some reason, the changes I've made should help.
