### ISSUE TITLE
refactor build system

### ISSUE THREAD

**Issue by martintaraz** [richardwilkes/gcs#167]
It would be cool if a tool like this would use maven (or gradle) as a build system.
I would be willing to spend the time doing this if @richardwilkes approves it.
Would you be ok with this?

**Comment by richardwilkes** [comment]
It isn't clear to me what this would provide that the `ant` build files don't already do, how easy it would be for me to do the things necessary to build on each platform, etc. Other than GCS, I left the Java world many years ago, so `ant` is what I'm familiar with -- I don't have anything against another system, but the few times I've glanced at maven & gradle, they seemed overly complicated to do even simple things. Happy to be shown that isn't the case, but I'm skeptical.

**Comment by richardwilkes** [comment]
I'm going to close this, as I've recently completely changed the way GCS is built and it now uses mostly just some Java code so that I can guarantee to get what I want on each platform.
