### ISSUE TITLE
Alternate method of tracking unspent points

### ISSUE THREAD

**Issue by acrosome** [richardwilkes/gcs#168]
Instead of setting a point value and having GCS tick them off as you buy, just have it keep a running total.  This way, as you edit the character to add things later you don't keep ending up with massively negative numbers of 'unspent points'.

Then there also needs to be a spot to track actual unspent points, though, since you can use them for deus-ex-machina interventions and such in GURPS.

At the very least have this be an option under preferences- to set it to keep a running total.

**Comment by acrosome** [comment]
Also, are the animals and livestock from B455-B461 anywhere in the standard databases?  i can't find them.

**Comment by richardwilkes** [comment]
There's already a field for unspent points.

**Comment by richardwilkes** [comment]
As for animals... no, I don't believe so. I've never needed them and apparently none of the folks who generated most of the libraries did, either. You're welcome to create them and contribute them to the project.
