### ISSUE TITLE
Allow full difficulty range for spells?

### ISSUE THREAD

**Issue by PlasticPhoenix** [richardwilkes/gcs#170]
Would it be possible to open the range of spell difficulties up? Currently everything is set as hard/VH as per GURPS Magic. Is something like allowing an Easy to VH Range possible? I use a customized magic system right now and while I do have a slightly clunky workaround, something like this would be very nice. Part of the aim is to let people with normal IQ stats (like 10) have some level of adequacy with simpler magics.

**Comment by richardwilkes** [comment]
This is already possible in the current (unreleased) code. I hope to make a release in the near future.
