### ISSUE TITLE
Confusion on Page References

### ISSUE THREAD

**Issue by HumanLlama** [richardwilkes/gcs#171]
So I'm helping a player create a mage character in a dungeon fantasy game and when I opened the Dungeon Fantasy RPG page for equipment I kept seeing a page reference for DFA and when I checked the page on the official website I saw no mention of a DFA, and I did check to see if it was Dungeon Fantasy 1: Adventurers but that only has 30~ pages.

**Comment by richardwilkes** [comment]
This https://gurpscharactersheet.com/page_references.html holds the set of page references that GCS is in theory using in its data files. If you see something outside of those, it means it was added by someone without checking with me. Most data files are contributed by users like you who take the time to create them. If you want to fix them up, I'd be happy to integrate them into the next release.

**Comment by richardwilkes** [comment]
Taking a look at my copy of DFRPG, those page references are clearing pointing at the Adventurers book. DFA makes sense for that. I'll likely add it to the page references list.
