### ISSUE TITLE
DFRPG Strongbow Perk is really weird to implement

### ISSUE THREAD

**Issue by ArchonShiva** [richardwilkes/gcs#172]
The best I've found is to lower the bow's ST by 2 and make a note of the actual ST.

**Comment by TheFabulousIronChef** [comment]
ArchonShiva, I'm a little confused by this answer. Are you using the bows from the Basic Set equipment? I think if you're using DFRPG equipment, you just add +1 to damage (which is the difference if you are going up two levels in ST). It does the same thing. But I agree that it has to be a modifier on the Bow...I can't see exactly how to do it with the perk itself, unless you just indicate +1 to damage from that perk with bows.

**Comment by ArchonShiva** [comment]
Wow, that’s a blast from the past...
I’m happy you’re still working on it, though.

DFRPG bows (like the Basic Set’s) have a fixed ST and fixed damage (barring Weapon Master).  The PC has to provide that ST or suffer penalties (unlike Basic, which makes it impossible).  Strongbow helps attain that ST minimum, but doesn’t add damage in any way (nor does ST or it’s component parts).

I guess your implementation of bows is damage based on ST, with the reasonable enough assumption that people buy the correct strength bow, in which case it *is* +1 damage.

I’ve been making characters who use bows far beyond their ST, so I had to tweak stuff that way to make a bow use a different ST value for min ST.

Maybe no fix is needed for the reasonable cases.  Thank you.

- Frédérik Vézina

**Comment by richardwilkes** [comment]
Based on @ArchonShiva's last comment, I'm going to close this.
