### ISSUE TITLE
Track changes to character sheet in a log-like format 

### ISSUE THREAD

**Issue by gtludwig** [richardwilkes/gcs#173]
While there is no way to enforce a "ready-to-go-adventuring" or "approved-by-the-GM" type of feature, it would be nice to have some sort of insight into how experience points were spent.
I was envisioning something like:
20200509 - character approved by GM (file md5sum: ...)
20200511 - 1 point used in First Aid/TL7 from IQ+0 to IQ+1 (file md5sum: ..!)

**Comment by devakm** [comment]
Is there some way like this log concept to track points gained from experience? The current system is amazing during initial character creation, but there doesn't seem to be any way currently to show EXP Points awarded later by the GM, which seems very strange to me.

**Comment by richardwilkes** [comment]
For awarded XP, just add them to Unspent Points

**Comment by devakm** [comment]
> For awarded XP, just add them to Unspent Points

Awesome! I tried that in an older version and it didn't work out well. Now it seems to work perfectly. You rock!

**Comment by wlockwood** [comment]
@gtludwig - FWIW, I keep my characters in a Git repo for this very reason.

**Comment by richardwilkes** [comment]
I have to second @wlockwood's suggestion: use a source control system if you want such detailed history.
