### ISSUE TITLE
Basic Lift and Lifting ST bug in high levels

### ISSUE THREAD

**Issue by Ghostwalker7** [richardwilkes/gcs#174]
Hello! In the previous version, the program supported STs in the tens of thousands, without problems. Now, between 3 and 4 thousand, the program is no longer able to calculate and displays wrong and negative values. It may not be a problem for most people in normal games, but for Supers games with characters Superman, Hercules, Thor, etc., the new version of the program makes them unfeasible.

**Comment by richardwilkes** [comment]
Was this working in version 4.14? I didn't think I had changed anything in this area, but clearly I did something, because I see it is having some issues. Knowing which version this last worked in would be useful.

**Comment by Ghostwalker7** [comment]
Was fine in version 4.14. I have a NPC inspired by Thor with Lifting ST 30.000, with BL of 90.000 tons. In the 4.15 version, it doesn't work anymore and the BL is negative. I checked other valules and the bug start around 3-4 thousand of Lifting ST. 

(And sorry for any english mistakes!)
