### ISSUE TITLE
Modifier drag-and-drop only works on the first page

### ISSUE THREAD

**Issue by jonathanmaw** [richardwilkes/gcs#175]
Hi,

I have been playing around with the modifier drag-and-drop feature added in 4.15. When I have an advantage list or equipment list that spans multiple pages, drag and drop only works for the first page.

Dragging a modifier to an advantage on the first page causes a box to be drawn around the advantage, and releasing causes it to be applied to the modifier list.
Dragging a modifier to an advantage on later pages causes it to draw a line between two advantages, and releasing does nothing.
Dragging the advantage to its first page allows the modifier to be added, which is a suitable, if inconvenient workaround for the time being.

This affects both advantages and equipment.

I have observed this behaviour on both the Linux and Windows versions downloaded from gurpscharactersheet.com

**Comment by richardwilkes** [comment]
(sigh) I had fixed that exact problem early on and apparently broke it again later with other changes. Will take a look as soon as time permits.
