### ISSUE TITLE
Allow Notes to have References

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#177]
The Basic Set Rules libraries is a good idea but this could also make sense as notes. Allowing Notes to have references would be a very nice and useful feature in general as well.

**Comment by richardwilkes** [comment]
That was actually contributed by Fantell from the GURPS Discord. I thought it was a pretty good idea and was going to suggest he use notes instead... and then realized that they don’t have the page reference field. At that point, I didn’t have the energy left to take the time to add that capability to notes and all the other knock-on places I’d have to adjust... but it is a good idea.

Hopefully in the next non-bug-fix release...
