### ISSUE TITLE
Unable to Edit Master Library Files / Mac

### ISSUE THREAD

**Issue by TheFabulousIronChef** [richardwilkes/gcs#180]
Ever since I updated the Master Library in GCS (when prompted), I cannot edit anything in those libraries or files (it is all greyed out). Am I missing something?

![Screen Shot 2020-05-12 at 10 00 29 AM](https://user-images.githubusercontent.com/46587602/81701002-6bbecd00-9437-11ea-95d6-6df6d8a061f0.png)

**Comment by richardwilkes** [comment]
When you open a library list, by default, it’s contents are locked to prevent unintended modifications. Just click the little lock icon in the toolbar to unlock it.

**Comment by TheFabulousIronChef** [comment]
D'oh. Thanks for the reminder.
