### ISSUE TITLE
[Windows] Updating the GCS master library from within GCS fails.

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#183]
This fails and nothing is updated, the following message is displayed:
![image](https://user-images.githubusercontent.com/1914417/81878262-dd7b5000-95ca-11ea-9317-ed93f692dec6.png)

After that attempt failed, I noticed that certain folders had disappeared from the master library as displayed in GCS, in this case Powers, and Power Ups. I think this is related to the fact that on this specific occasion those two folders were supposed to recieve new files, but I couldn't say for certain.
Though restarting it made them visible again.

**Comment by richardwilkes** [comment]
I've added some logging for this now... but in addition, I should have the code create the new data in a temporary location and only if it can do so successfully, delete the old and move the new into its spot.

**Comment by richardwilkes** [comment]
Note: the cause of this is most likely a temporary internet or GitHub failure. Still, it shouldn't damage the existing Master Library when those sorts of things happen.

**Comment by Legendsmith** [comment]
I'm not sure that this is internet or github failure, though maybe it is. My friends have reported the same error.

**Comment by richardwilkes** [comment]
Hmm... the only other thing that is a possibility (on Windows only, which I think is where you're running the software) is if you have a file in use in the Master Library tree (or possibly even a view onto it with the Windows desktop -- I'm not sure if that will prevent deletion of a directory, but it is likely given the way the Windows file system support works).

Unfortunately, if that's what is causing the problem, there isn't anything I can really do, other than building a more elaborate deployment scheme as mentioned above -- it will still fail when it goes to remove the old data, but it might improve things overall despite that.

**Comment by richardwilkes** [comment]
Commit d1095f96ccffecd91dc57fa99769c88cea8beefc changes the way updating of the Master Library is done to reduce the potential for leaving the library in a bad state. I say "reduces the potential" just because there are OS-level errors that, if they occur, make it impossible to recover from. Those should be rare and likely non-existent, though.
