### ISSUE TITLE
Changing Library Locations

### ISSUE THREAD

**Issue by ethomas340** [richardwilkes/gcs#185]
Is it possible to change the location of the Main and User Libraries from the default installation location? I run GCS from my Box account over multiple machines.

**Comment by richardwilkes** [comment]
Yes. The location of both can be controlled via environment variables:

GCS_MASTER_LIBRARY
GCS_USER_LIBRARY

**Comment by ethomas340** [comment]
I can't find them on any of the menus. How do I change them?

**Comment by richardwilkes** [comment]
It's not something you can do from the UI. It's a low-level environment setting that you must make. Each OS platform does it slightly differently. You should be able to google "how to set environment variables on [os]" to get a walk-through.

**Comment by ethomas340** [comment]
Okay, I'm halfway there. I found a tutorial that shows me how to get to Environment Variables but I don't see anything related to GCS in them. I double-clicked on PATH but only have something related to Wiindows Apps and Box Edit.

**Comment by richardwilkes** [comment]
You should be creating brand-new variables with the names above, each set to a path where you want the directory to be.

**Comment by ethomas340** [comment]
Got it! Works beautifully! Thanks, dude!
