### ISSUE TITLE
TL for Equipment Modifiers

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#186]
Ultra Tech, High Tech, and Pyramid Issues dealing with these subjects often have Equipment modifiers that have requisite TLs. It would be great to be able to actually have a field for these, because it's not efficient or elegant to try to use containers.

**Comment by richardwilkes** [comment]
Sounds like you want prerequisites on modifiers.

**Comment by Legendsmith** [comment]
No, I just want to be able to display TL on modifiers in the lists, just like how equipment does. it doesn't have to have any programmatic prerequisite function.

**Comment by richardwilkes** [comment]
Hmm... the TL field on equipment doesn't actually show up on the character sheet. If I added a TL field to modifiers as well, I'd likely not have it show up anywhere on the sheet either. i.e. just like with equipment, it would only be noticeable in the standalone lists and no where else -- including inside the editor for a piece of a equipment... although I guess I could add another column for it there if that was beneficial.

**Comment by richardwilkes** [comment]
I'm also not clear on how having this field actually makes them any easier to enter/use when a given modifier has different info for different TLs. Seems like you'd have to make distinct versions of each, just like you have to do for equipment.
