### ISSUE TITLE
Add -40% for ST and DX when No Fine Manipulators is added to disadvantages list. 

### ISSUE THREAD

**Issue by evsan** [richardwilkes/gcs#188]
Basic Set p. 145, Basic Set p. 15

When creature has any level of No Fine Manipulators they allowed to buy ST and DX more cheaply.

**Comment by richardwilkes** [comment]
This is already the case if you use the No Fine Manipulators disadvantage that is in the Basic Set Advantages file in the Master Library. If you look, it has two features attached to it:
- Reduces the attribute cost of ST by 40%
- Reduces the attribute cost of DX by 40%

**Comment by evsan** [comment]
Thank you for the quick answer.
Found it. 
In that case it should be an issue for gcs_library. This feature is not enabled by default for No (Fine) Manipulators disadvantage in Meta-Traits. 
E. g. 
Meta-Traits folder of the Master Library: Vermiform or Quadruped. 
Animals folder of the Master Library: Timber Wolf has Quadruped meta-trait without ST and DX reduction.

**Comment by richardwilkes** [comment]
I've adjusted the meta-traits and animals you pointed out, along with a few others. I've also taken the time to add the remaining animals and monsters from the Basic Set (and updated a few that were already present).

**Comment by evsan** [comment]
Great! 
Thank you so much!
