### ISSUE TITLE
HP and FP calculations for reduced Move and Dodge applied incorrectly

### ISSUE THREAD

**Issue by marcellraba** [richardwilkes/gcs#189]
When you go to Reeling/Tired the software **_seemingly_** utilizes the rules found on B380, however, Kromm said that this is incorrect and the rules on B419 and B426 should be applied.
![image](https://user-images.githubusercontent.com/50235155/82132710-07a75a80-97e3-11ea-8e44-a01a55732ff4.png)
Showing incorrect calculations, if correct it would go from 5 Move and 8 Dodge to 3 Move and 4 Dodge instead of 2 Move and 5 Dodge. (Plus FP loss should incur an ST loss too but that's a feature request)

Relevant Krommpost:
http://forums.sjgames.com/showthread.php?p=149546#post149546

Also relevant from PK:
http://forums.sjgames.com/showpost.php?p=2049301&postcount=25

**Comment by richardwilkes** [comment]
OK, so the commit I just made adjusts for the revisions that those posts refer to. Essentially revising the "tired" and "reeling" thresholds to less than ⅓ of FP & HP, respectively as well as changing the adjustment to work off of the correct base, rounding up, and finally applying the encumbrance penalty.

**Comment by richardwilkes** [comment]
Before I close this out, though, I'm wondering if the adjustment to ST from being "tired" should be reflected in the Max Load display as well as the values in the Lifting & Moving Things section? The text on B426 seems to imply that: "Halve your Move, Dodge, and ST (round up). This does not affect ST-based quantities, such as HP and damage." -- i.e. it won't affect your HP nor weapon damage, but it should affect your lifting and endurance. Opinion on this? Or, better yet, a ruling from someone on the SJG staff to back it up / say it isn't so?

**Comment by richardwilkes** [comment]
So I've done some experiments and I think the results of doing both of those (stacking "tired" and "reeling" penalties, as well as reflecting the effective ST reduction in the amount you can carry / lift) seem reasonable. I've checked in a commit that applies this change. I can always revert this change, so if someone has info that shows this shouldn't be done, let me know.
