### ISSUE TITLE
Incorrect skill level totals and advancement for Skills which Default to another Skill.

### ISSUE THREAD

**Issue by Deadoflife** [richardwilkes/gcs#193]
Environment: Windows 10, AMD64, GCS 4.16(Alternate Installer), Java 14.0.1

This bug can be consistently replicated

Steps to replicate:

1) Create new character sheet
2) Add a New DX/E Skill at 1cp, A, which Defaults to B at -2.
3) Add a New DX/E Skill at 1cp, B, which Defaults to A at -2.
4) Set the Number of cp for skill A to 4
5) Detriment Skill B using CTRL Minus to 0cp
6) Increment Skill B To 1cp Using Ctrl Equal

Expected Result: Skill B should be at DX+0
Actual Result: Skill B is at DX+1, Futhermore Following Phenomena is noted.
1) Skill level for B is Increased by 1 at cp levels 1,2,3,7,11... instead of 1,2,4,8,12... as should be expected.
2) This bug can be replicated by using DX/A Skills using the same Defaults.
3) This bug also can be replicated by adding skills "Guns(pistol)" and "Guns(Rifle)" from the master library's "Basic Set > Basic Set Skills" instead of custom skills.
Proof: See attached Image or link https://cdn.discordapp.com/attachments/237104265523363840/713855424218005584/GCS_Default_Bug_End_Result.png

Severity: Can possibly interfere with Use for Gameplay purposes, doesn't Interfere with use of program.

**Comment by richardwilkes** [comment]
This is not actually a bug. It has to do with the way defaults are set and retained. Once a default is determined, it is essentially locked in. You can use the Edit > State... > Swap defaults command to switch to a different default choice when there is more than one possibility (like in this case, where A can default to B, or B can default to A).

GCS used to always pick what it thought was the optimal choice, but that annoyed people that wanted to pick an alternate for whatever reason, or that had a house rule that once a default was chosen, it couldn't be altered.
