### ISSUE TITLE
Enhancement: Allow Skill Containers to be classified as Racial.

### ISSUE THREAD

**Issue by pgaurons** [richardwilkes/gcs#202]
Although Basic Set says that race templates should not have skills, some later pyramids have skills on racial templates (eg: #3/115). I think the trickiest part of this implementation would be if one were to continue improving skills on the racial template, you'd either need to hack up something to replace the skills with talents, or have a way to aggregate point values of the same skill when it appears multiple times on a character sheet.

**Comment by richardwilkes** [comment]
This seems better represented by having a feature that grants a bonus number of points (rather than levels) to a skill.

**Comment by pgaurons** [comment]
If you think that can work, that might be better. I agree it might be
better in that the race stays one "atomic" group.

**Comment by richardwilkes** [comment]
Implemented Skill Point Bonuses as part of 683ac712da2a99059923118cf60bd8292c04440f
