### ISSUE TITLE
Allow Spell Containers to be classified as Racial.

### ISSUE THREAD

**Issue by pgaurons** [richardwilkes/gcs#203]
Although Basic Set says that race templates should not have skills, some later pyramids have spells on racial templates (eg: #3/115). I think the trickiest part of this implementation would be if one were to continue improving spells on the racial template, you'd either need to hack up something to replace the spells with talents, or have a way to aggregate spell point totals when they appear multiple times on one sheet.

**Comment by richardwilkes** [comment]
Similar to the skill request you created before this one, this sounds like it would be better represented by a feature that added points to a spell.

**Comment by pgaurons** [comment]
I agree with the statement. I just submitted this as two requests because
I'm used to trying to break work items down to the minimum viable
enhancement.

**Comment by richardwilkes** [comment]
I appreciate that. Wasn't trying to sound like it was annoying me -- just wanted reference the other one so that when I get around to this, I don't forget to do that one, too. Probably should have added a link so that it's bi-directional... here: #202

**Comment by richardwilkes** [comment]
Implemented Spell Point Bonuses as part of 683ac712da2a99059923118cf60bd8292c04440f
