### ISSUE TITLE
User Description, Modifiers, and Notes display options not working correctly

### ISSUE THREAD

**Issue by Euthoniel** [richardwilkes/gcs#208]
Whatever options are selected at character creation seem to be unchangeable within GCS.  So if I create a character with "Tooltip" modifier display selected, it won't display as "Inline" if I make that change to the setting.  

I was able to go edit the xml files and change the setting manually, but the GCS settings won't change anything after character creation or first saving the files.

**Comment by richardwilkes** [comment]
Sounds like you're trying to change character sheet settings of an existing sheet by changing the preferences, which now only control the initial settings. To change the sheet settings, you must click on the settings button on the toolbar of the sheet.

**Comment by Euthoniel** [comment]
Oops, yeah, I hadn't noticed settings were now on a sheet by sheet basis.  My mistake.
