### ISSUE TITLE
Spells/Width of Field

### ISSUE THREAD

**Issue by TheFabulousIronChef** [richardwilkes/gcs#209]
I apologize if this has already been asked, but I didn't see it. Is there any way to make the width of the Spell's "name" field (it's called "Spells") narrower so the other fields can be wider, and the spell can fit all in one row, as opposed to broken over two rows? The College column, for example, is often too narrow for many colleges, while the width of the Spell column is quite large, with lots of empty space.

**Comment by richardwilkes** [comment]
The spell columns should auto-adjust, but give any excess space to the "Spells" column. I see that isn't happening except when first loaded, though, which is a bug.

**Comment by TheFabulousIronChef** [comment]
> The spell columns should auto-adjust, but give any excess space to the "Spells" column. I see that isn't happening except when first loaded, though, which is a bug.

Aha! Yes, I see it now. It's a minor bug. Once it's saved and reopened, that problem goes away. Thanks.

**Comment by TheFabulousIronChef** [comment]
I just realized that it also doesn't automatically switch if you change zoom levels. So if you default opening at 125% and then bump it up to 150% or 200%, that will expand the height of the row (because the column widths do not auto-adjust).

**Comment by TheFabulousIronChef** [comment]
In any event, I just want to note that this product is awesome and I really appreciate you putting the time into not only creating this product, but addressing the issues as they come up. It definitely merits a donation, which I just made.

**Comment by richardwilkes** [comment]
Thank you, @TheFabulousIronChef
