### ISSUE TITLE
Broken Equipment containers

### ISSUE THREAD

**Issue by Jesseman1** [richardwilkes/gcs#212]
I was adding a new equipment container to a character and looking at the different container prerequisites. after clicking on 'has contained weight' twice, the details box vanished and will not return, i've already closed and reopened the program, restarted the computer, tried on a different character sheet, and reinstalled the GCS to repair it, nothing has fixed this problem. now any time I try to select 'has contained weight' on any equipment container in any character sheet, the box vanishes.

**Comment by Jesseman1** [comment]
also no additional prerequisites can be added after this occurs, no new details boxes will appear when clicking on the + button

**Comment by Jesseman1** [comment]
Even after completely uninstalling the GCS from the control panel and reinstalling fresh the problem continues.

**Comment by richardwilkes** [comment]
You'll need to remove the GCS preference file to get back to normal. Even then, until I put out a new release, selecting the 'has contained weight' option will immediately break it again.

**Comment by Jesseman1** [comment]
I just dont understand why it worked fine at first. but then broke completely after clicking it twice

**Comment by richardwilkes** [comment]
It's obvious if you look at the code... but not worth going into detail here.

**Comment by richardwilkes** [comment]
I'm going to release 4.17.2 a bit later today to address this problem.

**Comment by Jesseman1** [comment]
alright well thank you for taking a look at it.
