### ISSUE TITLE
Unable to open GCS files

### ISSUE THREAD

**Issue by Jesseman1** [richardwilkes/gcs#216]
I just updated the GCS and now it can't open my character sheets

**Comment by Euthoniel** [comment]
Same thing is happening to me, including for the basic set set characters in the master library.  

Unable to open "file name.gcs".

**Comment by richardwilkes** [comment]
Please attach a sheet that won't open to this bug report as well as the log file. On macOS, this is ~/Library/Logs/gcs.log. On Windows, this is %LOCALAPPDATA%\logs\gcs.log. On Linux, this is ~/.local/logs/gcs.log.

**Comment by Jesseman1** [comment]
Alright, here's the error log, but Github won't let me attach the GCS file
[gcs.log](https://github.com/richardwilkes/gcs/files/4766312/gcs.log)

**Comment by richardwilkes** [comment]
Should be fixed in the v4.17.5 release, which was just uploaded.
