### ISSUE TITLE
GCS won't save character sheet

### ISSUE THREAD

**Issue by ubiquitousrat** [richardwilkes/gcs#217]
Just updated to version 4.17.5 on Windows 10 machine and I cannot save any character, nor can I export them to .PDF or .txt formats. Thus, when I close the program, I lose the character sheet.

**Comment by richardwilkes** [comment]
Please attach the error log. What you've stated above isn't enough for me to find the issue, as none of the many machines I have exhibit the problem.

You can find the error log at: `%LOCALAPPDATA%\logs\gcs.log`

**Comment by Rhymeleaf** [comment]
I had this exact problem with a character sheet. It turned out that the trigger for this was having a / in the character's name field. Once I removed it and the name field only had letters, the Save and Export functions began to work again.

**Comment by ubiquitousrat** [comment]
Ok - sorry, I have been unavailable since due to life happening, so I can’t get to the PC to figure out the log stuff immediately.

**Comment by ubiquitousrat** [comment]
Ok, here's the log (I think - not a techie)
Thanks for looking into it. It's possible the problem was the use of a "(" in the character name, maybe, but I think I did try without it at the time.
[gcs.log](https://github.com/richardwilkes/gcs/files/4776726/gcs.log)

**Comment by richardwilkes** [comment]
So looking at the log, the problem is as @Rhymeleaf mentions: a file name that your OS won’t accept.  Windows, in particular, has a fairly long list of reserved words and invalid characters for file names. I’ll keep this open for now, because while there isn’t much I can do about this, I should be able to detect that this is what the problem was and put up a more appropriate error message.

**Comment by PPAChao** [comment]
The error is absent on Ubuntu 20.04 LTS. A character sheet with a slash in the name field Exports and Saves As properly.

**Comment by richardwilkes** [comment]
The 4.17.7 release puts some checks in place to try and prevent invalid file names from being used for your platform.
