### ISSUE TITLE
Grand Unified Hit Location Table

### ISSUE THREAD

**Issue by Dvorn1543** [richardwilkes/gcs#218]
Now that space is used a bit differently in the newest version of GCS, the hit location column has a decent bit extra space. Would it be possible to add the hit locations introduced in MA and LT, and compiled together in the Grand Unified Hit Location Table, to the software?

**Comment by richardwilkes** [comment]
Recording some info regarding hit location suggestions that were sent to me back on October 19, 2020.

![hit location breakdown](https://user-images.githubusercontent.com/13079058/108573103-b293fa00-72c8-11eb-86a9-539510d0fcb3.png)
![sample hit location layout for gcs](https://user-images.githubusercontent.com/13079058/108573105-b3c52700-72c8-11eb-9bc7-29329dee001e.png)

**Comment by Dvorn1543** [comment]
Hey, here is a refference PDF for various location to hit penalties
[Bruno_UnifiedHitLocations_2p.pdf](https://github.com/richardwilkes/gcs/files/6016322/Bruno_UnifiedHitLocations_2p.pdf)

**Comment by richardwilkes** [comment]
So, in an attempt to summarize what is possible:

- Additional sub-locations, with multiple tiers (e.g. torso -> chest, abdomen; which in turn are chest -> vitals, chest and abdomen -> vitals, digestive tract, pelvis, groin)
- Notion of which limb, i.e. left, right, arm 4, etc.
- Front, back, top, bottom
- Variance in actual coverage of a location (e.g. DR4, but only 2 vs impaling)

Did I miss any?

As it is, I keep coming back to the fact that all this information, while I could represent it internally with a bit of effort, would take a page or more by itself to display. That's not a reasonable thing. Some additional brain-storming needs to be done to figure out a reasonable way to display this in a small area on the printed sheet.

**Comment by Dvorn1543** [comment]
Hey, sorry for a delayed reply. Just to clarify, my original idea is NOT the inclusion of every single hit location on the Grand Unified Hit Location Table. I mean, don't get me wrong I would love that, but I understand that's A LOT.

My idea was simply to include the next level of granularity from what is already in GCS.

In other words the locations I suggested were:

Skull
Face
Neck
Chest
Abdomen
Vitals(by RAW and supported via the Pyramid armor system, the vitals are a special sublocation that is spread between the abdomen and chest, so just leeaing it as is is best, NOT making 2 seperate vitals locations)
Groin
L/R Shoulder
L/R Upper Arm
L/R Elbow
L/R Forearm
L/R Hand
L/R Thigh
L/R Knee
L/R Shin
L/R Foot

As for stuff like facing(my chest is covered by DR6 plate but only from the front) I think covering that via notes on the actual piece of equipment is perfectly fine, PARTICULARLY when you can actually select and represent the fact it only covers the chest, not the whole torso). And the same goes for coverage(my chest is covered on 5/6).

**Comment by Dvorn1543** [comment]
I simply shared the Grand Unified Hit Location Table, as I noticed that in the example picture you posted, the hit location penalties were wrong.

**Comment by richardwilkes** [comment]
> Hey, sorry for a delayed reply. Just to clarify, my original idea is NOT the inclusion of every single hit location on the Grand Unified Hit Location Table. I mean, don't get me wrong I would love that, but I understand that's A LOT.

Yes, I understand. There were a number of essentially the same request (i.e. MORE hit locations!!) that I've collapsed into this single issue, as they are all fundamentally related to each other. From the little bit of digging I've done, I've noticed that the rules themselves aren't 100% consistent with each other across the various books and is likely where some of the "penalties were wrong" info might be springing up.

I'm interested in potentially adding something here, but the specifics of exactly what aren't becoming any clearer, as I have literally dozens of folks pulling in different directions. Without a reasonable UI that works for the printed page, though, I'm currently not seeing much I can do. One of the suggestions above takes up significantly more space and doesn't actually provide the info I'd want to see as a player -- unless someone first explained the data in detail first, which isn't likely to happen for most players.

**Comment by Dvorn1543** [comment]
Generally speaking, in regards to hit location penalties, the Grand Unified Hit Location Table is king.  But in general, simply allowing the player to adjust the penalties to hit a given location in GCS would side step rule issues nicely(ohh, at your table the forearm isn't a *insert penalty here*? Okay well just enter your own penalty into the box)

Is my suggestion above one of the more conservative ones? Because IMO as long as you can represent these "gross" sublocations, everything else can be handled via notes on the piece of equipment. I don't think every single locations needs 4 facing "sublocations", or something like, a specific "digestive track" sublocation.

**Comment by Dvorn1543** [comment]
IMO the example picture you linked above is perfectly adequate for what i had in mind when i originally made this post.

**Comment by richardwilkes** [comment]
Customized hit location support has been implemented and will be in the next release.
