### ISSUE TITLE
Roll20 JSON integration

### ISSUE THREAD

**Issue by gtludwig** [richardwilkes/gcs#220]
There is no official Roll20 way to integrate with GCS, but I just realized this feat could be achieved via JSON. 
While there would be an in-between step to parse the XML-like GCS file to JSON, which is easy enough to do with online tools. I renamed an older character of mine, from cgs to XML and uploaded it to freeformatter.com to get the JSON output, I was wondering if it would be possible to add an option under "File", "Export to.. >" and from there, either export to a JSON file or export to the clipboard.
Of course, it would require, in Roll20, a GURPS Sheet that could take on a JSON payload and parse it correctly!
I love using GCS (because it is available on different platforms) and my main issue with Roll20 is the lack of support and having to manually transfer all the data is really painful.

**Comment by richardwilkes** [comment]
This can already be achieved with the existing export templates. I believe the GURPS Calculator support does something similar.

**Comment by richardwilkes** [comment]
GCS v4.20 uses json as its storage format. This won't really help with automatic import into another system, as GCS only stores the minimum of what it needs in those files and calculates the rest -- and there are a ton of calculations that occur for this. My previous statement, however, is still true: using the text template output system that GCS has had for years, you can create an output template that generates json with the fully resolved information. Should you do so and want to contribute the result, I'd be happy to consider including the template as part of the master library for others to use.
