### ISSUE TITLE
Opening a file from Windows File Explorer in a directory with spaces in its path fails

### ISSUE THREAD

**Issue by mustafakalash** [richardwilkes/gcs#223]
Attempting to open a file from a path with spaces (e.g., `C:\Users\me\OneDrive\Documents\GURPS 4e\Kecick.gcs`) causes the following pop-ups, in order:
![image](https://user-images.githubusercontent.com/313146/85959349-eb621600-b969-11ea-8be8-22005e0c8381.png)
![image](https://user-images.githubusercontent.com/313146/85959353-ee5d0680-b969-11ea-8749-b8baba4639e6.png)
![image](https://user-images.githubusercontent.com/313146/85959357-f2892400-b969-11ea-87e8-0f25c9bc55d8.png)

Opening the file from the same directory within the program (File > Open...) works as expected.

**Comment by richardwilkes** [comment]
Yes, on Windows, the installer doesn't setup the Windows Explorer stuff correctly. You can open files from within the program, but not by double-clicking on a file that has spaces in its name or path in the Windows Explorer. This is a known bug with Java's packaging tool -- nothing I can do about it at the moment. The next release of Java will have a fix. I tried to use the early access release, but found that unreleased version broke all kinds of other stuff on Windows, making it unusable.

**Comment by richardwilkes** [comment]
The next release will use JDK 15, which fixes this problem.
