### ISSUE TITLE
Ritual magic spells disappears from spell containers

### ISSUE THREAD

**Issue by Elunian** [richardwilkes/gcs#225]
Hello! I noticed that version 4.19 of GCS have Spell Container, but don't have Ritual Magic Spell Container. When I add Ritual Magic Spells to Spells Container, they disapper after saving and opening. 

![111](https://user-images.githubusercontent.com/58914123/86126691-6ef54180-bae7-11ea-92fb-cce9fc34c9ab.PNG)

![112](https://user-images.githubusercontent.com/58914123/86126694-6f8dd800-bae7-11ea-939d-363d2b33090b.PNG)

**Comment by richardwilkes** [comment]
(sigh) The data is being stored but not loaded in this case... so as long as you don't save again, it can be recovered from the file after I fix the issue. I'll try to find time to create an update today.

**Comment by richardwilkes** [comment]
Fixed in v4.19.1

**Comment by Elunian** [comment]
Thank you!
