### ISSUE TITLE
Add option to show information about level adjustments in the note area (currently shown in tooltips)

### ISSUE THREAD

**Issue by evsan** [richardwilkes/gcs#227]
Advantages, Talents and Encumbrance modify skills and this information could be shown in notes under the skill

e.g.

There are Advantages: Smooth Operator-2 and Voice
Skills: Fast-Talk includes all modifiers (+2 from Voice, +2 from Talent) or Streetwise includes +2 from Smooth Operator but this information is not visible ATM.  Notes could be generated automatically: `inc. +2 from Voice; +2 from Smooth Operator` and `inc. +2 from Smooth Operator` respectively

**Comment by richardwilkes** [comment]
The tooltip for the SL column already tells you this information

**Comment by evsan** [comment]
Thanks! So maybe the configuration to show it also/or in notes. And/or add this information to pdf
