### ISSUE TITLE
1 Issue & and 1 Request with Newest Version

### ISSUE THREAD

**Issue by Siliconhobbit** [richardwilkes/gcs#234]
**#1** Why does the Installer require me to restart my computer to do an update to the program? This should not be necessary at all.

**#2** Can you add the ability to add Advantages to Equipment pieces (assuming an Equipment list is still available?) I'm not sure about other GMs but I've often made magic items for my players that give Advantages (temporary or permanent) through a magic item. Being able to do this would be great. Right now when you create a new piece of equipment, edit, or duplicate then edit an item, all you have available is Features. Features however doesn't allow you to directly add an Advantage to an item. Canthis be changed?

**Comment by richardwilkes** [comment]
If the installer is requiring that, it is something specific to your machine or how you’re using your computer, as it has never asked me nor anyone else I’m aware of to restart the computer.

As for adding an advantage... that’s exactly what features are. If you want it to somehow add a separate advantage line item in the advantages section, then no, that’s not something I plan to ever allow — you can easily drag and drop the advantage there to give the same effect.

**Comment by Siliconhobbit** [comment]
I'm unsure how you can drag & drop an Advantage onto the Features tab of an item. Once I double-click on an item to edit it, that pop-up no longer allows any other tab behind it to be accessed. In fact there is no way to interact with anything else but the pop-up box for that item, while in edit mode.

Can you elaborate?

**Comment by richardwilkes** [comment]
I meant that the effects that advantages can provide are all done via features, so you can replicate them in the item if you wanted. For example, if you had a Ring of Dexterity, you can add a feature to it that gives the character +1 to DX when it is equipped.

**Comment by Siliconhobbit** [comment]
While that is the case, and adding affects such as an Attribute increase is easy to do, I'm more concerned with adding the effects of other Advantages that do not directly affect Attributes or Skills.

For example, if I as the GM game a play a Magic Helmet that provides 360 degree vision, as per the actual Advantage, how could I go about adding that effect the the actual helmet itself, and then have that Advantage show up on the Character Sheet? 

Could you not add Advantages to the Features tab like this:
![Ads_disads_GCS](https://user-images.githubusercontent.com/68209466/87367351-b8fb1000-c548-11ea-8120-e6187a2c9cca.png)

Forgive the font selection if you will, as I don't know the font used.

But anyways, you get my idea. This way you could add Advantages, Disadvantages, Perks, Quirks, Traits, etc to items, magic items, and such. You could provide a point cost if needed, but I'd suspect that most GMs do not charge their players Character Points when they give them magic items.

**Comment by richardwilkes** [comment]
That’s just not practical. Adding what amounts to fake data is problematic and would cause lots of user interface issues that I have no interest in fighting on a constant basis. Any advantage that doesn’t add specific bonuses of some sort and is just text on the sheet can be mimicked in exactly that way: add a note to the equipment that states what it does OR just drag and drop the appropriate advantage to the sheet when it is enabled. I know that’s not what you want, but what you’re asking for isn’t something that I will likely ever try to do thanks to the many issues it would cause.
