### ISSUE TITLE
Ritual Magic Spells disappered again

### ISSUE THREAD

**Issue by Elunian** [richardwilkes/gcs#235]
Hello! I downloaded last version of GCS and updated libraries, and all ritual magic spells disappeared again.
When I add new ritual spells, save the, close and open character sheet again, all remains. Is there a way to get ritual magic spells back? 

![image](https://user-images.githubusercontent.com/58914123/87439111-0d5dc880-c5f9-11ea-96b2-8cc4af4c1b81.png)

Also, every instalation of new version delete previous version. Is there an option to not do that?

(Sorry for mistakes, English isn't my native)

**Comment by richardwilkes** [comment]
I am unable to reproduce any problem with loading ritual magic spells. Are you sure you're using the latest version (v4.21)?

As for deleting previous versions... that all depends on the OS and how its installers work. Why do you care if the old version of the software is removed? Having more than one version installed is likely to cause problems, as trying to open a file saved with a newer version with an older version is unlikely to work correctly.

**Comment by Elunian** [comment]
I open the same file in two versions, I have 4.21.0, and my friend have version 4.19.1
New version don't display any spells and old version display them.
![screen1](https://user-images.githubusercontent.com/58914123/87448677-cf66a180-c604-11ea-817f-14c21c811557.PNG)
![screen2](https://user-images.githubusercontent.com/58914123/87448730-e0171780-c604-11ea-83f8-0f3fd418fa61.png)

This character file still have xml format, as I understand.

**Comment by richardwilkes** [comment]
OK, I see the issue now. A couple more cases that weren't handled. (sigh)

Please attach the character sheet that is having the problem so that I can verify my fix works for your particular case before I make a new release.

**Comment by Elunian** [comment]
https://drive.google.com/file/d/13vuQhPqCcQTaotxLX31MeLa0c8LdBknc/view?usp=sharing

Here is it. I have noticed few small probles, should I make another Issue for them?

**Comment by richardwilkes** [comment]
Yes, please

**Comment by richardwilkes** [comment]
I attempted to grab that file from the google drive yesterday, but it required me to ask permission -- which I did. Still haven't gotten approval to download it. Why don't you just attach it here?

**Comment by Elunian** [comment]
Git Hub can't attachs *.gcs file. If I understand right, I can add *.gcs to any archive and attached. I created accout here only for describing previous bug with ritual magic spells.

**Comment by richardwilkes** [comment]
No worries -- you must have approved the access because I was able to retrieve the file yesterday evening. Odd that GitHub won't allow you to attach a file of any type. I guess they want you to zip them up first. (sigh)

**Comment by richardwilkes** [comment]
By the way, I plan to make a release either today or tomorrow that will contain a fix for this issue.
