### ISSUE TITLE
"Unidentified key: 'MANA_COST'"

### ISSUE THREAD

**Issue by arconom** [richardwilkes/gcs#236]
Either the documentation for templates is wrong or the program is wrong. 

I added spaces after the @ to not ping people.

   ,"spells":[
        @ SPELLS_LOOP_START
        {
            "name":"@ DESCRIPTION_PRIMARY"
            ,"description":"@ DESCRIPTION_NOTES"
            ,"modifiers":"@ DESCRIPTION_MODIFIER_NOTES"
            ,"class":"@ CLASS"
            ,"college":"@ COLLEGE"
            ,"level":"@ SL"
            ,"difficulty":"@ DIFFICULTY"
            ,"relativeLevel":"@ RSL"
            ,"points":"@ POINTS"
            ,"duration":"@ DURATION"
            ,"manaCost":"@ MANA_COST"
            ,"manaMaintain":"@ MANA_MAINTAIN"
            ,"castTime":"@ TIME_CAST"
            ,"ref":"@ REF"
        },
        @ SPELLS_LOOP_END
    ]

**Comment by richardwilkes** [comment]
Can you be specific as to what is wrong? I'm not near the computer right now to try this.

**Comment by rsl** [comment]
can someone fix the fact that my name is mentioned above [@rsl]? i keep getting updates on this thread. all good except my inbox is full enough as is. thanks.

**Comment by rsl** [comment]
actually seems like a bunch of people are being pinged on this.

**Comment by arconom** [comment]
The template engine doesn't seem to recognize @ MANA_COST

**Comment by richardwilkes** [comment]
First, there should be no space after the @ symbol. That might be your problem here. I likely won't have an opportunity to take a look for another day or so at best.

@rsl Not sure why you'd be getting notifications at all... unless perhaps you've marked yourself as a Watcher of the project, in which case I think you may get emails for things like this.

**Comment by arconom** [comment]
it was because of the @ in the code, hence the spaces

**Comment by richardwilkes** [comment]
Ah... I missed that. OK. Will take a look once I get a chance. Thanks for clarifying.

**Comment by richardwilkes** [comment]
OK, just checked the code. It has been MANA_CAST since sometime in 2016. The docs on the website just have a typo, which is now fixed.

**Comment by rsl** [comment]
i was getting notification [which will not stop] because someone named a "variable" @rsl. code like this pinged evvery github user with an @ name matching any of those variables. not great.
