### ISSUE TITLE
Feature Request: High Contrast Compatiibility

### ISSUE THREAD

**Issue by SaintNoof** [richardwilkes/gcs#237]
Hi! I'm a legally blind GURPS initiate who would really love to use GCS, but it doesn't work well with my eyes because of its colors. I use the High Contrast 1 theme in Windows 10, so I'm hoping that maybe it would be possible to release an update soon that uses dark backgrounds and light text to help me get the most out of this awesome program!

**Comment by richardwilkes** [comment]
I think this is essentially subsumed by #88, so adding this link and closing.
