### ISSUE TITLE
Tags for traits with "from container" to be included or excluded in output loop

### ISSUE THREAD

**Issue by efinest** [richardwilkes/gcs#246]
The goal is to allow a block format for text output that allow you have something like:

@EXCLUDE_CONTAINER_TRAITS Advantages:@ADVANTAGES_LOOP_START @DESCRIPTION_PRIMARY @DESCRIPTION_MODIFIER_NOTES_PAREN [@POINTS];@ADVANTAGES_LOOP_END

where the output might look like: 

Advantages: Combat Reflexes [15]; Body of Fire [XXX];  High Pain Threshold.

where the Body of Fire metatrait is listed but the components are not.  Code to list only group names and individual components of the trait would be like:

@LIST_CONTAINER_TRAITS @ADVANTAGES_LOOP_START @DESCRIPTION_PRIMARY @DESCRIPTION_MODIFIER_NOTES_PAREN [@POINTS]:;@ADVANTAGES_LOOP_END

where the output might look like:
Body of Fire [XXX]: ST 0 [-100]; +10 HP [0]; etc

with each line being a group and the traits associated with that group.

**Comment by richardwilkes** [comment]
I'm not sure that this is practical in the current form, as container nesting can be arbitrarily deep and not just one level, which you seem to assume in the above request. Can you expand on what you're hoping to see when there are items nested many levels deep?

**Comment by efinest** [comment]
If HTML or PDF have a note to indent, perhaps TEXT could have a note to surround them with curly braces or something? 

Just a way to figure out which traits belong to each container in the text output. In the HTML or PDF output you can tell by the indenting.

**Comment by crnormand** [comment]
> I think this might be better suited to generating a file using the current keys and then running some sort of custom post-processor on the result that you write. 

To be able to make a post processing work, an advantage (or skill or spell) needs to have a KEY indicating its parent.   Equipment has @LOCATION (which somehow didn't make it to the templates web page... sorry).    Any thing that can have a container (Advantages, Skills, Spells, etc.) probably needs a "parent" key, which will allow the post processor to determine what belongs where.

**Comment by richardwilkes** [comment]
This can actually be solved using the @PARENT_ID key
