### ISSUE TITLE
Rule of 20 is (erroneously?) applied to techniques that default from attributes

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#251]
I was going through and updating the last of my old sheets before I install the newest version, and I came across a few issues. The first one is that techniques defaulting directly to an attribute (Neck Snap was the specific one I noticed) are having the Rule of 20 applied, making their effective level lower than it should be. As far as I'm aware, the Rule of 20 is only supposed to apply to skills.

**Comment by richardwilkes** [comment]
Fixed in 81fe03052dbe23eef9d09cc099cb7ede38dfa21a
