### ISSUE TITLE
Allow modifiers to subtract points from the final cost

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#252]
This is the second thing I discovered while going through my old sheets. I can't find a way to properly represent Temporary Disadvantage's maximum point break. If I set it to just subtract the maximum point break, that will subtract it from the *base* point value, before modifiers, which means it won't be quite correct. Some way to make this work that isn't just "add a separate disadvantage and make it a metatrait" would be nice.

**Comment by richardwilkes** [comment]
This will require an additional modifier type and changes to the UI to accommodate it.

**Comment by richardwilkes** [comment]
I was looking at this today and can't come up with a reasonable way to represent this in GCS. It requires a modifier that somehow knows the cost of another separate trait to enforce a limit with. That's not something I'm likely to ever support.

Instead, for the few cases that would run afoul of this limitation, it seems like you could just compute what the actual deduction should be and set the Temporary Disadvantage cost to that.
