### ISSUE TITLE
Bluescreen caused while running other apps

### ISSUE THREAD

**Issue by Kaill3r** [richardwilkes/gcs#253]
unfortunately i didn't catch the bluescreen message itself, but when trying to open a program using UE4 and EAC via steam with chrome open (3 tabs), my computer Bluescreened. i've had multiple issues with GCS using up a tonne of memory and CPU but i've never had it bluescreen before the most recent version. (supposedly there was a memory.dmp created during the crash, but none was found)

**Comment by richardwilkes** [comment]
This sounds more like your machine ran out of available RAM than anything GCS is doing. GCS itself is constrained by the Java VM and is only permitted a specific maximum amount of RAM. I don't recall what that is off the top of my head, but I believe it is somewhere around 2GB -- that's way more than GCS should ever consume unless you open large or many PDFs with it, though.

If you can provide a reproducible case, I'm happy to look and see if there is anything that can be done... but short of that, there isn't anything I can do. Feel free to reopen this and attach that info if you do have the steps needed.
