### ISSUE TITLE
Weapon master damage bonuses on weapons that can be used either one or two handed don't calculate right

### ISSUE THREAD

**Issue by efinest** [richardwilkes/gcs#254]
I was building a weapon master with ST19 and a Mace.  I noticed that the +2/die bonus was giving twice what it should no matter how I set the usage contains/does not contain values.

**Comment by richardwilkes** [comment]
Please attach an example of what you are doing, and state what you expected.

**Comment by efinest** [comment]
Example 1:  Here the bonus is right for one handed use. I wouldn't have expected any bonus for two hand use (should have stayed at 3d+3) since I specified it by Axe/Mace skill where the relative bonus is +2.

![axe_mace](https://user-images.githubusercontent.com/30058862/91311904-3dac9100-e779-11ea-80bc-dca0b311aa31.png)

Figuring that it might be better to use the "usage" tag instead, I tried to add an entry for a bonus to throwing damage only.  Instead, it added +12 (+2/die twice?) to Thrown when I expected +6 damage (+2 x 3 dice). 

![mace throwing](https://user-images.githubusercontent.com/30058862/91313340-e27b9e00-e77a-11ea-8fc0-610b584a1baa.png)

Using the usage tag for melee didn't help either. It always added twice what I expected.

**Comment by richardwilkes** [comment]
Please attach the sheet so I can take a look

**Comment by efinest** [comment]
[mace weapon master.gcs.zip](https://github.com/richardwilkes/gcs/files/5131179/mace.weapon.master.gcs.zip)
Sure, sorry about the zip file, it wouldn't take a .gcs

**Comment by richardwilkes** [comment]
Definitely something not quite right here with the resolution. I'll likely have to make a change in the code to address this. Not sure when I'll get to that, but I have been fairly active lately, so hopefully you won't have to wait too long. In the meantime, you can always just go in and adjust the Melee Weapon entries appropriately.

**Comment by efinest** [comment]
No rush. I fiddled until I it presented right. I just thought I would report back what it was doing.
