### ISSUE TITLE
Invalid or unsupported type: [null]

### ISSUE THREAD

**Issue by aonphleacs** [richardwilkes/gcs#255]
I'm trying to compile on Manjaro and after installing JDK14 and cloning from Github I get the following:
```
Removing any previous build data... 0.002s
Compiling... 11.232s
Copying resources... 0.105s
Creating modules... 1.266s
Extracting localization template... 0.237s
Packaging the application... 
Error: Invalid or unsupported type: [null]
```
Any help would be appreciated!

**Comment by richardwilkes** [comment]
I'm not familiar with that distribution, but if you're getting packaging errors, then most likely your particular distribution doesn't have the necessary bits. You can still build it in the unpackaged form, using the --unpackaged option.

**Comment by richardwilkes** [comment]
I'm going to go ahead and close this out... but feel free to either pop into the GURPS Discord and ask me additional questions in the #apps or #apps-dev channel channel.

**Comment by aonphleacs** [comment]
Brilliant. I wasn't aware of --unpackaged. That worked!
