### ISSUE TITLE
Issue with "&" symbol when exporting to XML

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#258]
Strings containing a lone ampersand symbol (e.g. "Illusion & Creation") when exporting a character sheet to an XML file for Fantasy Grounds will fail to import in Fantasy Grounds, with the following error:
`import: An error occurred while parsing EntityName`
This can be fixed by replacing instances of the "&" character with "&amp;" when exporting to XML.

**Comment by richardwilkes** [comment]
This is already done by default, but can be disabled by a directive `@ENCODING_OFF` in the file. I've not checked those templates to see if they use it or not, as I don't have Fantasy Grounds so have never tried them.

**Comment by richardwilkes** [comment]
Just got a chance to check and indeed each of the Fantasy Grounds templates have the @ENCODING_OFF directive in them. I assume the original author did this for a reason, though I couldn't say what that would be.

@crnormand is the original author of those, IIRC. Chris, do you have any insight here?

**Comment by crnormand** [comment]
Hmmm... not certain.   I will investigate.

**Comment by crnormand** [comment]
I removed "@ENCODING_OFF" from the output template, and the export still failed.   I have to recreate my build environment, so it may be a few days before I can get this resolved.

**Comment by rinickolous** [comment]
Removing `@ENCODING OFF` fixed the issue for me, as far as I can tell.

**Comment by crnormand** [comment]
I am glad it worked for you... I'm still trying to get my dev environment up and working ;-)

**Comment by richardwilkes** [comment]
What's the issue with your dev environment, @crnormand? Something I might be able to help with?
