### ISSUE TITLE
Add NPC Characters sheet generator

### ISSUE THREAD

**Issue by velteyn** [richardwilkes/gcs#264]
Hello,
I would like to suggest a new feature. A NPG Character sheet list . A quick list with a least 10 characters on an A4 page . All the informations should be very essential (character stats on a row instead on a column. etc)  The cool thing could be that a user can build  a NPC quick sheet using the same procedure as a regular character sheet (with calculations etc) but haveing many characters on the same page. A plus could be that the program generates the sheet randomly
What do you think ?

**Comment by richardwilkes** [comment]
I'd recommend putting together a suitable NPC output template, then using a script to do the N-up presentation. GCS doesn't really have a concept of outputting multiple sheets to a single sheet as that raises a fair number of issues that would have to be addressed and it does not seem worth the work, given a script could do this as a post-processing step.
