### ISSUE TITLE
Library Search does not provide enough infomation for identically named items

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#267]
I search Dwarf. I get many results. How do I know which one I want? It doesn't tell me. (See figure 1).
See Figure 2 for a mock-up of my proposal; in a fainter text provide the Path of the result. This allows the user to differentiate between them and find the result they want.
(The path here should technically include "master library' at the root but I think that could be omitted, and root only included for the User Library, or even not at all. The reason is to save space since pretty much every result will start with Master Library.)
Figure 1:
![image](https://user-images.githubusercontent.com/1914417/95596125-bb61fd00-0a98-11eb-903e-f0e3640e1b84.png)
Figure 2:
![image](https://user-images.githubusercontent.com/1914417/95596176-c9b01900-0a98-11eb-8edb-afce72da4425.png)

**Comment by richardwilkes** [comment]
Thanks to the way that drop-down is rendered, I chose not to make it fancy with grayed-out text, but I do now provide the path to the file/folder in question when there are multiple with the same name in the list.
