### ISSUE TITLE
Please allow a third party PDF viewer, if it's not already a thing.

### ISSUE THREAD

**Issue by Lovewyrm** [richardwilkes/gcs#269]
I don't wanna deal with javas BS 'the BROWSE function is not supported on the current platform' from any of the releases that use that.

My web browser is a web browser, not a pdf viewer.

You'd like to be called and conducted with in a way that retains your nature as a human, right?
You'd balk if I treated you like a monkey or something? Right?

If you agree with that, then, yeah. Why not extend that mindset to software.

**Comment by richardwilkes** [comment]
You are free to stop using my software if it so offends you.

**Comment by Lovewyrm** [comment]
Whatever you say, monkey.
