### ISSUE TITLE
Show other types of move

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#27]
When selecting the Advantages of Flight or Amphibious, or selecting the Disadvantage of No Legs (Aquatic or Semi-Aquatic) could we get the Notes in the Advantage/Disadvantage to show Air Move or Water Move as calculated from Basic Speed per each advantage/disadvantage? In addition, would it be possible then to get the Enhanced Move advantage to calculate the Enhanced Move by selecting a prerequisite of the appropriate Move score we're Enhancing (Basic i.e. Ground, Flight, Amphibious or No Legs (Aquatic, Semi-Aquatic).

For quick reference:

- Flight is 2x Basic Speed dropping fractions
- Amphibious equals Basic Move
- No Legs (Aquatic) equals Basic Move
- No Legs (Semi-Aquatic) Water Move equals Basic Move, but Ground Move equals 1/5 x Basic Move.

**Comment by crnormand** [comment]
If this gets implemented, don't forget to add export keys in the Encumbrance loop.  For example:   @flight @water etc.

**Comment by richardwilkes** [comment]
This can be accomplished using custom attributes, so I'm closing it.
