### ISSUE TITLE
Long-term support for loading both XML and JSON saves

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#270]
My group is refusing to upgrade to latest version. Everyone has different versions, some as old as a 2016 version.  Main reason for refusing to upgrade - it won't open their existing GCS files.  They don't want to do the chore of downloading the one of the four 'special versions' and convert every one of their existing GCS files. They are not computer savvy enough to work command line to access the bulk conversion feature.

Two players who upgraded reverted back to GURPS Character Assistant (GCA) for a short time because they thought GCS was broken, refusing to load their old files until the GM gave them his old 4.11 copy (from 2018).

I am being given GCT files (template files) from a GM from old versions of GCS that I can not load.  I am not wanting to keep two versions of GCS on my computer.  She refuses to upgrade to latest version because it will cut her off from her old files.

Nobody in my groups can read my GCS files because I upgraded to new version and when the narrow transition windows was active, I mass-converted my library to the new format. So they can't open any of my GCS files with their old versions. 

I noticed I missed some, mostly not-mine character sheets i've stashed and can't open them unless I put one of transition versions on my computer to convert it.

Both groups appear to be attempting to standardize on the 4.11 version that Raine has. But most are content to keep whatever version they currently have as long as it loads their old files and the newest version refuses to. They seem committed to never upgrade while it won't load their old files.

One player/GM commented that if it continued to load their old saves he would upgrade to latest version.  He said he explicitly didn't care if it silently converted them to the new format. He just doesn't want to go back and convert his hundreds of pre-existing GCS files to the new format with a special version just to be able to load his old files.

I'm thinking GCS is hemorrhaging users while the backward compatibility is broken, at least for loading. Or most of the user base just simply refuse to upgrade, and then switch to competitor if something better than their old version comes out.

I am of the same opinion as that other person. Load both XML and JSON formats, probably indefinitely. Fine to save only in the JSON format.

I'm even fine with silently converting the from XML to JSON when loading old XML-based GCS file even if the user does not explicitly save it, as long as the file continues to load. Would be better to notify user that a automatic conversion is occurring though (when they load old XML-based file) and prompt them to allow it to proceed. I'm not sure if others would be fully ok with aggressive auto-conversion. But I am confident they will be fine with 'load XML or JSON, Save only JSON' (passive conversion) but acceptance will increase if notifying that that saving the previously XML based file will make the file no longer load in pre-4.20 versions.

**Comment by richardwilkes** [comment]
Due to the long-term maintenance burden, I will definitely not add xml loading back into GCS. However, I will consider writing a standalone tool that prompts users for files or directories to convert from old to new, eliminating the need to understand how to use the command line.

**Comment by richardwilkes** [comment]
The main web site now has GUI programs that can be downloaded to upgrade the old xml file format to the json format.

**Comment by 1s0m0rph** [comment]
Is there a way to compile these programs for non debian linux? I'm of the opinion that backwards-compatibility for these older saves (which comprise my entire library of hundreds of characters) is a critical enough feature to warrant continued support, but then I'm not the one doing the maintenance.
