### ISSUE TITLE
PDF export to official looking character sheet (fillable if possible)

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#271]
PDF export option to official looking character sheet, fillable if possible.  Along side (not instead of) current PDF export.

#enhancement

**Comment by SirHall** [comment]
You could theoretically do this already.
GCS can already export to a 'templated text file'.
In theory all you would have to do is create a LaTeX file that when compiled creates a PDF that is atleast *similar* to the official character sheet.
Then export to a text file using your LaTeX template and that should work pretty well.
I'm not sure if you'd be able to release your source files, but it could work.

**Comment by richardwilkes** [comment]
As noted above, this is already possible, at least in theory. GCS provides a wealth of data that can be exported into any textual format via the output template mechanism. If someone were to create it and contribute it, I'd be happy to include it. As I don't find the official character sheet to be all that attractive or functional, this not something I'll be working on myself, however.
