### ISSUE TITLE
+ and - buttons for adding usage lines for Ranged/Melee Weapons are still disappeared

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#273]
I believe this was previously reported a few years ago, still seems to be kicking around.

![Equipment_Window_Ranged](https://user-images.githubusercontent.com/38299571/97606253-f4312a00-19e5-11eb-9012-df25bf9b1fe0.PNG)

**Comment by vilobion** [comment]
Taken another shot to show what happens when I hover my mouse over where I know the buttons are. I'm elbows-deep in a writing another tutorial post on the program, and this sorta weirdness is potentially really confusing for the people who haven't been using it since at least version 4.2.

![DisappearedGCSButtons](https://user-images.githubusercontent.com/38299571/97606400-204cab00-19e6-11eb-8997-31b293858017.PNG)

**Comment by richardwilkes** [comment]
Yes, this is a Windows-specific problem and no amount of debugging has enlightened me as to why Windows has this problem on some installations. The button is definitely there, it just isn't getting drawn.... but only for some users of Windows. I've already invested way too much energy into discovering the problem and will not be looking into it further. Sorry.
