### ISSUE TITLE
Equip/Unequip all items in a container with the container

### ISSUE THREAD

**Issue by Rupert01** [richardwilkes/gcs#274]
It would be nice to have the ability to equip or unequip all items in a container with the container. For example being able to use ctrl+mouse click on the 'equip' field to make the container and everything in it toggle equipped/unequipped, and/or adding a keybind (say ctrl+alt+quote) to do this.

**Comment by richardwilkes** [comment]
You can just select all of the relevant entries (click on the first one, shift-click on the last one), then choose Edit > State > Toggle State (or use the command key equivalent).
