### ISSUE TITLE
[Feature Request] Adding Energy reserve section/ To FP section

### ISSUE THREAD

**Issue by knownexus** [richardwilkes/gcs#275]
Would it be possible to add either an optional modifiable Energy reserve section to the sheet, or add an entry to the FP section for it

As far as i know, there's currently no way to keep track of that kind of thing other than adding a piece of equipment to track it

thanks

Sorry if this is a Dup, i couldn't see any similar request

**Comment by Maeriden** [comment]
I'm willing to contribute manpower for this feature. I don't feel like I can tackle it all on my own, but if someone can provide a list of things to do and, more importantly, a sketch of how the UI-related parts should look like, I could implement them.

**Comment by richardwilkes** [comment]
It isn't clear to me what is actually desired. I'm aware of the Energy Reserve option in GURPS, though I've not used it myself. I understand there are other potential "point pools", too, though... I just don't know what they might be. There is also the issue of limited space -- even though the default configuration for a US Letter page layout has a fair amount of available space in the current HP & FP block, that's not the case once you have a character with a supers-level ST, or are using a smaller page format... or worse, both.

**Comment by knownexus** [comment]
@richardwilkes Essentially something similar to what already exists in the Fatigue Points section
I.E. 
x Current
y Basic
Where basic is taken from a named advantage, e.g. Energy Reserve n

To allow for custom point pools, this could be a toggleable thing, so it doesn't have to always be on the sheet, but available if wanted

Personally from a design perspective, i would be okay with the "Lifting and Moving Things" section to be dropped down to where the Modifier + Reaction section is, in instances where the custom pools are enabled

Which would potentially allow for ~3 different custom pools to be enabled at once
But ofcourse there are a lot of design options for it

**Comment by richardwilkes** [comment]
So you're advocating for a new feature option that creates pools. I missed that detail and that you wanted some fixed set. The feature route makes more sense and is much more flexible... but does cause huge layout issues. Layout, in particular, is not easy to make work well with arbitrary things like this, unless forced into list form, like I do for most of the sheet.

**Comment by knownexus** [comment]
a quick mock up,
A couple of ideas for layout could be this
![image](https://user-images.githubusercontent.com/19297623/98875188-997ee000-2473-11eb-8980-24d0e62ec71d.png)

Or this, 
![image](https://user-images.githubusercontent.com/19297623/98875367-02665800-2474-11eb-900c-799b33e546b8.png)

Where Lifting and Moving is moved down to the line below
However from a quick glance at the code, it looks like the page stops rendering as the "first page" after that point
so it would either need extending down one, or continues onto the next page

But these are just potential ideas

**Comment by richardwilkes** [comment]
Yes, I guess just extending the whole thing vertically when you have those in there isn't the most horrible thing. It does leave a bunch of dead space, but that's probably unavoidable. I'll give this some more thought.

**Comment by maw3193** [comment]
I think an arbitrarily-long list of pools would be quite useful.
In my own games, I've had to track:
* A Psionic Energy Reserve
* The amount of charge left in a Psychotronic Battery
* a gauss rifle's remaining shots
* The number of spare energy cells I have to reload with.

e.g. perhaps an element:
```
 -----[Pools]-----
|<Pool Name 1> X/Y|
|<Pool Name 2> X/Y|
 ------------------
```

**Comment by richardwilkes** [comment]
@maw3193 For the rifle shots & energy cells/batteries, you can already do that with the "Uses" feature of equipment. This particular feature is unneeded for those types of things.

**Comment by richardwilkes** [comment]
Technically, you could create a dummy piece of equipment for each energy pool you wanted to track and do it that way, as well. I can see the appeal of having the pools all show up in a unified spot on the page, though.

**Comment by jonathanmaw** [comment]
Ah, I didn't see Uses, thanks!

**Comment by kaldrich001** [comment]
If this were to be implemented at some point, hopefully the name(s) of the pools being used could be customized. I saw it because I was originally going to make a post about RP and LFP from After the End, but I saw there was already a very similar one.

**Comment by richardwilkes** [comment]
Custom point pools, among other things, will be in the next release.
