### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#277]
Since GitHub doesn't provide me with a way to contact my sponsors (well, other than in bulk to *all* of them at once), I'm using this issue as a way to (hopefully) contact new sponsors so that I can give them access to the sponsor Discord.

**Comment by richardwilkes** [comment]
@HoopsMcCann what is good way to send you the link to the sponsor Discord?

**Comment by HoopsMcCann** [comment]
Hey Richard
I guess just here on email works ok right?
Thanks again for your amazing work making GCS!
Ben

**Comment by richardwilkes** [comment]
Hi, @HoopsMcCann 

I sent an email with an invite to the GCS Discord in it to you a few days ago and wanted to check to see if you ever got it as I haven't seen you show up there. If you did and just have no interest in the Discord, that's fine -- I just want to make sure the invite didn't go into a black hole or that I made a typo when entering in the address.

- Rich

**Comment by richardwilkes** [comment]
@Fellzorn what is a good way to send you the link to the sponsor Discord?

**Comment by Fellzorn** [comment]
Please simply use this e-mail address.Thanks in advance.BestAndreasAm 13.11.20, 17:06 schrieb Richard Wilkes <notifications@github.com>:

   
  @Fellzorn what is a good way to send you the link to the sponsor Discord?

**Comment by richardwilkes** [comment]
> Please simply use this e-mail address.Thanks in advance.BestAndreasAm 13.11.20, 17:06 schrieb Richard Wilkes <notifications@github.com>: @Fellzorn what is a good way to send you the link to the sponsor Discord? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Unfortunately, GitHub doesn't provide me with your email address, which is why I was asking. If you don't want to post it here, you are welcome to send an email directly to me at wilkes@me.com -- hopefully the spam filters won't prevent me from seeing it -- at which point I can send you the invite to the private Discord server. If you aren't interested in that, that's fine as well -- I just want to make sure folks have the opportunity if they want it.
