### ISSUE TITLE
Missing Spell Type Info from FG Export Template

### ISSUE THREAD

**Issue by baoghal** [richardwilkes/gcs#280]
On exporting a character sheet for Fantasy Grounds import, the type node is missing the type information for spells.
```
<id-1>
   <!-- removed for brevity -->
   <type type="string"></type>
   <!-- removed for brevity -->
</id-1>
```
Expected: type contains IQ/H or IQ/VH

**Comment by richardwilkes** [comment]
@crnormand is this something you can take a look at?

**Comment by crnormand** [comment]
Sure thing.
