### ISSUE TITLE
Add Vitals Location to the locations that the DR Featuire can apply to.

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#281]
Currently, while the vitals are listed in the built in hit location table, there is no way to directly add DR to just the vitals. There are rules that do support this in GURPS, such as the Basic set rules for locational DR, as well as Low Tech Instant Armor's Pectoral Plates. This seems light a relatively simple issue to fix, since Vitals are already displayed and shown.

**Comment by richardwilkes** [comment]
Removed the restriction on selecting the vitals location and changed the text for the torso location to make it clear that it includes not only the torso, but the vitals as well.
