### ISSUE TITLE
Wildcard cost and Skill Level

### ISSUE THREAD

**Issue by juliopcrj** [richardwilkes/gcs#283]
When creating a wildcard, the cost should be VH * 3.
I create a wildcard in spells, set it to "W" difficulty, and the skill level is the same as when setting to "VH".

I couldn't find a workaround for this problem yet, so I'm just writing the correct Level as a comment.

**Comment by richardwilkes** [comment]
This works correctly for me on a new sheet. I suspect you have some advantage or other feature causing other modifications as well. Please post a sheet that illustrates the problem -- and reduce it to as few entries as possible -- ideally, just a single skill.

**Comment by juliopcrj** [comment]
With skills, it works correctly, the problem is with spells. I created a new file, added a new spell, changed the difficulty to W, and it registers as the same level as VH.

**Comment by richardwilkes** [comment]
Ah. I missed that part. I'm relatively sure that spells do not have support for W, which is why it is behaving as VH. What rulebook adds this as an option?

**Comment by juliopcrj** [comment]
Gurps Magic, page 202

**Comment by richardwilkes** [comment]
Thanks. I'll take a look and update GCS appropriately. Odd that no one in all these years has mentioned this before.

**Comment by juliopcrj** [comment]
I guess no one bothered to try using wildcard before haha

Thank you!

**Comment by richardwilkes** [comment]
Ah... I think I know why. When reading page 202, "Wildcard Magic", they specifically reference a "Magic!" *skill* to be used in place of all spells... so the accepted way is to use that skill and not a spell entry -- which makes sense, given that all the extra fields on a spell entry have no meaning in this context.

That said, I see no reason GCS can't support having a spell entry with a wildcard difficulty setting.

**Comment by richardwilkes** [comment]
Fixed. Will be in the next release, whenever that may be.

**Comment by juliopcrj** [comment]
Thank you!
