### ISSUE TITLE
Ritual Magic Spells change to regular Spells when moved to a Library.

### ISSUE THREAD

**Issue by PlasticPhoenix** [richardwilkes/gcs#284]
I have noticed that as I decided to place all my custom Ritual Magic spells into a campaign library that when I drag them over to the library from the character sheet, they change back to regular spells. Dragging them back to the original sheet, they do indeed stay regular spells.

**Comment by richardwilkes** [comment]
I”m not where I can check at the moment or I’d just run it locally myself and verify: this is with the latest version of GCS (v4.26), correct?

**Comment by PlasticPhoenix** [comment]
Ah, ok. Little more info. If I drag them directly into the Library, no problem. However, on my character sheet I had them inside a spell container to organize them into Colleges. When I drag a Spell Container that has RM spells inside it, they all convert back to regular spells. If I create a Spell Container inside the library first and then drag them in, it also works correctly. If I drag a spell into the library and then into a container, it works correctly. So, just the direct "batch" transfer seems odd. I can work around that for now, though.
