### ISSUE TITLE
Ritual Magic spells only can be (H)ard difficulty.

### ISSUE THREAD

**Issue by PlasticPhoenix** [richardwilkes/gcs#285]
I have created several Ritual Magic spells, split between A & H difficulties. But, noticing cost discrepancies from my worksheet, I checked them and every one of them was set to H. I changed them to A, closed the RM spell, reopened it and it was back to H.

**Comment by richardwilkes** [comment]
Again, please verify that you’re running the latest version of GCS. Both this and #284 that you reported are ones I recall happening in a past release and being fixed by a subsequent release.

**Comment by PlasticPhoenix** [comment]
Yes, I am using 4.26 as of this writing. I just now create a new character, added a new Ritual Magic spell. It defaulted to H. I set it to A and closed the spell. Opened and spell and it was back to H.
Maybe some old error got reverted?

**Comment by PlasticPhoenix** [comment]
Ok, I manually edited the JSON file and saw that the RM spell had:
"difficulty": "IQ/H",
So, changed it to IQ/A and loaded it, and yes, it was now A. However, I couldn't change it back to H, it just ignored the change when the object was closed and reopened.
Maybe the code in 4.26 isn't properly setting the difficulty property when changing the dropdown?

**Comment by richardwilkes** [comment]
Implemented support for A(verage) difficulty. Note that this is a variation not found in the official rules.
