### ISSUE TITLE
[Feature Request] Possibility to display Skill difficulty on sheet

### ISSUE THREAD

**Issue by Fellzorn** [richardwilkes/gcs#289]
I really appreciate GCS for generating PC and NPC. But old fashioned as I am I prefer to have a paper version and a pencil (and some dice) at hand when I am playing. So  I use GCS to generate my character and transfer it on a standard character sheet.  Usually I know the difficulties by hard. But there are exceptions and it would be easier if I could simply copy them from the GCS sheet to have them at hand for levelling. From time to time I also have new players which are playing GURPS for the first time. To ease the start I hand them a pdf  GCS sheet with their stats. For them it also would be easier if the difficulty would be ready available when spending character points. 
Overall a possibility to optionally show the difficulty of a  #skill would be a nice to have feature for me.

**Comment by devakm** [comment]
You mean base difficulty before modifiers?

**Comment by Fellzorn** [comment]
Yes, thank you for the clarifiaction
