### ISSUE TITLE
Scale UI properly on hi-dpi 4k Linux 

### ISSUE THREAD

**Issue by cdobrich** [richardwilkes/gcs#293]
I am running Linux (Ubuntu 20.10) with KDE. I am running a high DPI (4k) monitor display. I am unable to get GCS to scale up. I have tested with version 4.27.0-1. I tested this building from git today, and also downloaded the provided .deb file and tested with that. I verified that I'm running Java 15.

The primary problem is the text on the menus.

```
java --version
openjdk 15 2020-09-15
OpenJDK Runtime Environment (build 15+36-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 15+36-Ubuntu-1, mixed mode, sharing)
```

I have tried building GCS from the the git repository. I generated the .deb file but it did not change the font size adjustment.

I tried invoking GCS from the commandline with the extra arguments "-J-Dsun.java2d.dpiaware=false" without quotes and trying with various extra spaces, but nothing works. This is what I get from invoking over commandline:

```
/opt/gcs/bin/GCS -J-Dsun.java2d.dpiaware=false
unknown option: -J-Dsun.java2d.dpiaware
```

Please advise and thank you.

**Comment by richardwilkes** [comment]
That won't work. If you really need to set such options, you'll need to do so via the GCS.cfg file. I don't recall the exact path for that on Linux off the top of my head, but you should be able to search for it. Find that file and add additional java-options= lines.

**Comment by cdobrich** [comment]
The main program GCS.cfg file is located in /opt/gcs/lib/app/GCS.cfg. What option should I put into the file?

Should look like this?

```
[Application]
app.mainmodule=com.trollworks.gcs/com.trollworks.gcs.GCS

[JavaOptions]
java-options=-Dhttps.protocols=TLSv1.2,TLSv1.1,TLSv1
java-options=--module-path
java-options=$APPDIR/mods
java-options=lines
```

Also what arguments should I use to invoke the program? Anything like --lines=false?

**Comment by richardwilkes** [comment]
No, don't literally add the line `java-options=lines`... add the options you want. Each java-options= line specifies a single argument to the underly JVM. Assuming you think you need to set -Dsun.java2d.dpiaware=false, you'd add a line to the end like this:

java-options=-Dsun.java2d.dpiaware=false

Whether that will actually do what you want, I'm not sure. It used to have an effect, but may not with the newer JVMs.

**Comment by cdobrich** [comment]
I know this issue is closed, but this does not address the problem of 4k hi-dpi scaling. Is there any way I can request this feature be added?

**Comment by richardwilkes** [comment]
You are welcome to reopen it if you can provide something I can actually do. High resolution displays work well in every case I have access to try. I’ve done so on many versions of macOS, a few versions of Windows, and a few versions of Linux — but there are a zillion permutations of Linux alone and at least the one you’re using doesn’t work properly with the combination of Linux + your hardware + GCS. Short of having your specific setup, or a reproduction case that I can replicate on my systems, I see no way to address the issue. :-(
