### ISSUE TITLE
Add USES and MAX_USES Output Template keys (for Equipment)

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#295]
All your fault really... you had to bring up "Uses" in the #vtt-foundry channel.   Just kidding  ;-)

I don't know if you knew, but the USES column doesn't appear in the "HTML - PC.html" Output Template (which is why we don't have it)

![image](https://user-images.githubusercontent.com/8931036/107282533-1563d680-6a29-11eb-9226-50db28a6d85a.png)

**Comment by richardwilkes** [comment]
Yep. That's because it was never added as a key that could be exported, hence impossible to export into the html sheet. I'll add that for the next release, though. Thanks for filing this.

**Comment by richardwilkes** [comment]
Implemented... @crnormand could I get you to make whatever changes are necessary in your template to make use of this? Then I'll push out a new release.

**Comment by richardwilkes** [comment]
(There is now a @USES and a @MAX_USES key you can use on equipment)
