### ISSUE TITLE
Add the ability to disable appearance random info generation

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#299]
When adding a new character with all those field filled, I MUST edit them to change the info. If they were blank I would only need to edit what I want to.

Just like the random name if the appearance info could be disabled.

**Comment by richardwilkes** [comment]
I'll change the checkbox that currently controls whether the name is randomized or not to control whether the various auto-filled fields in the identity and description blocks are auto-filled or not instead.
