### ISSUE TITLE
@TYPE only works inside @ADVANTAGES_LOOP_START within a Template.

### ISSUE THREAD

**Issue by mehalforc** [richardwilkes/gcs#300]
Would like to have @TYPE work anywhere there is a Container, when outputting a template. I sometimes group Skills, Spells and Equipment. It would be nice if the template knew if it is a Container of @TYPE. (Helps me with the "Down Arrow" in front of the Container Name when outputting an HTML Template.)

**Comment by richardwilkes** [comment]
Sounds reasonable. Added a moment ago. Will be in the next release, whenever that is, or you can build GCS from source to get it now.
