### ISSUE TITLE
Center list when using the "Add extra space around Encumbrance table rather than around FP/HP table" option

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#301]
I don't know if this would be possible (or at least if it would be more difficult than I imagine, but it would make the sheets look better for me. The whole reason I would want to change where the extra space goes is aesthetic reasons, and I think it would look a lot better if the "Lifting & Moving Things" list was centered rather than having a bunch of empty white space on one side and not the other.

**Comment by richardwilkes** [comment]
I'm reluctant to add any more here... almost didn't allow the recent option to switch where the extra space ended up precisely because I didn't want to end up with a zillion little micro-options for futzing with it. Will keep this open in case I change my mind, though.

**Comment by richardwilkes** [comment]
The preference mentioned has been removed in the upcoming release to make way for the new custom attribute and point pool support. I've decided I'm not going to add additional options for centering, etc.
