### ISSUE TITLE
Support rich text in the Notes list

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#302]
Currently, notes are plain text and while things like tabs can be added, they are not rendered properly. This is compounded by the Note editor using a monospaced font, giving the illusion you can align things by just adding spaces, but the actual display on the sheet uses the same font as the lists, which is set to a proportional font by default.

In addition to supporting tabs, adding support for simple formatting (bold & italics, at a minimum) would be useful. Also support for breaking large notes up such that they display across page boundaries properly, unlike right now.

**Comment by Legendsmith** [comment]
Markdown syntax might be the way to go here. The popularization of discord and other webapps that use markdown *(including github!)* has made it ubiquitous and well known.

**Comment by richardwilkes** [comment]
Markdown support for the notes list was part of the v5.5 release.
