### ISSUE TITLE
Unable to open character from previous version

### ISSUE THREAD

**Issue by atilagbs** [richardwilkes/gcs#303]
I had the version _4.14_ installed and updated to the _4.28._ Now I can't access my previous characters. I've searched online if there was a way to import the raw data or to extract some of the data to paste it on a new file, but found nothing. Is there something that could be done to save my characters and use them on the new version?
I still have the old installer, so my last resort would be to use the old version. But I wanted to give the new version a try.

**Comment by richardwilkes** [comment]
You can go to the main GCS website to download a converter for the old version's format into the new.
