### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#306]
So this would probably be a fairly major undertaking, and I don't know how feasible it is, but I think it would be really useful to have the ability to include vehicles on a character sheet. There's an official table layout you could base it on, akin to the melee and ranged weapons sections that are on the sheets already. Like I said, might not be possible, but I would certainly use it.

**Comment by Nedorus** [comment]
I was having the same issue. I opted to use the 'Attributes...' and the 'Body Type...' to create customized vehicle sheets. I made separate attribute sheets for ground, air and water vehicles and drones (6 in total). Similarly I created 6 different body types (e.g. to reflect the fact that a drone doesn't have windows and a boat doesn't have wheels etc.).
Contact me via Discord if you're interested in getting a copy of my file...

**Comment by richardwilkes** [comment]
I don't currently have any plans to add vehicle-specific support to GCS, as I feel that such a thing probably needs a dedicated tool.
