### ISSUE TITLE
Won't open PDF with accents for page referencing

### ISSUE THREAD

**Issue by tiagoaquinofl** [richardwilkes/gcs#308]
If a PDF contains accents on its name, it won't open.
Error message: Index -4 out of bounds for lenght 16.

**Comment by richardwilkes** [comment]
Which platform are you running? And what is the PDF’s exact name?

**Comment by tiagoaquinofl** [comment]
Windows and macOs
"GURPS 4ª Edição - Módulo Básico.pdf"
I've tried taking off each and every accent... all of them turn out failing.. after removing them all, it works..
