### ISSUE TITLE
Increment skill hotkey doesn't work when editing template

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#310]
The decrement skill hotkey, and both the increment and decrement level hotkeys, work within templates, but not the increment skill hotkey.

**Comment by richardwilkes** [comment]
The increment / decrement skill options shouldn't be enabling themselves for templates, as they are only valid when you have actual levels that can be calculated, which you don't inside a template. I'll make sure they are disabled in a future release.
