### ISSUE TITLE
Issue with new non-damaging attack feature

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#317]
If you put a value in the box that needs to be empty, it permanently makes it impossible to remove for that weapon, always keeping a 0 like before the update. You need to create a new weapon in order for it to display properly.

**Comment by richardwilkes** [comment]
Value in what box... there are a few zillion in there... and I’m not at my computer at the moment.

**Comment by kaldrich001** [comment]
Base Damage, sorry.
