### ISSUE TITLE
Add Extra Resource Pools to Character Sheet

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs#321]
Fatigue Points and Health Points aren't the only resource pools GURPS supports. Energy Reserve exists and can be bought multiple times for different pools.
Roll20 and Foundry VTT both recognize this and add support for extra pools, but the GCS doesn't as far as I can see. Even adding Energy Reserve (Magic) to my character, doesn't add the new pool.

**Comment by richardwilkes** [comment]
I believe there is already a request for this, but I don’t have time tonight to go look for it, so just moved the request in GCS for now.

As I’ve stated before, the main issue here is a lack of a good place to put such things on the current display. Actually adding additional FP/HP-like things isn’t that difficult (in the code).

**Comment by Deliphin** [comment]
I think a good idea might be to take a look at what other character sheets have done.

Roll20: 
![image](https://user-images.githubusercontent.com/14265753/113774209-56acf580-96fd-11eb-8ec8-9bcc7bcca0f4.png)
Stacks them in a dense form. Little difficult for GCS to replicate since you have those notes for HP and FP checks.

If you go this route, one thing that could help is make the Hit Points section a bit more dense by replacing -10, -20, -30 and -40 with a single line, "-x1, -x2, -x3, -x4 basic HP checks", still reminds people how that works.

But I think the best way to do it, would be to make it a 2x2 cluster. On US Letter format, there is a lot of wasted space just for HP and FP. Adding two more sections to the right of them would give us two areas for stuff like Energy Reserve.
The only downside of this I see, is that it might look a little cluttered on ISO A4 format.
I doubt you care about these formats though, they are needessly small. Also personally, I would never waste my time printing a character sheet when I can just have it up on a laptop. I just set paper type to Super B and use it as my character sheet directly.


**Alternatively, an idea I think is much better,** is you give us the option to rearrange how our character sheets are laid out. This would likely be quite a bit more work on your part, you'd have to build an editor, or at least basic instructions on some config files. We'd be able to customize the character sheet for our specific use case. There is tons of stuff I would change on my character sheets that I can't suggest be made the default.

**Comment by richardwilkes** [comment]
This has been implemented and will be in the next release.
