### ISSUE TITLE
[Suggestion] Port to Android

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs#322]
One thing I'd love to do is be able to use my tablet like a paper character sheet.

I recognize this would be a ton of work. Even though it's java, it's a lot more to make it work right on android or iOS. So, maybe start with just a viewer that can open a .gcs file and let me change the resource pools and move around inventory?

**Comment by richardwilkes** [comment]
This is a non-starter. Steve Jackson Games has expressly forbidden development on mobile platforms.
