### ISSUE TITLE
Notes on spells are NOT exported to foundry VTT

### ISSUE THREAD

**Issue by LordOHelmet** [richardwilkes/gcs#324]
Notes on spells are NOT exported using the @NOTES export key.
Thus the NAN-GURPS module for Foundry VTT is unable to import it.

**Comment by crnormand** [comment]
To be concise, if a Spell appears in GCS as:
![image](https://user-images.githubusercontent.com/8931036/114332923-260df700-9b15-11eb-80e2-79632398c650.png)

When we export the @NOTES key, we only get "Note on Spell":

![image](https://user-images.githubusercontent.com/8931036/114332986-463db600-9b15-11eb-89c8-cb61273bf249.png)

The Ritual and Time text does not get exported.
