### ISSUE TITLE
Add Counters for Output Template Loops

### ISSUE THREAD

**Issue by cyberianfrontier** [richardwilkes/gcs#327]
This request has to do with Output Templates.  It would be very helpful to have template variables for each of the loops that would report the number of items contained in each loop, or simply if a loop has content or not.  In the instance that the loop count variable returns zero, that could be used to hide empty sections via CSS.  Thanks!

**Comment by richardwilkes** [comment]
You can now specify the same key used for the start of the loop, but with the "_START" replaced with "_COUNT" to get the count.
