### ISSUE TITLE
GCS Crashing When Exporting Character

### ISSUE THREAD

**Issue by wesleymg** [richardwilkes/gcs#328]
When attempting to export a character, GCS crashes. This has applied both when outputting to the PC HTML template, NPC Card HTML template and a custom template. My system is an up-to-date version of Manjaro Linux running on a Lenovo Thinkpad T540p with an Intel i5 and 8 GB of RAM. The cores spike in usage, and the program seems to crash when reaching 100% on one core. Background CPU usage was generally <10% with up to two cores spiking to potentially 50% when other programs were running. GCS was not outputting a log to my .local directory as the website says, and setting the GCS_LOG environment variable still does not output to the file listed.

**Comment by wesleymg** [comment]
I should add, those spikes with other programs running were <1 second in length, the spikes from GCS started when I hit export, and continued till the crash.

**Comment by richardwilkes** [comment]
Manjaro linux is not something I've tried before. It shouldn't be special, but I'm unfamiliar with it.

That said, your description (and assuming this is related to an earlier report on the same OS), it sounds like it is crashing when trying to bring up the native file browser. This isn't actually something under GCS's control. When I've seen crashes in this area before, it has been related to modifications on the affected system that altered the standard file dialogs.

**Comment by wesleymg** [comment]
Ran the application in my terminal, here was the error message when it crashed.

`(GCS:201987): GVFS-WARNING **: 16:16:31.517: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(GCS:201987): GVFS-WARNING **: 16:16:31.518: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdaf8d0912c, pid=201987, tid=203102
#
# JRE version: OpenJDK Runtime Environment (16.0+36) (build 16+36-2231)
# Java VM: OpenJDK 64-Bit Server VM (16+36-2231, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007fdaf8d0912c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /opt/gcs/bin/core.201987)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid201987.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)`

**Comment by wesleymg** [comment]
On further research, this seems to be caused by a different package, It's probably fine to close this issue.

**Comment by richardwilkes** [comment]
That confirms that the crash is happening in the native code. That is something that can only be fixed outside of GCS.

**Comment by richardwilkes** [comment]
If you attach the /tmp/hs_err_pid201987.log file, it likely will give some info about which subsystem / system library is crashing.
