### ISSUE TITLE
Feature Request: add newline to "notes" field.

### ISSUE THREAD

**Issue by FourWingedKid** [richardwilkes/gcs#330]
A while ago I mentioned the notes field doesn't wrap properly when exporting to PDF. While we wait for the fix proper, I'd like to request a feature that would provide a temporary fix by allowing the user to add newlines in the notes field of a trait. This would also give the users some control over document flow, allowing pure-text formatting simulating a few features of Rich Text (a request I've seen around) like lists and paragraphs.

Lastly, I've never contributed to a project before, but I would like to volunteer for porting the UI to WPF. If that's something the team of GCS would be interested in, please let me know how I can help.

**Comment by richardwilkes** [comment]
Are you referring to #319 ? If so, I was unable to replicate the issue.

As for porting the UI to WPF... I'm afraid that's not realistic, as I currently rely on Java's Swing platform for the underlying UI.

**Comment by FourWingedKid** [comment]
I updated Java and still have the same issue. Maybe someone with Windows installed as their only OS could try it. I'll update a PDF I just created.

[Ian Sinquefield.pdf](https://github.com/richardwilkes/gcs/files/6406817/Ian.Sinquefield.pdf)

**Comment by richardwilkes** [comment]
[Thanh Gawrys.pdf](https://github.com/richardwilkes/gcs/files/6406979/Thanh.Gawrys.pdf)

This is what I get with the same type of data added. There appears to be something wrong with your system's ability to measure the width of a font's characters. Odd, but I have seen such corruption on OS's before. Unfortunately, I don't believe there is anything my code can do to compensate when it is getting this bad data.

**Comment by FourWingedKid** [comment]
That **is** very weird. The text in yours is in a different place and the font is wider! Look closely. When converting to PNG, the break occurs somewhere else: 
![Ian Sinquefield](https://user-images.githubusercontent.com/25872161/116731525-2c7aea80-a9c0-11eb-9a2c-ba0220da357d.png)

**Comment by richardwilkes** [comment]
Just realized I wasn't using the default font that GCS sets (SansSerif, which is *supposed* to be an alias to the default system font) when running on Windows. When I do, I get similar problems. If I explicitly choose Segoe UI (which should be the default for Windows 10), for example, the problem goes away -- but it oddly does not display well inside GCS itself (muddy). Again, not really anything I can do here... Windows is just behaving very poorly when interacting with Java.

**Comment by richardwilkes** [comment]
So the main issue here was that font substitution was occurring in the PDF output because the built-in PDF export code that GCS has doesn't correctly support font embedding. In the upcoming release, I've removed the PDF export option entirely, as all platforms that GCS runs on support print-to-PDF, either natively or with a free plugin of some sort. This support is superior to what GCS had, as it does properly handle font embedding.
