### ISSUE TITLE
Self Referential custom attribute/pool formula breaks GCS

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#332]
With the new update it's possible to break a sheet by entering a self-referential formula for a pool. (example, id ``qn``, with base ``$qn``) The sheet will unrender, becoming blank and saving will not function properly. I have attached an example of what happens if the sheet is 'saved'. The output is incomplete.
[trn15937330940616759830.txt](https://github.com/richardwilkes/gcs/files/6424081/trn15937330940616759830.txt)

**Comment by richardwilkes** [comment]
Thanks for the report. I put logic in to try and explicitly resolve this in a safe (though inaccurate, as it is impossible to actually resolve) manner... but clearly must have missed a case.

**Comment by richardwilkes** [comment]
Ah.. looks like you reference yourself directly. I likely don't handle that case -- but will. I already have logic to prevent referencing yourself indirectly through another reference.
