### ISSUE TITLE
Weapon Default Type is saved as "" if unchanged

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#333]
When adding a new default to a weapon, if the "type" is not changed from the dropdown menu, it is saved as a `""` instead of `"st"`, as the dropdown would indicate.

**Comment by richardwilkes** [comment]
I'm not seeing this. Perhaps you're looking at the wrong spot?

**Comment by rinickolous** [comment]
Just double-checked, and the issue is indeed there. To reproduce:

1. Add a new weapon default to any weapon. 
2. Without clicking on the new dropdown menu, press "Apply" for the item containing the weapon, and save. 
3. The entry for this new default should now be `{"type": ""}` instead of `{"type": "st"}`.

**Comment by richardwilkes** [comment]
Got it. Thanks for the steps. Fixed in commit 9bd65f553a07bcb615672d1f8e104a026585daed
