### ISSUE TITLE
Add a "Quick re-export" button

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#336]
Once a character has been exported, have it remember the type of export (ie.e Foundry VTT) and the destination directory file (useful if your GCS files are stored elsewhere).   You could squeeze it in to the left of the charactersheet settings button.  Example:

![image](https://user-images.githubusercontent.com/8931036/118343297-258ec480-b4f6-11eb-9af2-7b8401180d6f.png)

Obviously, this benefits Foundry users the most.   I am not certain if this would that helpful for other users.   But for GCS-Foundry users, this would be huge.    Make a change in GCS, and press one button, and assuming you exported your character to the Foundry data directory (as explained in the Special Export location section of the users guide), then go to Foundry, open the character sheet and press one button.

**Comment by richardwilkes** [comment]
I'd rather see you just be able to load .gcs files directly and not have to export at all... ;-)

**Comment by crnormand** [comment]
Wouldn't we all ;-)     But in terms of time... I feel that writing the code to read the .gcs files into our object model will take quite a bit longer...

Our import code is 1000+ lines ... and we are already parsing JSON (we convert the XML into a JSON object with a utility function).  While there is some fluff, it is mostly mapping data from one JSON to another.      And I will have to re-write all of it (and verify that I didn't screw it up).   Which I may do some day... but not anytime soon.

Also, this feature WOULD help FantasyGrounds users... as I am pretty certain they will never read .gcs files directly.  

So thank you for not closing this request... we could just let it sit there and see if some enterprising young developer wants to tackle it ;-)
