### ISSUE TITLE
A few requests to enable Enhanced Move

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#337]
These first two definitely have more general use as well:
1) The ability to have attributes that aren't displayed on the sheet.
2) When an attribute is a decimal instead of an integer, allow leveled advantages that add to attributes to include half-levels.
And the last one is specific and could easily be too complex to be worth implementing:
3) Some way to display attributes the way movement speed often is, as (Basic Move)/(Maximum Move). This would require putting multiple attributes on the same line, so it may just not be possible.

**Comment by richardwilkes** [comment]
What is the purpose of having an attribute you can't see on the sheet?

**Comment by kaldrich001** [comment]
Well, in the case of Enhanced Move, mainly because you need some way to represent the level of the advantage and there's not much benefit to it being visually displayed since you're mainly going to be representing it by an advantage anyway. EM is pretty much always (at least in my experience) going to have some modifiers, so having to display both an attribute and an advantage for it seems redundant.

**Comment by richardwilkes** [comment]
I guess I'm just not following. Can you give a worked example of what you mean? I'm assuming the advantage in question gives a bonus of some sort directly to the new move attribute, so no intermediate is required.

**Comment by kaldrich001** [comment]
I've attached a simple character sheet showing how it might be made just using attributes. The issue is that EM uses exponents, so you definitely need a separate attribute for it, and then another for maximum Move that uses the EM attribute within it.
[em example.zip](https://github.com/richardwilkes/gcs/files/6489627/em.example.zip)

**Comment by richardwilkes** [comment]
Hmm... maybe a function to do a lookup for an advantage with a specific name that returns the number of levels (including an extra 0.5 if the half checkbox is ticked) is warranted? That would allow you to eliminate the "Enhanced Move" attribute entirely, I think.

**Comment by kaldrich001** [comment]
That would certainly help a lot in this case. Not sure if there might be any other use for invisible attributes, but that would be enough here.

**Comment by richardwilkes** [comment]
Added advantage_level() to the set of functions you can use in the expression evaluator. Give it the name of an advantage, and it will return that advantage's level, or -1 if it can't be found or is disabled. This will be part of the v4.31 release.
