### ISSUE TITLE
Provide a way to see how a skill's level has been calculated

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#34]

**Comment by crnormand** [comment]
I can see a way to collect up information in SkillLevel.   What I can't see is how to make that a ToolTip for the main page.   I assume it is being displayed (since Skill is a subclass of ListRow), but I don't know how/where it is being shown on the screen.     Can you give me a hint?

**Comment by richardwilkes** [comment]
Tooltips for the `Outline` views are dependent upon the cell. For example, in `SkillColumn.java`, you can see that the `LEVEL` column returns a `ListTextCell()` for its contents. If you look at `ListTextCell.java`, you'll find that there is a `getToolTipText()` method.

**Comment by crnormand** [comment]
Finally done!   The Pull Requests https://github.com/richardwilkes/gcs/pull/112 (for Skills/Techniques), https://github.com/richardwilkes/gcs/pull/113 (for Spells * Weapon Damage) and https://github.com/richardwilkes/gcs/pull/115 (for Skill/Spell editors), provide a ToolTip when you hover over the Skill Level (SL) or Relative Skill Level (RSL) columns that shows Advantages, etc. that provide bonuses to a Skill/Technique/Spell or Weapon Damage.

Examples:
![image](https://user-images.githubusercontent.com/8931036/61596054-8dab4280-abcc-11e9-927e-fbd3bcede081.png)

![image](https://user-images.githubusercontent.com/8931036/61596060-a9aee400-abcc-11e9-9f6b-c2b7c9bb206c.png)
