### ISSUE TITLE
Adding Independent Notes On Items

### ISSUE THREAD

**Issue by Volksters** [richardwilkes/gcs#345]
![TestsheetGCS](https://user-images.githubusercontent.com/78762498/119240557-a54d0c80-bb50-11eb-8043-083225891f4f.png)

Like the example above, this benefits players who write flavour texts in their items' notes and also uses NAN's Game Aid that relies a lot on modifiers.

**Comment by richardwilkes** [comment]
@crnormand’s latest changes seem to invalidate the need for this. Do you think this is still useful in light of the changes to the GGA for Foundry?

**Comment by Volksters** [comment]
I believe it won't be needed then. This can be closed.
