### ISSUE TITLE
Features on Skill that give a bonus per level should give a bonus equal to Skill level

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#348]
Say I have a pool for Conditional Spells, which should be equal to Levels in Magery, plus Skill Level in Thaumatology.

At current, Adding a feature that gives +1 to the pool per level of Magery works as expected.

Adding a feature to a skill to give an attribute bonus to the pool works as long as the "per level" dropdown is blank.

Selecting the "Per level" option should pass Skill Level as the bonus to the pool.

**Comment by richardwilkes** [comment]
That's an enhancement that could be made. That particular capability was only ever intended for Advantage levels, however, which is why it is doing nothing in this case (well, technically it is doing something: but 0 times anything is still 0).
