### ISSUE TITLE
Improved Visual Indication that Trait/Equipment is being dropped into Container

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#349]
The red indented arrow that shows up when moving a trait into a container is a little subtle. In addition to the arrow, I suggest having the text color of the container change temporarily when it's going to be the destination of a move (similar to how a trait text will turn red if prerequisites aren't met).

**Comment by richardwilkes** [comment]
I tried highlighting the parent row as well. Unfortunately, that is often not even visible, as the parent may not be very close to the destination. Instead, I've fattened up the arrow and the line it draws to (hopefully) make it a bit more obvious.
