### ISSUE TITLE
Allow a modifier to affect skills with a given category tag

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#35]
Some of the advantages apply modifiers to a broad category, e.g. a bonus to all thieving skills, or bonus weapon damage to all melee attacks. For these, it would be easiest to configure if advantages had "Gives a Skill Level Bonus to Skills Whose Category is X" and "Gives a Weapon Damage Bonus" to Weapons Whose Required Skill has Category X".

**Comment by crnormand** [comment]
Pull Requests https://github.com/richardwilkes/gcs/pull/117 (Skills/Techniques), https://github.com/richardwilkes/gcs/pull/118 (Spells) and https://github.com/richardwilkes/gcs/pull/119 (Weapons Bonuses) now allow you to set a criteria for searching on categories.
