### ISSUE TITLE
Custom Attribute Export Keys do not function

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#350]
Expected outcome:
Custom attributes are exported properly.
Actual outcome: Keys are not identified at all.

Template
```xml
      <quintessence type="number">@QN</quintessence>
      <quintessence_points type="number">@QN_POINTS</quintessence_points>
      <quintessencepoints type="number">@QP</quintessencepoints>
      <quintessencepoints_points type="number">@QP_POINTS</quintessencepoints_points>
```
Note I tried both lower case and upper case export keys, the result is the same.
```xml
      <quintessence type="number">Unidentified key: 'QN'</quintessence>
      <quintessence_points type="number">Unidentified key: 'QN_POINTS'</quintessence_points>
      <quintessencepoints type="number">Unidentified key: 'qp'</quintessencepoints>
      <quintessencepoints_points type="number">Unidentified key: 'qp_POINTS'</quintessencepoints_points>
```
The custom attributes in GCS:
![image](https://user-images.githubusercontent.com/1914417/122909660-c34c9d80-d398-11eb-8a8b-1e81c7e1932a.png)

**Comment by richardwilkes** [comment]
I don't believe anything has been added to the text export mechanism to support the new attribute & hit location configurability. The hit location one probably works just because it wasn't something you needed to specify individual keys for. The attribute one, however, will require some additional code. I believe all I got around to was making the old style keys work, to keep existing export templates working.

**Comment by richardwilkes** [comment]
Looking at this finally... and realized that the code is actually there for exporting the new attributes and hit locations. However, they are accessible via the loop mechanism, which is not what you were likely trying.

**Comment by richardwilkes** [comment]
At least for the attributes, I'll make a way to access them via explicit values. However, to avoid potential collisions, I may require an extra prefix to be added, maybe something like `attr.`.

**Comment by richardwilkes** [comment]
(sigh) That won't work due to other processing not wanting to allow a dot in the name. I guess I could just check for the id that was specified after all other keys have been checked for. Then also check for the keys plus various suffixes to get some of the sub-data.

**Comment by richardwilkes** [comment]
OK, about to push a change that looks for the id you've specified for the attribute, which will resolve to its value (or maximum value, for a pool). You can append _NAME to get its name, _FULL_NAME to get its full name, _COMBINED_NAME to get its combined name, _POINTS to get the points spent on it, and _CURRENT to get the current value (for pools only).

**Comment by Legendsmith** [comment]
Thanks Rich.
