### ISSUE TITLE
Make display preferences work for .GCT templates

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#351]
Implement display preferences for .GCT template files:
'Show the college column'
'Show the difficulty column'
'Show advantage modifier cost adjustments'
'Show Equipment Modifier cost & weight adjustments'
'Show spell ritual, cost, & time adjustments'

I attached zip file full of .gct templates to use as test fodder
[Templates.zip](https://github.com/richardwilkes/gcs/files/6759362/Templates.zip)

**Comment by richardwilkes** [comment]
Templates work off of the default sheet settings, as they have no sheet settings of their own.

The two that show the additional columns are already functional, although the released code won't dynamically update when you change the preference -- you'll need to either close and reopen the template, or make a modification that causes the columns to update.

The two for showing modifiers need a code change to enable, which I'm about to commit.

The one for spell rituals won't have any effect, as it requires knowing the actual level of the spell, which can't be known in a template.
