### ISSUE TITLE
Pagination changes at different zoom levels

### ISSUE THREAD

**Issue by daliin** [richardwilkes/gcs#352]
On my Win10 laptop using 4.31.1, I'm seeing different pagination for a character sheet depending on what zoom level I'm at. See the attached screenshots. I usually work at 125% but when I printed the sheet I was surprised to see it coming out on a third page. It seems that only the 100% view is showing the page breaks accurately. 

![Pagination Example - 125 percent](https://user-images.githubusercontent.com/35744059/124400740-6fbc4700-dcea-11eb-8a06-2ab0e59ea665.jpg)
![Pagination Example - 100 percent](https://user-images.githubusercontent.com/35744059/124400741-7054dd80-dcea-11eb-88a7-df9f800aa2ab.jpg)

**Comment by richardwilkes** [comment]
I have some as-yet-unreleased changes that may fix this or at least improve the behavior a bit.

**Comment by richardwilkes** [comment]
I checked again this morning and this appears to be fixed in the unreleased version, at least on the cases I've tried. Once the new release comes out, if you have a case where it is still broken, please re-open this report and attach an example sheet that illustrates the issue.

**Comment by daliin** [comment]
I'm still seeing it on the latest release. Attached is a character where it happens on my Win10 laptop.
[Zorgar (Dragon-Blooded Wizard) 250 point - Griffin.zip](https://github.com/richardwilkes/gcs/files/6793370/Zorgar.Dragon-Blooded.Wizard.250.point.-.Griffin.zip)
