### ISSUE TITLE
Characters with no portrait cannot load a new portrait in 4.23

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#355]
Also, they cannot export, if the export script contains a reference to the portrait.

Attached is a character that cannot export (to HTML or Foundry) and cannot change its portrait.

[Dorian.zip](https://github.com/richardwilkes/gcs/files/6793604/Dorian.zip)

**Comment by richardwilkes** [comment]
Fixed in commit 2c00673d87213d9a00bb42e0d27c815bc8b720c2
