### ISSUE TITLE
Some type of delay or cache issue when it comes to automatic resizing

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#359]
Very minor issue that only seems to come up in one case, but still maybe worth checking out. If you change the font in a way that makes it take up different space (either size or between bold and regular), then the tables don't automatically resize themselves until you do something else to the sheet.

**Comment by richardwilkes** [comment]
Fixed in commit dd96c7c2c96f23a7bda675ff90681fcade4c65ee
