### ISSUE TITLE
Bug / Feature - UI Nuisance - Note text equal priority in column width determination in spells

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#363]
If the notes in the power investiture 6 spells were not there, the wrapping in the time & duration columns would not occur. 

Determine column widths on the bold / name text only or with much higher priority so putting descriptions doesn't cause wrapping even in the majority of the no-notes spells.

Unsure if this should apply when rituals are display since that is displayed as secondary text also.  Minimization of overall unnecessary wrapping is the goal.

![GCS_SpellsColumnWidth](https://user-images.githubusercontent.com/73035795/125648419-38e64aae-ed79-48b9-9abe-d8025ba45b02.png)

**Comment by richardwilkes** [comment]
Seems like a generally good idea. Secondary text (i.e. the text that is smaller in the default theme) is no longer considered when determining how wide a column wants to be, giving the other columns a chance to get their full width that might otherwise be overpowered by long notes.
