### ISSUE TITLE
Add Adobe Acrobat Reader support

### ISSUE THREAD

**Issue by mustafakalash** [richardwilkes/gcs#367]
The command line syntax for Acrobat is similar to other readers:
`Acrobat.exe /A page=[page] [file path]`

**Comment by richardwilkes** [comment]
What is the exact path the .exe file gets installed to by default?

**Comment by mustafakalash** [comment]
C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe

**Comment by richardwilkes** [comment]
I assume https://acrobat.adobe.com is a reasonable link to obtain the software? (Note that I generally want to point at the main page and not some specific download page, as those tend to shift around a lot over time)

**Comment by richardwilkes** [comment]
Added in commit 02f63832
