### ISSUE TITLE
Add PDF Exchange Viewer Support

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#368]
Download page URL:
https://www.tracker-software.com/product/pdf-xchange-viewer

Command Line / EXE Name:
PDFXCview.exe /A "page=10&zoom=200,250,100" mypdffile.pdf 

Default Path (unsure, manual-example for making own installer):
C:\Program Files\Tracker Software\PDF-Viewer\

Direct link to manual in a zip file (has command line for installer and application):
https://www.tracker-software.com/product/pdf-xchange-viewer/download?fileid=447

**Comment by richardwilkes** [comment]
Implemented in 676e2c0b
