### ISSUE TITLE
Ability to Import and Export Features

### ISSUE THREAD

**Issue by Tarrith** [richardwilkes/gcs#371]
Creating different armor "sets" and having to set up the same modifiers with different values would benefit by being able to export and import previously created modifiers.

ie.
![Modifiers](https://user-images.githubusercontent.com/23333805/127322280-cc8d8433-8ff7-4c6d-9d22-b913e6476a78.png)

**Comment by richardwilkes** [comment]
I'm unclear why this is needed. Can't you just duplicate an existing modifier to use as your base?

**Comment by Tarrith** [comment]
Sorry if the DEX14 name mislead you. It should have read "Heavy Armour"
Having said that I figured out that I figured out I could just make the armor set, import it into a sheet adjust the numbers and call it a different armor set :)
However "All" as a catagory to give a DR Bonus of would still be nice, instead of having to add every DR location.
