### ISSUE TITLE
Make CTL-G Page-Reference work for Modifier Page References

### ISSUE THREAD

**Issue by GreatInca** [richardwilkes/gcs#373]
Open details for an advantage, navigate to the list of modifiers. Add ability to CTL-G the page references there.

**Comment by richardwilkes** [comment]
While not exactly what was asked for, this commit gives you the ability to click on a page reference cell in a list to open it. 51a9d154

**Comment by GreatInca** [comment]
I think clickable is even better than the hotkey.
