### ISSUE TITLE
Force all sheets to display using default sheet settings, unless specifically exempted

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#374]
At current, new sheets will respect the default display settings I pick, but old/already extant sheets, or sheets created by someone with different settings, will ignore them. Manually going through every sheet old to specify my preferred display settings, and more importantly, expecting my players to have the same display settings as me is really cumbersome.

In general, I'd like my chosen default display settings to be used when opening all sheets, unless I've exempted a specific sheet from that.

Three settings affect the content of sheets- damage progression, multiplicative modifiers, and the dice+adds rule, and should always be passed along as-is.

**Comment by richardwilkes** [comment]
I don't care for the idea of selective overrides like you're suggesting. They easily confuse the user. The current system isn't great, either, as the user needs to be aware of the concept of "initial" (or "global") settings as well as "sheet" settings.

Having a way to bulk apply the settings to a directory of sheets could be useful.
