### ISSUE TITLE
Spell Container Notes

### ISSUE THREAD

**Issue by Tarrith** [richardwilkes/gcs#376]
GCS V4.34
Something is wrong when entering text into the Notes in the Spell Container
First typing into the box it omits letters (example 1)

![1](https://user-images.githubusercontent.com/23333805/128532652-de64147b-ee56-40cd-bbf9-ff0c959ac5f2.jpg)

When I click on a different part of the dialogue box it show what has been typed but it is backward. I kid you not. 
I type in Notes, it comes out as setoN (example 2)

![2](https://user-images.githubusercontent.com/23333805/128532746-0c2f59b6-3ad5-42db-84c2-3e38db1de9ec.jpg)

Tarrith

**Comment by richardwilkes** [comment]
That is indeed bizarre. It appears as if something is forcing the cursor back to the beginning of the field with every keystroke. The good news is that it happens for me as well, which means figuring out what is going on should be fairly straightforward once I get a spare moment to take a look.
