### ISSUE TITLE
Horizontal Scroll Bar Issue

### ISSUE THREAD

**Issue by RevenantBob** [richardwilkes/gcs#377]
When horizontal scrollbar is present in a list, the last item in the list is covered by the scrollbar.

Example:

![Screenshot](https://user-images.githubusercontent.com/1105676/128581406-4fbc962e-bfd2-4c1c-832b-5723cdd29ee6.png)

**Comment by richardwilkes** [comment]
Not technically a bug, but definitely a usability problem. I'll need to enforce a bit of extra dead space at the end of such displays. I'm already doing that in some other places.
