### ISSUE TITLE
Simple metric conversion rules seem wrong for load (weight)

### ISSUE THREAD

**Issue by khirasoft** [richardwilkes/gcs#379]
In the base rule set on page 9 this conversion rule is given:
> Round down for character feats and combat results. When you do math to determine what a character can do – how much he can lift, how far he can jump, etc. – or to calculate injury or other combat results, round all fractions down. For instance, for an attack that inflicts 3 points of injury with a 50% damage bonus, round down from 4.5 to 4 points.

In this example I have set the weight units to 'kilograms (kg)':
<img width="294" alt="image" src="https://user-images.githubusercontent.com/30346277/129728144-2eb4bc26-3d5e-403f-b464-e8a7e2cc7c5f.png">

According to the rules mentioned above the max. load should be rounded down if the checkbox in GCS settings is set ('Use simple metric conversion rules (B9)'). So in my example the max load for 0 encumbrance should be 7 kg. Instead it is 8 kg:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/30346277/129728866-c51bae74-9241-4251-892e-02fd7c0c9c7e.png">

Best regards,
Arne

**Comment by richardwilkes** [comment]
The rounding rule isn't relevant here, since the "simplified" rule explicitly converts 1 pound -> 0.5 kilogram. i.e. it just halves the value that would normally be calculated for Basic Lift and changes the label from "lb" to "kg". Basic Lift is then multiplied appropriately for each of the encumbrance levels.

**Comment by khirasoft** [comment]
But if you are using the 1 pound to 0.5 kg conversion - why does my first screen shot show those odd numbers?

Additionally I noticed that any equipment I enter is also not converted with that simplified rule. E.g. if I add 'Disguise Kit' the weight shows correctly with 5kg in the equipment repository but in the character sheet it says 4.535 kg:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/30346277/129757784-f7204819-f14c-4e57-8f07-5b38b256e5af.png">

I really think that there is something off here...

**Comment by richardwilkes** [comment]
There are global settings and there are per-sheet settings. The global settings are used for everything that isn't a sheet. They are also used to initialize the sheet settings when they are first created. After that point, they are completely independent. You appear to have your character sheet set differently than your global settings.

**Comment by khirasoft** [comment]
Hm, still, if I create a completely new character with both settings set to kg I get that odd number of 4.5kg (this time in both views) instead of 5kg which would be the 0.5 factor conversion.

Anyways what my real issue here is that my game master gives me the handout from the official Gurps Character Assistant which is not available on my Mac. So I try to get my GCS as much in line with that handout as possible. In that GCA sheet however I get a base load of 7kg and in GCS I get 8kg if I have that 'Use simple metric conversion rules (B9)' switched on. So there is a mismatch between both tools in that regard :(

<img width="587" alt="image" src="https://user-images.githubusercontent.com/30346277/129854544-63e10096-ab63-41ef-b6d2-e8b97365535a.png">

**Comment by richardwilkes** [comment]
Without seeing more of the sheet, I can’t say how GCA arrived at that conclusion. Based on the information you have given me and the actual rules, however, it is wrong.

Page 15 of the Basic Set states that Basic Lift (BL) is calculated by squaring ST and dividing by 5 and the result is the number of pounds. That is then rounded down. Your ST of 9 therefore gives you a BL of 16 (9x9 = 81, 81/5 = 16.2, rounded down = 16). Using the simple GURPS metric conversion rules from page 9 would then have you multiply that value in by 0.5 to convert it from lbs to kg, giving you a final BL of 8.

All that said, there could easily be a disadvantage on your sheet elsewhere that is giving a penalty to BL. Unlikely, but possible.

**Comment by khirasoft** [comment]
OK, then let's leave it like that. I still don't get why the equipments get those odd numbers in kg if you indeed use the simple 0.5 conversion ;)

**Comment by khirasoft** [comment]
btw - I very much appreciate how responsive you are 🥇

**Comment by richardwilkes** [comment]
I'm not clear on how you're getting the odd numbers, either. In the current version of GCS that I pulled up to check with, regardless of how I had the settings, I never got numbers like that. I either saw 10 lbs (the original value in the data) or 5 kg, depending on the global/sheet setting and where the data was at the time.

If you can reproduce the problem and can enumerate the exact steps you took to do so, that might help me track down whatever is causing what you're seeing. If so, please attach the info here and reopen the issue. Thanks.
