### ISSUE TITLE
[Suggestion] Allow empty entries in the @@ information prompts

### ISSUE THREAD

**Issue by Ryantist** [richardwilkes/gcs#380]
I have a robust equipment system for my homebrew fantasy campaign. I have created a system that often requires Material, Quality, DR and other entries that vary from the standard GURPS systems. Each weapon and armor is defined by its material, quality and balance. 

I used "@quality@ @material@ Vest*"; for example as a vest template that was then given a material and/or balance/quality modifiers. So the name field alone required three separate and varying fields of description. However, typing in Common along with the material for each armor piece, instead of leaving the quality field blank (only requiring entries for cheap, fine, legendary, etc quality levels), is rather tedious. It'd be easier to leave the field blank and only make entries for non common items.

Further, each of these materials defines both the chance of an item to break, as well as it's DR. So in the notes I had "DR: @material dr@; [@chance to break value@ to Break]; @Concealable?@;"

This allowed the items relevant DR, chance to break (as a GGA OtF formula) and whether the piece of armor received reaction penalties or not when worn in social situations, to be displayed neatly in GGA as an OtF. Not all pieces needed all modifiers and it was easy to only add the modifiers needed to the item template, filling out the prompted fields as necessary. I used to be able to simply leave fields blank when a prompt wasn't required, but now have to add a dash or some other cluttering data to the item name or notes in order to add the information that is actually required, where before I could leave it blank.

Because of my fantasy materials system, I have hundreds (if not thousands) of variations of equipment based on materials, quality and balance modifiers. Prompts are an easy way to create hundreds of unique items quickly. Now however, I need to fill in a field that should usually be empty, giving all my items a '-' in the quality field, rather than just being blank.

Having prompts is useful for players building their own equipment, but even more useful for GMs trying to create as many of the common items (hundreds)]]

**Comment by richardwilkes** [comment]
Thank you for the detailed explanation of why this is useful. Very helpful.
