### ISSUE TITLE
New Feature Request - Customizing the randomized description ranges

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs#382]
Low priority.

The default ranges for the randomizable name, age, height, weight, hair, eyes and skin, all assume Human, and Birthday assumes Earth's calendar.
Calendar would be a pain, I don't expect that one to actually be satisfiably done.

The rest though, I'd like to be able to set customizable values or number ranges, preferably as something inside an Advantage so it could be included in a race template.

Supporting this, I'd also like Handedness to be randomizable, and get the same customizable range treatment. Maybe Gender and Religion too, but those could difficult to do satisfactorily. They're too integral to who a character is for most players to just hit randomize, but it also doesn't hurt much to support.

**Comment by richardwilkes** [comment]
This has been implemented as part of the new Ancestry support. Note there are no built-in editors for this as of now, but the capability now exists.
