### ISSUE TITLE
Hiding notes

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs#384]
I would like to be able to take say an advantage with a long description, and hide its long description. Specifically just the ones I do this to, not a setting to hide all notes, that'd be useless.
I could just delete the notes, but I don't want to delete them because that means finding its spot in the book, or finding it in my own notes if it's homebrew, but if it's simply hidden, then I could just un-hide it.

I think the best way to do this would be for it to be an option in the right click menu. Just right click an item, click "Hide Notes".

**Comment by richardwilkes** [comment]
You can put such things in the user notes and control them separately from regular notes. At any rate, I do not currently plan to add more ways to display notes.
