### ISSUE TITLE
Feature Request: House Rule - Cross Defaults, and/or House Rule Modding Framework.

### ISSUE THREAD

**Issue by Angular-Angel** [richardwilkes/gcs#407]
So, if I take a character and give them two skills with decent default to each other, and a whole bunch of points in both, I can have one skill lower and the other higher. Say, Gardening and Farming with 20 points each, on a character with IQ 10. I can have those skills at either 16 and 18, or 17 and 15. I think it would make sense if they could be the best of both worlds - and thus, 17 and 18. A house rule for this would be really cool. Now, that's probably a lot of work, I understand, but it would be neat.

If you wanted to go even further, some kind of a modding framework or something, where people could write their own house rules and then drag and drop them onto sheets the same way they do skills and advantages would be even neater. That's definitely a lot of work, though. XD

**Comment by richardwilkes** [comment]
It is unclear what you're asking for. An explicit example might help. The current code follows the GURPS rules for the way defaults work, which is already quite complicated -- much more so than it appears at a first glance through the rule book, as there are a lot of edge cases. I'd be very reluctant to make this even more complicated unless there was a truly outstanding benefit that could be achieved.

**Comment by Angular-Angel** [comment]
Mmm, fair enough. For the cross defaults, I meant it would allow you to treat two high skills with defaults to each other such that you can get the best of both worlds. Like, with IQ 10 and 20 points in each of Farming and Gardening, you can have those two skills at 16 and 18, or at 17 and 15, depending on which way the defaults go. I thought it would be neat if you could get the best of both worlds, and have them at 17 and 18. But, that would be a lot of work, and it does say in the book that you're allowed to just rearrange points between skills to that end, so long as neither skill actually goes down in level - which might be the more practical way to go about doing it.

For the second idea, it'd be cool to have some kind of a modding framework, like Forge or Fabric for Minecraft, such that you can have 'House Rule' libraries, and just drag these rules on characters. That would be an even larger quantity of work though, I will admit. It'd also be neat to be able to have city stats, organization write-ups, realm stats, and campaign sheets in the program? But all of those are more work too. :/

**Comment by richardwilkes** [comment]
So you are asking to have defaults work off of defaults, essentially. This is specifically prohibited in the rules and isn't something I'm willing to add.

The idea of a general rule modding framework is likely unworkable in a generic sense.

The other ideas are all substantial amounts of work each. Feel free to create separate feature requests for each.

**Comment by Angular-Angel** [comment]
> So you are asking to have defaults work off of defaults, essentially. This is specifically prohibited in the rules and isn't something I'm willing to add.

Not off of defaults - rather, I was suggesting being able to have your defaults both ways. So you could have one skill level based on defaulting to the other skill, while the other skill was based off an attribute, and then the others skill level based on defaulting to the first skill which the first skill was based off an attribute. This would require calculating each skill level more than once, but in computational terms that's not that expensive. It would be complicated to program though.

As for a modding framework, yeah probably. Minecraft's modding community is pretty nuts, that level of investment is hard to macth. :/
