### ISSUE TITLE
.webp images

### ISSUE THREAD

**Issue by Fredrik-Siljeblad** [richardwilkes/gcs#409]
Simply being able to use images in .webp format would be nice.

**Comment by richardwilkes** [comment]
This won't happen until I can find a stable implementation for Java. I've not yet found such a thing. If you have a link to one, I'm happy to take a look.

**Comment by Fredrik-Siljeblad** [comment]
Understandable. I'll keep an eye out for such an implementation. Thank you
for the fantastic tool you've built.

**Comment by richardwilkes** [comment]
The GCS v5 code base has supported webp from the start.
