### ISSUE TITLE
Filter equipment by TL

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#41]
From [R. William Morris](mailto:noctifer1011@gmail.com):

It would be extremely useful to have something on the Equipment view, maybe a drop-down next to the Category drop-down, that limits the visible equipment to the 'default' TL of the campaign as defined under Preferences.

**Comment by richardwilkes** [comment]
That would be useful. I haven't implemented this in the past primarily because the TL field is freeform and allows any text to be placed in it, to support some of the oddball notations SJG has used in some of their books (they'd make my life a LOT easier if they considered how easy a rule / description / whatever was to implement in a computer program...).

Looking at the current books, I think I'd have to support the following notations at a minimum:

```
4
0-4
4+
^
-
4^
(and an empty field)
```

It's been a while since I've played GURPS for anything but low tech, so I don't recall what the ^ even means in this context.

**Comment by richardwilkes** [comment]
From [R. William Morris](mailto:noctifer1011@gmail.com):

^ by itself is a designation for super-science beyond TL12 or that just plain violates physics as we understand it. If I understand correctly, something like 4^ would indicate a divergent technology loosely possible at TL4, but never existed (like Steampunk).

That said, I sense plenty of conditional statements in your coding future :-)

**Comment by richardwilkes** [comment]
From Anonymous:

I've been mulling this a bit more and I don't think you really need most of those variations for what we're looking to accomplish with listing equipment.

TL 4, 4+, 3+1 and 4^ are basicly the same thing: TL4. This can be handled with coding to process out as equivalent to TL4 (either during a save or in how the equipment item is treated while sorting... the former, I think, would be easier). TL - and an empty TL field are essentially TL0, meaning they're available at any Campaign TL. TL 0-4, as far as I can tell, is mainly used when describing what is 'Low Tech' in the text body of Low Tech, not as a tech level for an individual piece of equipment.

Accomodating superscience or divergent technology could be as easy as an 'Allow Divergent Tech' checkbox on the Preferences window next to the Tech Level checkbox, then another checkbox on each equipment item for 'Divergent Tech'.

When coding, if someone has the Divergent Tech box checked for an item but no TL, its treated as Superscience. If they have a numerical TL and the box checked, its treated as the numerical TL, but displayed with the carat. If the end-user enters a number and carat in the TL field, you could separate that out while saving the piece of equipment into a numercial entry for TL and a 'yes' for 'Divergent Tech'.

Thoughts?

**Comment by richardwilkes** [comment]
As with most things in programming, anything is possible. I was just pointing out that this isn't necessarily a trivial thing to implement due to the variety of notations used and the need to divine that many of them are functionally equivalent. The examples I listed above already exist in the current data files, so they would need to be supported.

**Comment by richardwilkes** [comment]
Possible values for TL, as found in various books:
- whole number, e.g. "1"
- fractional number, e.g. "6.75"
- split number, e.g. "2/3"
- divergent, e.g. "5+1" -> divergent 6
- superscience, e.g. "^"
- superscience at a specific TL, e.g. "5^"
- range, e.g. "0-5", "-5", "6+"

In addition, the current data files also have a null value and an empty string as possibilities.

**Comment by jinkside** [comment]
The easy-mode version of this would be a dropdown with just numbered TLs in it and filtering the TL for a given entity with a `contains` check. Filtering doesn't need to get you down to a single item it just needs to narrow down the selection. I haven't dug into the UI code as yet - I'm hoping to at some later point! - but I suspect it would be a near duplicate of the _Category_ filter that's already on most such windows.

I feel like the next step would be to allow the user to say specify the comparator: `=`, `>`, `>=`, `<`, `<=`, `!=` or `<>`. Either that or set a "TLs between"

**Comment by richardwilkes** [comment]
The current version of GCS includes the TL column in the list display. If you want a specific TL, you can just sort on that and/or apply some filtering.
