### ISSUE TITLE
Attribute Customization

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#410]
I've been using the attribute modification (Power Ups 9 Alternate Attributes is good!). But I've run into a small problem that seems to be *relatively* easy to fix: Dodge is not part of the attributes/not customizable. it *only* looks for `basic_speed` and then adds 3 to it.
I'd like Dodge to be added to the attributes list that can be modified. Maybe in a "fixed" bar at the top of things that don't change but you can change what they're *based* on.
So dodge would be by default  `basic_speed+3`

**Comment by rinickolous** [comment]
Seconded. To expand on this, I think allowing the option to change what the "fixed" attributes (those used as base values for parts of the character sheet which are not directly user editable) are based on could be useful for some use cases.
Off the top of my head, this would include Lifting/Striking/Throwing ST, Dodge, Move (*not* Basic Move, obviously).

**Comment by richardwilkes** [comment]
Five special attributes can now be defined and, if present, will be used instead of the standard calculations for them:

- dodge
- move
- lifting_st
- striking_st
- throwing_st
