### ISSUE TITLE
GUI Fails to launch after closing GCS

### ISSUE THREAD

**Issue by Zagzig184** [richardwilkes/gcs#413]
After installation, closing GCS prevents the program from successfully launching again. No GUI windows or Taskbar icon on second launch attempt, only a Task Manager entry under "Background Applications" with RAM and CPU usage. The CPU usage never drops to idle levels, it always maxes out one core. To fix, I must uninstall GCS, restart my computer, and install it again. Then I can launch it one time.

Windows 11 
Version 10.0.22000 Build 22000
AMD Ryzen 5800X

**Comment by richardwilkes** [comment]
I am unable to reproduce this, although I don't have Windows 11 to try it on and can only use Windows 10 at the moment. Are you sure you've uninstalled all other versions of GCS? I've found in the past that Windows will behave as you describe if more than one copy of GCS is on the system.

**Comment by Zagzig184** [comment]
I have only had one version installed on this PC but I will check for old
files. The GCS installer only finds one installation.

**Comment by Zagzig184** [comment]
Found and removed an old GCS.exe, and the problem is gone. Thank you!
