### ISSUE TITLE
Innate Attacks not working

### ISSUE THREAD

**Issue by ssveter1** [richardwilkes/gcs#416]
Attacks from advantages both melee and ranged are not working
![image](https://user-images.githubusercontent.com/10831302/149251052-e8bf6890-6a36-4cd4-b72d-5e1e21c3ede3.png)

**Comment by ssveter1** [comment]
Right sorry barked up wrong tree

V/r

Scott D. Sveter
MBA, PMP, ITIL-F, SFC, USA (Ret.)

C: 804-904-2020

***@***.***

**Comment by richardwilkes** [comment]
All good. They are welcome to contact me if they need a change on my side for some reason.
