### ISSUE TITLE
Problem with Notes for Equipment

### ISSUE THREAD

**Issue by ZarmonicM** [richardwilkes/gcs#419]
New or altered notes don't save for equipment items after pressing apply.  It erases the entire note field instead.

**Comment by richardwilkes** [comment]
Geez... yep, looks like it is pulling the data for the new VTTNotes field and stuffing it in there instead, overwriting the original note.... and doing it for everything except the Advantages. Well... guess I get to roll out a dot release...

**Comment by richardwilkes** [comment]
Fixed in commit e79624c03f114d424894354878bd1df7ef243861. Will re-release shortly.
