### ISSUE TITLE
Saving a new character, but cancelling, gives error dialog

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#420]
Create a new character.
Click Save.
File Dialog appears.
Click cancel.
This appears:
![image](https://user-images.githubusercontent.com/8931036/151231553-9861fdc3-7358-4b5c-85a6-352393ef25fd.png)
Nothing bad happens... so not very serious, but I wanted to let you know.

Windows 10, GCS v4.37.1

**Comment by richardwilkes** [comment]
Thanks. Looking at the code, it has been that way a long time. Easy fix... just surprised it took so long for someone to notice (including me).
