### ISSUE TITLE
Feature logic "category does not contain" and "category is not" does not seem to be working

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#421]
I created an Innate Attack advantage that is a melee attack.  I defined the melee attack to use the Brawling skill.
![image](https://user-images.githubusercontent.com/8931036/152693624-a0070cb7-920b-4aa7-a69f-a532c1ab1438.png)

However, Brawling can add damage to any attack that uses Brawling as the skill, which I did not want, so I modified it to only affect attacks that do not have the category 'Magical':
![image](https://user-images.githubusercontent.com/8931036/152693816-cb8d328d-5395-4626-8ea8-3a37b1d35097.png)

But the damage is still being applied.    As a test, I added a shortsword, added "Magical" to its category and then added "Brawling" as one of the defaults to the melee attack skill lists, and yes, the Brawling damage was applied to the shortsword attacks also.

After playing around for a while, it seems that the "is not" and "does not contain" logic isn't working, but the "is" and "contains" logic does.

This is the character: 
[The Witcher-build.zip](https://github.com/richardwilkes/gcs/files/8010794/The.Witcher-build.zip)

**Comment by richardwilkes** [comment]
This code:
```
    protected static boolean matchesCategories(StringCriteria criteria, Set<String> categories) {
        if (categories != null) {
            for (String category : categories) {
                if (criteria.matches(category)) {
                    return true;
                }
            }
        }
        return criteria.matches("");
    }
```
is the problem. It will loop through the list and not find any matches with the NOT variants... but then fall through to the final check that I believe is there to correctly match empty category lists. Anyway, I'm swamped with other things at the moment, so it may be a bit before I get around to figuring out what needs to be done to make this work without breaking other things.

**Comment by crnormand** [comment]
No worries.. I just wanted to give you enough information to know where to look.   I completely understand about being "swamped" ;-)

**Comment by richardwilkes** [comment]
Will be in the upcoming v5 release
