### ISSUE TITLE
Add modifier total to modifier section title bar

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#422]
Since I build a lot of odd advantages (as spells, etc.), it would be really nice if the Modifer section could have a running total of the enabled modifiers in the list:
![image](https://user-images.githubusercontent.com/8931036/153243982-6e19a96e-45d9-4fe6-9f97-fd222a27e8fe.png)
Obviously, very low priority.

**Comment by richardwilkes** [comment]
Was looking at this today... however, the cost modifier isn't always just a percentage, so this isn't actually practical.
