### ISSUE TITLE
Allow user to change column names

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#427]
Again, I haven't looked at the code in a long while, but how hard would it be to allow some of the column names to be user configurable?    
And I am mainly talking about the Spell columns (since most other columns are pretty well defined and used).

In my world where spells are "free" (but the spell slots cost CP), I want to be able to list the spells on the character sheet.   So I just manually entered them.   However, I had to use two columns as other things... the "Class" column indicates the Verbal, Somatic and Material components of a spell:

<html>
<body>

Modifiers | Cost | Notes
-- | -- | --
material | (m) | [-10%]
Material | (M) | [-20%]
Somatic | (S) | [-10%]
somatic | (s) | [-5%]
Verbal | (V) | [-10%]
verbal | (v) | [-5%]

<br class="Apple-interchange-newline">
</body>
</html>

And the "Maintain" column is used to show the Spell Cost (which is used to determine which spell slot it can fit in).   So I would love to be able to re-define those two column names. 

Here you can see the Modular Abilities purchased (and the associated slot sizes they represent, 3, 5, 10) and a "Spell Cost Offset" to remove the cost of the spells, and the spells themselves:
![image](https://user-images.githubusercontent.com/8931036/156694261-e3569582-7331-45a9-819f-1b3cac899fb0.png)

Admittedly, low priority.

**Comment by richardwilkes** [comment]
If the title is used no where else within GCS, you could accomplish this by providing a custom localization file to essentially replace the text at runtime. "Maintain" and "Class" may very well be semi-unique text fragments in GCS, allowing this to be a viable, no code change, solution.

**Comment by crnormand** [comment]
True, but editing the localization file would not be an easy thing for a normal user (not power users, like us), and it would affect every character sheet.    If I had a mix of characters, using different magic systems, this would not work as well.

**Comment by richardwilkes** [comment]
After discussing with Chris, closing this out as not something I'll be adding
