### ISSUE TITLE
Optional "house rule" applies to individual character

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#43]
From [Ian Engleback](mailto:ian@engleback.com):

Can the optional "house rules" apply to individual characters rather than affect every character, the one in particular is to decouple Perception and Will, which is on a "per game" basis.

Thinking perhaps a new type of item called a Rule that you can add to characters like Advantages, Skills, Spells and Equipment. Any calculation currently reliant on a Preference setting would check for the existence of a rule instead.

**Comment by richardwilkes** [comment]
I like the idea of one or more 'rules' attached to a character sheet. Would still need the preferences, though, as I'd want defaults for each new sheet created.

**Comment by RevenantBob** [comment]
Would absolutely love this one, especially since I have games that use "Multiplicative MOdifiers" and "Know Your Own ST" running different games.

**Comment by richardwilkes** [comment]
Preferences that could be per-sheet were separated into preferences to use for newly created sheets and per-sheet options  a few releases ago.
