### ISSUE TITLE
Issues regarding Natural Attacks

### ISSUE THREAD

**Issue by BaHalus** [richardwilkes/gcs#430]
If I put both brawling and karate in the sheet, the natural attack uses the brawling bonus only, even when it would be worse. It should use the best bonus only, right? That would be brawling for bite, but karate for punches and kicks.

Btw, Arm ST is not affecting the damage of the punches. How to make it happen?

How do I edit the natural Attacks so it shows everything in another language?
I want to edit bite, punch and kick to Portuguese and haven't found how.

I would like to use weak arms disadvantage (from extra arms) to create centaurs and couldn't find how.
There is any way to make punch damage and kick damage follow different values of ST?

**Comment by richardwilkes** [comment]
I already answered this on the mailing list, but will copy and paste it here, too:

> In general, the answer is to double-click the items in question and edit them to be the way you’d prefer. Sometimes this is because the data was created well before some capability in GCS existed and no one has bothered to submit an update for the data. Other times it is simply because there is no easy way for the computer to do it with the data it currently has.
> 
> Specifically, to rename the attacks that the Natural Attacks advantage gives, double-click it in the Advantages list on your sheet, click the weapon entry you want to modify, and change it. Keep in mind that changing the name of an ability can have wide-ranging impact, as all of the data has been created assuming the english names are in use. Localizing it can be done manually, but is generally not a good idea as it will cause incorrect calculations in a wide range of areas that may not be easy to determine.
> 

I'm going to close this issue, as issues should usually be specific bug reports or enhancement requests and not just a list of questions. Feel free to make individual issues for things that are missing.
