### ISSUE TITLE
Damage using Dice+Adds saves incorrectly

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#433]
If you use dice+adds and input a base damage that would be recalculated (for example, 2d+5), then after exiting the window, the recalculated damage will be saved as the new base damage (in that example, 3d+1). It shouldn't do that, and it can cause issues with per-die damage bonuses. I tested this with both an advantage and equipment, and it happened in both cases.

**Comment by richardwilkes** [comment]
Fixed in v5
