### ISSUE TITLE
Tab character support

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs#435]
Currently, if you copy-paste a tab character in GCS, while it shows correctly in the editor, it is zero-width on the actual character sheet. It should display, preferably with the width of 4 spaces, so we can have text line up perfectly.

Additionally, GCS doesn't allow you to input tab characters outside of copy-paste, as tab is bound to go to the next piece of interface.
Not really sure how to solve this. Removing the tab bind would annoy people. Maybe disable the tab bind when in text input, and use Esc to get out of the text input? As in, when in a text input, you hit Esc to select the text input without being in it, then tab to another interface. If you're trying to select another text input, press any key to enter the text mode that allows tab input.

**Comment by richardwilkes** [comment]
I'm unlikely to support tab characters, primarily because of the complexity of doing so in a way that everyone can understand. The complications to the UI just don't warrant the needed effort and would likely cause a significant additional support burden.
