### ISSUE TITLE
GCS expects wrong foxit pdf viewer exe name

### ISSUE THREAD

**Issue by warmist** [richardwilkes/gcs#439]
as in https://github.com/richardwilkes/gcs/blob/master/com.trollworks.gcs/src/com/trollworks/gcs/pageref/PDFViewer.java#L99 expects "FoxitPDFReader.exe". AFAIK it's "Foxit Reader.exe"

**Comment by richardwilkes** [comment]
The problem here is that the FoxIt folks keep changing the name of their binary. The new version of GCS I'm working on goes back to an internal PDF viewer, so this problem will go away at that point, as I will be removing external PDF viewer support.

**Comment by richardwilkes** [comment]
Closing, since the upcoming v5 release doesn't use external PDF viewers.
