### ISSUE TITLE
Feature: 'gives a skill level bonus of # to weapons whose name is: ____' applies twice if on the named weapon

### ISSUE THREAD

**Issue by arlodu** [richardwilkes/gcs#451]
Version 4.37.1 windows 10, Java 17.0.1

**Comment by richardwilkes** [comment]
Please attach an example

**Comment by arlodu** [comment]
Sure! Here's a pic of the feature, and result on the skill of the weapon in the melee weapons field. It is 14 without the feature, but jumps to 16, and you can see the bonus applied twice in the modifier pop-up. 
![Feature](https://user-images.githubusercontent.com/42949723/174832911-82feb0b4-25c6-41c5-8355-d831b8fe1b40.PNG)
![Weapons Field](https://user-images.githubusercontent.com/42949723/174833002-e032b1f7-2cbd-48c4-ac9e-c35a608b1be9.PNG)

**Comment by arlodu** [comment]
And that feature is on the item in the inventory, just to be clear, named 'shadow staff'

**Comment by richardwilkes** [comment]
Thanks for the screenshots, but could I get you to attach the actual .gcs file so that I can review its contents and run it through the debugger, if needed?

**Comment by arlodu** [comment]
Sorry, I'm struggling to upload the GCS file to github, here's a google drive link or zip, for whichever is less sketchy to use

https://drive.google.com/file/d/1UcUtcCQ4-0i8gz-nCwKRYvqOVAiaTV4d/view?usp=sharing

[Orc Necromancer.zip](https://github.com/richardwilkes/gcs/files/8958067/Orc.Necromancer.zip)

**Comment by richardwilkes** [comment]
Will be part of the v5 release
