### ISSUE TITLE
Support for more specific bonuses

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#46]
There are cases where a bonus should only be applied to a particular weapon. Right now, bonuses get applied to all weapons of a given type.

**Comment by crnormand** [comment]
Although not perfect, this can be accomplished with https://github.com/richardwilkes/gcs/pull/119.   Add a new category to the weapon (e.g. "Bonded"), and then build the bonus so that it only applies to weapons with that category (e.g. "+1 Damage to all weapons whose category is "Bonded").
