### ISSUE TITLE
v5 Bug: Some features are not visibly applied until sheet update

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#477]
When adding new attribute bonuses, DR bonuses, and cost reduction features, the changes do not seem to be visually applied until the character sheet is updated again. Adding attribute bonuses to attributes which a skill is dependent on (e.g. adding a +1 to IQ when some IQ-based skill is present on the character sheet) results in the skill levels being updated, with the attribute's value being visibly changed on the next update.

**Comment by richardwilkes** [comment]
At first I was unable to replicate the problem. You failed to mention just how you were applying the new bonus. If I edit one, it seems to always apply immediately upon hitting the commit button. However, when I drag & drop (and probably also via the Edit > Copy to Character Sheet menu item, although I didn't try that), the full update doesn't seem to happen. Will try to find some time to look at this today.
