### ISSUE TITLE
v5 Bug: system "light/dark mode" settings are not respected in Linux

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#487]
OS: Linux 5.18.11-arch1-1
DE: Plasma 5.25.3

All other applications that I have tried so far have respected my system's "dark mode" preference, but GCS does not do this (and there is no longer a way to change it to dark mode manually as far as I know).

**Comment by richardwilkes** [comment]
I've not seen a way to actually check nor monitor for that on Linux, at least not without the use of a toolkit like qt, which I will not use. If you know of a way to get this information -- and it works on most Linux distributions -- I'm happy to add such support.

**Comment by rinickolous** [comment]
I'll check later today.
Though would you consider adding a manual light/dark mode switch?

**Comment by richardwilkes** [comment]
Yes, that's reasonable.
