### ISSUE TITLE
Support variable level of detail for hit locations

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#49]
From [Uwe Hentschel](mailto:lordraszul@gmail.com):

GURPS offers various levels of detail for hit locations.

Starting with the currently implemented layout from the Basic Set, then adding new locations in the section about custom armor in Low Tech and again expanding on the list in Martial Arts.

It would be awesome if we could pick which one of these we want.
And with the new option to select your body type, adding these different lists as 'body types' might work quite well (or well enough).

Low Tech (p100) adds various locations as can be seen on the attached image.

Martial Arts (p137) adds
- Ear (-7)
- Jaw (-6)
- Joints (-5 or -7)
    - limb / shoulder, elbow & knee (-5)
    - extremity / wrist & ankle (-7)
- Nose (-7)
- Spine (-8)
- Veins and Arteries (-5 or -8)
    - neck (-8)
    - arm, leg (-5)

Allowing for items that only cover one arm or leg would be nice as well - especially since the locations for that already exist.

**Comment by richardwilkes** [comment]
Do any of these "extra levels" have armor that only apply to them? Or is it more like "Vitals" in that "Torso" is always assumed to include "Vitals"? If the latter, then this is indeed easy enough to add by adding additional Hit Location variants. If not, then there is a much larger issue of also adapting all existing equipment and potentially some advantages to include the extra locations.

**Comment by richardwilkes** [comment]
From [Uwe Hentschel](mailto:lordraszul@gmail.com):

Both and the inverse.

Jaw is a sub location of Face. Thus anything that covers the face covers the jaw.
Nose is a sub location of Face.
Joints are sub locations of the corresponding limb sections which in turn are sub locations of the corresponding limb. Knee -> Upper Leg -> Leg
Spine is a sub location of back which is a sub location of torso.

For example there are helmets that do NOT cover the ears (eg. the typical roman ones) but most that cover the skull do cover the ears ...

So for the most part they are sub locations under another already present location and it is generally assumed that they are covered by anything that covers their parent location - BUT unlike vitals, they can be specifically targeted for armoring them (or excluding them from armor - which in GCS I'd do by adding the parent location with DR +x and the child location with DR -x).

Hope that helps.

**Comment by trooper6** [comment]
I'm planning on running a Gladiator game soon and it would be great if GCS would support being able to have the leg armor only on the left leg or the arm armor only on the right arm. I think all it would require would be being able to specify r. arm or l. arm/r.leg or l. leg. It seems like an easy enhancement?

**Comment by jutis** [comment]
Also looking at Low Tech p.100 there are other partial hit locations.

Location Cost and Weight Hit Location Notes
Head 30% 3-5 [1]
 Skull 20% 3-4
 Face 10% 5
Neck 5% 17-18
Torso 100% 9-11 [2, 3]
 Chest 75% 9-10 [2]
 Abdomen 25% 11 [2, 4]
 Groin 5% –
Arms 50% 8, 12 [5]
 Shoulders 10% – [6]
 Upper Arms 10% – [7]
 Elbows 5% – [8]
 Forearms 25% – [9]
Hands 10% 15
Legs 100% 6-7, 13-14 [10]
 Thighs 45% – [11]
 Knees 5% – [8]
 Shins 50% – [9]
Feet 10% 16

**Comment by richardwilkes** [comment]
Another request that is essentially part of #218
