### ISSUE TITLE
PDF viewer support for Sioyek request

### ISSUE THREAD

**Issue by gregdezeeuw** [richardwilkes/gcs#490]
Hello,

Please consider adding support for using [Sioyek ](https://github.com/ahrm/sioyek) as a PDF viewer.

Thanks.

**Comment by richardwilkes** [comment]
The new version of GCS I'm working on (v5) displays PDFs internally again, so support for external PDF viewers will be removed. Turned out they were more of a support burden than I expected, primarily because of the providers changing naming or directory layout much more frequently than I expected.
