### ISSUE TITLE
Keep Json comments when saving

### ISSUE THREAD

**Issue by Euthoniel** [richardwilkes/gcs#491]
I use many characters, and have a text editor open when running campaigns. I'd like to be able to add a json "_comment" near the top of each .gcs character sheet just to remind me of the character essentials without having to open the characters separately in GCS.

I'm able to add "_comment" fields to .gcs files with my text editor and GCS opens the characters without issue, but if I make any changes and save the file it deletes the "_comment" fields. I'd like GCS to keep the "_comment" fields.

No idea how much time investment this would be, and I'm sure there is not much demand for it, just thought I'd make the request in and hope it is easy to implement.

**Comment by richardwilkes** [comment]
Support for this already exists (and has, for quite some time) in the form of the `third_party` key at the top level of .gcs files. The content of that key can be any arbitrary data. It will be saved as-is and not actually used at all by GCS.
