### ISSUE TITLE
Heavy Sleeping Bags have incorrect prices and weights

### ISSUE THREAD

**Issue by allpossibledogs** [richardwilkes/gcs#493]
The heavy sleeping bags from High-Tech have incorrect prices and weights. They should be as follows:
Heavy Sleeping Bag (TL6): $100, 15 lbs
Heavy Sleeping Bag (TL8): $500, 4 lbs

![](https://i.imgur.com/q4LrmZb.png)

![](https://i.imgur.com/URALrKG.png)

**Comment by richardwilkes** [comment]
Fixed in commit 830ff8ac88a09606dda0b6330f57a50d798968e1
