### ISSUE TITLE
v5 Bug: Incorrect Colour for Some Headers

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#496]
The header text on the tables for modifiers and melee and ranged weapons for the items which use these properties are using the "On Background" colour instead of the "On Header" colour.

**Comment by richardwilkes** [comment]
I'm not seeing this in v5. Is this a report for v4?

**Comment by rinickolous** [comment]
Nope, definitely a v5 thing. Here's the text showing up in the wrong colour:
![image](https://user-images.githubusercontent.com/43256580/183393681-e341928b-7a9b-4f58-b7d8-68c6dc1a6392.png)
and here it is after changing the "On Background" colour:
![image](https://user-images.githubusercontent.com/43256580/183394113-d8f62193-58e3-4b8c-ab5b-daa02da13dad.png)

**Comment by richardwilkes** [comment]
Ah. You didn't mention you were referring to the item editors, not the sheet. Still traveling, but will address it when I return.
