### ISSUE TITLE
v5 Suggestion: open file dialog changes

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#498]
Could you change the Open File dialog so that it shows all compatible file types by default? Currently, it defaults to something beginning with *.a (can't check, not at my PC right now), which is slightly annoying when trying to open *.gcs files (which I think is the most common usage of the dialog).

**Comment by richardwilkes** [comment]
Hmm... it does on my Mac. Are you seeing this on Windows or Linux?

**Comment by rinickolous** [comment]
I may have been unclear in my original post. Just in case I was, what I'm asking for is that instead of "*.adm" being the default filetype the GCS open file dialog looks for, the setting is something like "All compatible files (*.adm, *.gcs, etc.)". I have highlighted what I'm talking about in the below image.
This is what it looks like on Linux:
![image](https://user-images.githubusercontent.com/43256580/184043684-bbac5b61-1197-4f24-a47b-db0a6c68c5a2.png)
Windows opens the default Windows Open File dialog (I can't currently get a screenshot as my VM seems to not have the OpenGL drivers GCS requires to open).
