### ISSUE TITLE
Add desktop icons to Linux version of GCS

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#500]

**Comment by richardwilkes** [comment]
So I've done as much as I can here. Not happy with the results on my linux box, as I can't seem to get the documents to have icons that show up on the desktop.

@rinickolous do you have any insight here?

**Comment by rinickolous** [comment]
I'll see what I can do when I get home

**Comment by rinickolous** [comment]
Just built the new version. Document icons were indeed not showing on the desktop (though they _were_ showing in Dolphin), until I restarted my computer. After that, they seem to show up just fine. Might just be a matter of restarting the DE's process to recognise the new icons? I'm on KDE, so I'm not sure if this behaviour will be the same on GNOME, which PopOS! runs a fork of.

**Comment by richardwilkes** [comment]
Yeah, fighting between versions for which icon is displayed is normal, since linux doesn't attach that information to the actual executable. Nothing I can do about that except have each version have a completely unique ID and extensions, which isn't going to happen.

**Comment by richardwilkes** [comment]
After messing with this for way too much time, I'm just going to call it good enough and move on, much like I've done on the Windows side, which also has issues here thanks to Microsoft's policies.
