### ISSUE TITLE
v5: Consistency issue with Attribute Dividers

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#504]
The colour used for attribute dividers is currently set to the "On Page" colour, which I don't think makes a lot of sense considering the only other (afaik) piece of text which uses this colour is the footer. It should probably be the "On Content" colour instead, to match with attribute names.

**Comment by richardwilkes** [comment]
After trying both the Divider and the OnContent colors, I ended up using the OnContent color.
