### ISSUE TITLE
v5: Traits & Equipment no longer prompt to check modifiers when added to sheet

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#507]
Not sure if this is intentional (either because you're planning on replacing how it works or just no longer want that feature) or an oversight, but just noticed that I am no longer prompted when adding a trait with modifiers.

**Comment by richardwilkes** [comment]
Just forgot about it. I believe I did the replacement text prompt, but I don't recall doing anything for modifier selection.
