### ISSUE TITLE
Add PDF export of character sheet

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#509]

**Comment by lucasrpatten** [comment]
I can do this

**Comment by richardwilkes** [comment]
No need. I’m almost done with it.

**Comment by lucasrpatten** [comment]
> No need. I’m almost done with it.

alright sounds good

**Comment by richardwilkes** [comment]
Implemented in commit 12e622abcd172e0ddd8ddcd5f2ca0dae036293da
