### ISSUE TITLE
v5: Focused Editable Borders using wrong colour (probably)

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#511]
Currently, the borders of editable text inputs use the "Editable Border" colour when focused, meaning that "Focused Editable Border" doesn't seem to actually be used for anything (as far as I can tell).

Edit: Now that I'm looking at it, it actually seems the problem is something else entirely.
Text Input fields for items use:
- Control Edge both when focused and not (the border thickness increases when focused)
Text Input fields for characters use:
- Control Edge when not focused
- Accent when focused
Meanwhile, Editable Border and Focused Editable Border seem to be used for nothing at all.

**Comment by richardwilkes** [comment]
Yes, very possible. I pulled the color sets over from the old GCS, but then had to merge them with my unison toolkit, so some are likely orphaned. I will go through and clean that up at some point.
