### ISSUE TITLE
v5: Technique Difficulty shows as "DX/*" in Skill Library

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#518]
The value displays correctly for Skills, but Techniques seem to default to showing "DX/" as the attribute portion of the difficulty value.

**Comment by richardwilkes** [comment]
Hmm... I don't see this. Can you give me step-by-step details to reproduce?

**Comment by rinickolous** [comment]
This seems to not be a display issue as much as an issue when creating new Techniques. They are automatically assigned difficulty value "dx/a" instead of "a". To reproduce:

1. Create a new Technique.
2. Drag into a skill library (or check file) to verify value.
3. Value will be displayed as "DX/A" instead of expected "A".
