### ISSUE TITLE
Unable to save files in remote filesystems not supporting chmod GCS5

### ISSUE THREAD

**Issue by Calmquist** [richardwilkes/gcs#522]
I attempted to save a file in a remote filesystem that GCS4 supports. The error appears to be that chmod isn't supported and that GCS5 uses chmod when saving files.

[github.com/richardwilkes/gcs/v5/model/jio.SaveToFile] save.go:35
[github.com/richardwilkes/gcs/v5/model/gurps.(*Entity).Save] entity.go:136
[github.com/richardwilkes/gcs/v5/ui/workspace.SaveDockableAs] workspace.go:356
[github.com/richardwilkes/gcs/v5/ui/workspace/sheet.(*Sheet).save] sheet.go:342
[github.com/richardwilkes/gcs/v5/ui/workspace/sheet.NewSheet.func9] sheet.go:204
[github.com/richardwilkes/unison.(*Panel).PerformCmd.func1] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/panel.go:715
[github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.73.0/call.go:25
[github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.73.0/call.go:19
[github.com/richardwilkes/unison.(*Panel).PerformCmd] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/panel.go:715
[github.com/richardwilkes/unison.RouteActionToFocusExecuteFunc] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/action.go:124
[github.com/richardwilkes/unison.(*Action).Execute.func1] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/action.go:103
[github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.73.0/call.go:25
[github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.73.0/call.go:19
[github.com/richardwilkes/unison.(*Action).Execute] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/action.go:103
[github.com/richardwilkes/unison.(*Action).execute] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/action.go:108
[github.com/richardwilkes/unison.(*menuItem).execute.func1] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/menu_item.go:321
[github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.73.0/call.go:25
[github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.73.0/call.go:19
[github.com/richardwilkes/unison.(*menuItem).execute] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/menu_item.go:321
[github.com/richardwilkes/unison.(*menu).preKeyDown] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/menu.go:332
[github.com/richardwilkes/unison.(*menu).preKeyDown] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/menu.go:338
[github.com/richardwilkes/unison.(*Window).keyDown.func1] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/window.go:1154
[github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.73.0/call.go:25
[github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.73.0/call.go:19
[github.com/richardwilkes/unison.(*Window).keyDown] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/window.go:1154
[github.com/richardwilkes/unison.NewWindow.func12] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/window.go:279
[github.com/go-gl/glfw/v3.3/glfw.goKeyCB] github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220806181222-55e207c401ad/input.go:359
[_cgoexp_4e2a132c1af0_goKeyCB] _cgo_gotypes.go:2696
[github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEvents] _cgo_gotypes.go:2569
[github.com/go-gl/glfw/v3.3/glfw.WaitEvents] github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220806181222-55e207c401ad/window.go:982
[github.com/richardwilkes/unison.processEvents] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/app.go:170
[github.com/richardwilkes/unison.Start] github.com/richardwilkes/unison@v0.29.2-0.20220906020553-0c1ca7e4f434/app.go:165
[github.com/richardwilkes/gcs/v5/ui.Start] startup.go:28
[main.main] main.go:65
Caused by: chmod /run/user/<UID>/gvfs/smb-share:server=<server_name>,share=<share_name>/path/to/directory/safe1167692790: operation not supported

**Comment by Calmquist** [comment]
I also get two save dialogs when attempting to to save, but that is probably a separate problem.

**Comment by richardwilkes** [comment]
OK, so I see why this is happening. I'm using a "safe" method of writing a file, where I basically write to a brand new file, ensure everything is complete, then move the old out of the way, move the new into place, then delete the old one. This is done to ensure that a failed write doesn't damage an existing file. To make this work when I want to explicitly set the mode of a file, I have to change the mode after I've created it, since I'm using a call to create a temp file which does not provide a way to set the mode.

This *should* work, but for some reason your file system isn't permitting mode changes... which is extremely odd if I can write the file in the first place with a specific mode.

Anyway, I'll have to give this some thought.

**Comment by richardwilkes** [comment]
I made some changes in my underlying toolbox library to avoid using chmod. Please update to the latest code and see if that improves this issue any.

**Comment by Calmquist** [comment]
That appears to have fixed the problem.
