### ISSUE TITLE
v5: "Provide Subsitutions" window doesn't automatically resize to appropriate size

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#523]
When prompting for substitutions, the pop-up window's initial size is significantly smaller than what would be desired. This might be a platform-specific issue, but I don't currently have the ability to test on other platforms.

Below is what the pop-up window initially looks like for me:
![image](https://user-images.githubusercontent.com/43256580/190852964-a7a8cedd-be20-4f16-b507-ed7ff6d3f5de.png)

**Comment by richardwilkes** [comment]
Please give me a file that demonstrates the problem. When I try this on Linux, it comes up correctly. I'm on PopOS, so that may be the difference... but having the actual file and steps will be useful.

**Comment by rinickolous** [comment]
The behaviour isn't specific to a file. Any item dragged onto a character sheet will pop up with a too small "Provide Substitutions" window as shown above.
Notably, the "Select Modifiers" window seems to not display this behaviour until a "Provide Substitutions" window is displayed. Afterwards, it too will display this behaviour. I am attaching some screenshots for demonstration. These are taken immediately after launching GCS (because the behaviour of these windows is affected by them being opened):

Dragging the "Flight" trait (from Basic Set Advantages) onto the character sheet (Select Modifiers window displays correctly):
![image](https://user-images.githubusercontent.com/43256580/190900437-a22f1e2e-9334-4006-a2df-8745e3c018a1.png)
Then, dragging the "Fanaticism" trait from the same file onto the character sheet (Select Modifiers window has a scrollbar which indicates incorrect default size, though this may be unrelated):
![image](https://user-images.githubusercontent.com/43256580/190900520-c5bd4d51-e84d-408f-820b-215fe7fce9d4.png)
Pressing "Cancel" or "Ok" on the above window brings up this "Provide Subsitutions" window for Fanaticism. This is insufficiently large to be readable:
![image](https://user-images.githubusercontent.com/43256580/190900564-48525cbc-46fe-4e08-bef5-aab962766bbe.png)
After doing all of the above, dragging over the "Flight" trait again results in this. The window's default size appears to be reset, and is now also too small to be usable before resizing:
![image](https://user-images.githubusercontent.com/43256580/190900630-0546de57-8502-41d1-9b7d-b6e478fe9ea9.png)

**Comment by richardwilkes** [comment]
I'm still unable to reproduce this. Which linux distribution are you using? I may have to install that specific one to see the issue.

I'm not seeing anything obvious in the code that would trigger this, either. Although, now that I type that, I realize that I have seen something sort of similar to this on *some* linux distributions long ago... what I was seeing there was that the call to set the window size was often ignored on the first attempt and the only way I could get it to work reliably was to issue the resize, wait for a moment, then issue it again... at which point, if it hadn't taken on the first attempt, the second attempt would cause it to size correctly... however, that's generally not a workable solution.

**Comment by rinickolous** [comment]
I'm running Arch Linux, with KDE as my Desktop Environment, if that's relevant.

**Comment by richardwilkes** [comment]
Installed kubuntu since it defaults to kde... and sure enough, the problem shows up immediately. So, something odd that the window manager in kde is doing. Will poke into it a bit to see if there is a workaround.

**Comment by richardwilkes** [comment]
So, as I suspected, the KDE window manager is sometimes ignoring resize requests. On the times when the dialog doesn't size itself properly, I can see that the window size I asked for is completely ignored. I've seen this with X-windows in general, but it doesn't seem to happen with gnome as often.
