### ISSUE TITLE
[Bug] SM changing ST price with KYOS ST Scaling

### ISSUE THREAD

**Issue by Sirgoii** [richardwilkes/gcs#526]
> "When using the Revised Strength Table, ST still costs 10
points/level. The No Fine Manipulators and Size modifiers on
p. B15 are no longer necessary." From Pyramid#3/83 page 18

SM is not meant to change the price of ST in KYOS scaling, but it seems like SM is changing the price of ST even when KYOS scaling is active. Shown in the examples below (KYOS scaling is active for both).

![Ex1](https://user-images.githubusercontent.com/109975617/191582801-e7ceccc5-6fc6-4900-bfe3-9efdd1792f6b.png)
![Ex2](https://user-images.githubusercontent.com/109975617/191582803-7c819c21-514c-4019-8324-2df3244ddb9b.png)

**Comment by richardwilkes** [comment]
The KYOS option is only for damage progression. It does not alter your basic attribute configuration. To do that, you need to edit the character's attributes (and likely the default attributes for new sheets, so you don't have to do this every time) and remove the SM Reduction from the ST attribute.
