### ISSUE TITLE
v5: newline character in notes displays as null square when loaded

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#530]
When opening a Note, if the Note contains any newlines, the newlines are shown as a null character square (pictured below) when initially loaded
![image](https://user-images.githubusercontent.com/43256580/192100111-f210b434-4374-44a5-84e0-40a400dd48f5.png)

**Comment by richardwilkes** [comment]
Which platform? I'm not seeing this behavior on macOS

**Comment by rinickolous** [comment]
Linux. Running KDE as my DE if relevant. Thought for a second it might've been a font issue, but this happens with the default font too.

**Comment by richardwilkes** [comment]
Fixed in unison
