### ISSUE TITLE
Tag filter dropdown missing from table sheets

### ISSUE THREAD

**Issue by ikiris** [richardwilkes/gcs#534]
Simple search is a vast regression from proper dropdown filtering of the item lists such as spells / advantages / skills, etc. Frankly the commit should have been reverted at this level of UX regression, and would have at $dayjob.

Please at least add back a dropdown to allow filtering against the now jumbled together "Tag" field, if not arbitrary field filtering.

**Comment by ArchSinccubus** [comment]
Please do! It's one of the best ways to filter through the many, many lists GCS has, I would love to see it return

**Comment by Exxar** [comment]
I use this often.

**Comment by vilobion** [comment]
I also miss being able to filter the contents of a library via the tags dropdown.

**Comment by richardwilkes** [comment]
Replaced the search field and the various other controls that went with it with a filter field & tag selector.

When in a filtered state, operations that would potentially alter the list of rows (removal, reordering, additions, etc) are prohibited.
