### ISSUE TITLE
gcs5: KDE file dialog does not remember last directory used

### ISSUE THREAD

**Issue by dripton** [richardwilkes/gcs#536]
In GCS 5 on Kubuntu, the app uses the KDE file dialog, which is good.  But the file dialog always starts at the default location ("Root" of the computer), rather than remembering the last directory used.  So every time I want to load a character, I need to navigate to my ~/gcs directory again.  I imagine most users keep most of their gcs files in one place, and reusing the last location by default would make things faster.  Easy enough to save it in memory for one run of the program.  Saving it across runs would require some kind of prefs file.

**Comment by richardwilkes** [comment]
The code already asks the native dialog to open in a specific place... although maybe not for the Open, but just for save. I'll have to check that. Anyway, if I am asking and it is being ignored, then I likely won't be able to do anything.

**Comment by richardwilkes** [comment]
It turns out I wasn't bothering to set & track it for the open dialogs. I've addressed that. Hopefully the KDE-specific case is resolved as well.
