### ISSUE TITLE
GCS5 Bug: Windows Version is unable to Zoom with Scroll Wheel in the Integrated PDF Viewer

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#544]
As stated above, currently impossible to use Zoom functionality with a mouse in PDF Viewer. Neither Ctrl, Shift or Alt keys have any effect in conjunction with the Scroll Wheel.

**Comment by Nyksia** [comment]
After checking, it is also impossible to horizontally scroll with a key combo. Probably caused by same issue.

**Comment by richardwilkes** [comment]
In the upcoming v5.3 release, alt/option held down while using the mouse wheel will adjust the scale. In addition, an information icon is in each view that supports this to let users know they can do this.
