### ISSUE TITLE
GCS5 Suggestion: Zoom level presets for the Integrated PDF Viewer

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#545]
Ability to set dynamic zoom levels, i.e. Fit to Screen, Fit to Page, Fit to Width and etc.
This allows the user to quickly change the zoom levels without requiring them to constantly put in the zoom percentages manually.

**Comment by richardwilkes** [comment]
While not what you're asking for, there already are key presets available:

Q => 25% (quarter)
H => 50% (half)
T => 75% (three-fourths)
1 => 100% (1x)
2 => 200% (2x)
3 => 300% (3x)
- => decrement the current scale by 10%
= => increment the current scale by 10%

Similar keys are usable in the various image viewers, too, although there are some extras, as 4 through 0 are also accepted, changing scale from 400% through 1000%.

**Comment by richardwilkes** [comment]
In the upcoming v5.3 release, I've added a view menu that has a bunch of preset options in it. Again, not things like "Fit to xxx", but specific scales, much like listed above. This menu is part of the main menu bar and not on the control itself, but gives you the same capability, along with hot keys that can be configured.

**Comment by richardwilkes** [comment]
I don't plan to add the 3 extra options you suggested above.
