### ISSUE TITLE
Allow to change what is being searched in Libraries

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#546]
Currently putting anything into the Search field will search both in Names and Descriptions/Notes. This is not only unintuitive compared to the previous version, but is also making it more annoying to find things by names quickly, as it has no priority for one or another, instead opting for whichever is first.
It would be nice to either have 'Search Modes', or ability to opt-out from searching for anything but the Names.

**Comment by richardwilkes** [comment]
Is this still relevant, given the replacement of the search field with the filter field & tag popup?

**Comment by richardwilkes** [comment]
Added a "Names Only" checkbox to the various search/filter fields to control whether the whole item or just the name is used (commit ef2cd8f6851ec2a8e8c7920340db61d22bd1b45d)
