### ISSUE TITLE
GCS5 Possible Bug: Option to not count Unspent Points towards Point Total having no effect

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#547]
Haven't tested it extensively, but when I was sorting out everything with character sheets after moving to GCS5, toggling the option on and off made no difference on the sheet's point total.
It is worth noting those were sheets created in previous version of GCS, and this was on the Windows version of the app.
Unless the option itself is not functioning properly, it might have something to do with how the sheet info is stored, the older version of sheets possibly missing a variable for it or whatever else.

**Comment by Nyksia** [comment]
Did a bit more of a thorough test, and at least toggling it on and off does nothing, both on an existing sheet and a new one.

**Comment by richardwilkes** [comment]
I just forgot to implement this in the rewrite. I've moved the option into per-sheet settings and hooked it up.
