### ISSUE TITLE
Option to hide Default info for skills & techniques

### ISSUE THREAD

**Issue by Vethano** [richardwilkes/gcs#55]
In order to limit how much space a skill takes up on the sheet, or to hide unwanted information, it'd be helpful to have an option to hide the Default info that's printed beneath some skills and all techniques. Ideally this option could be toggled individually per skill. There's a "Swap Defaults" menu key in preferences, but its purpose is unclear (at least to me).

**Comment by richardwilkes** [comment]
The Swap Defaults command is for just that: swapping a default to an alternate in the case where a skill can default to more than thing and the automatic choice wasn't what you desired. It has nothing to do with showing or not showing the text in question.

**Comment by richardwilkes** [comment]
Hiding the modifier notes or the regular notes is now possible on GCS 4.12
