### ISSUE TITLE
The Built-in PDF viewer crashes 5.0.1

### ISSUE THREAD

**Issue by johnnyschad** [richardwilkes/gcs#553]
I'm running 5.0.1 on a Macbook Pro (Intel). 

Any time I attempt to click a skill or trait I'm prompted to establish a connection between the code letter and a PDF. Once I select the PDF to use (I've tried GURPS Characters, Dungeon Fantasy Adventurers, and Magic) the built-in PDF viewer appears on the right, there is an ominous pause as the viewer says it's referencing the page number for which I asked, then the entire program crashes to the desktop. 

I'm happy to provide any information you want. 

Thank you in advance for any help or insight.

**Comment by richardwilkes** [comment]
I don't see the attachment. Perhaps you can DM it to me on Discord if GitHub is being uncooperative?

**Comment by johnnyschad** [comment]
> On Sep 27, 2022, at 5:36 PM, Richard Wilkes ***@***.***> wrote:
> 
> 
> I don't see the attachment. Perhaps you can DM it to me on Discord if GitHub is being uncooperative
> 
> 

I’ll give that a shot. 

The email client choked on the attachment (14 meg file). 

If it would help, I’d be willing to set up Team Viewer for you to see the problem first-hand.

**Comment by johnnyschad** [comment]
Richard, 

I ran the app as my usual username, but in a terminal so that I could read any Error Output. 

Maybe this will help:

Johnnys-MacBook-Pro-2:MacOS johnnyschad$ ./gcs
panic: runtime error: gobytes: length out of range

goroutine 38 [running]:
github.com/richardwilkes/pdf._Cfunc_GoBytes(...)
	_cgo_gotypes.go:879
github.com/richardwilkes/pdf.(*Document).renderPage.func5(0x42349c7242349c72?, 0x600002614060?)
	***@***.***/pdf.go:270 +0x56
github.com/richardwilkes/pdf.(*Document).renderPage(0x44aaead?, 0x600001718d80?, 0xc000196618?)
	***@***.***/pdf.go:270 +0x11d
github.com/richardwilkes/pdf.(*Document).RenderPage(0xc000146000, 0x0, 0xcb3, 0xc000094360?, {0xc000092e9b, 0x0})
	***@***.***/pdf.go:249 +0x1a9
github.com/richardwilkes/gcs/v5/pdf.(*PDF).render(0xc0000e4200, 0xc0001ae048)
	github.com/richardwilkes/gcs/v5/pdf/pdf.go:163 +0xe5
github.com/richardwilkes/gcs/v5/pdf.(*queueData).worker(0x0?)
	github.com/richardwilkes/gcs/v5/pdf/queue.go:90 +0x45
created by github.com/richardwilkes/gcs/v5/pdf.newQueue
	github.com/richardwilkes/gcs/v5/pdf/queue.go:37 +0xd6

**Comment by richardwilkes** [comment]
Yes, that is helpful. Even more helpful would be the actual .pdf that I can try against myself while in the debugger...

**Comment by johnnyschad** [comment]
Attached is the PDF I’ve (usually) been attempting to open. 

>

**Comment by richardwilkes** [comment]
Still no attachment. If you're doing this via email (which it looks like you might be), attachments aren't being brought through to the issue.

**Comment by johnnyschad** [comment]
> On Sep 27, 2022, at 8:54 PM, Richard Wilkes ***@***.***> wrote:
> 
> 
> Still no attachment. If you're doing this via email (which it looks like you might be), attachments aren't being brought through to the issue
> 
> 

Odd. I thought it was small enough to pass through. I’ll send you the file through Discord.
