### ISSUE TITLE
GCS5 Bug: Text sometimes disappears while screen-sharing on Discord

### ISSUE THREAD

**Issue by darkband** [richardwilkes/gcs#559]
While streaming on Discord to help a friend build a character, we noticed that the text in the new version tends to disappear in some of the library files or editors he opened up. This immediately ended once he ended his stream. Problem was not present in previous version

**Comment by richardwilkes** [comment]
Hmm... not sure how much, if anything, I can do about that. I don't know what Discord does to do screen recording and sounds like a bug in Discord if it is interfering with another program.

**Comment by darkband** [comment]
Small Update, we discovered that the problem only happened while sharing application in Discord, not while sharing screen. Like you said probably more to do with Discord than GCS
