### ISSUE TITLE
Text Wrapping/Popup Width with multiple monitors

### ISSUE THREAD

**Issue by JotunSoldat** [richardwilkes/gcs#563]
![image](https://user-images.githubusercontent.com/114710101/193165729-09f4282e-f618-44d5-ab7c-f4f30ede441a.png)

Per the above image, and your comments below for future reference.

![image](https://user-images.githubusercontent.com/114710101/193165872-1cc81a5c-ccd6-49c7-80e5-03dea1fcc506.png)

**Comment by richardwilkes** [comment]
This one will have to wait for a bit, since it will require enhancing the checkbox widget in my `unison` project to allow its text label to be wrapped before I can do the right thing here.
