### ISSUE TITLE
Cannot create Levelled Traits that are 0-point features

### ISSUE THREAD

**Issue by JotunSoldat** [richardwilkes/gcs#564]
The only way to create a levelled trait is to include a point cost in the "Per Level" section. This prevents the creation of 0-point features such as Born Biter from being levelled.

**Comment by richardwilkes** [comment]
I'm not where I can look at the rules, but if additional levels have no cost, why are there levels at all?

I'll take infinite levels!

**Comment by richardwilkes** [comment]
Reviewing DF3: The Next Level, I see nothing about it being a leveled trait.

**Comment by richardwilkes** [comment]
I don't see a valid reason to allow leveling if there is no cost associated with it, so I'm going close this. Feel free to reopen and plead your case if you really think this is necessary.

**Comment by JotunSoldat** [comment]
Fair enough. The only reason I tagged it was because I saw a build using it at level 2. I'm not that concerned about it tbh.
I think it's zero points because the ability to bite larger creatures balances to having an easier to hit mouth, which sucks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
