### ISSUE TITLE
GCS5 UI Suggestions

### ISSUE THREAD

**Issue by Sorenant** [richardwilkes/gcs#565]
Hello Richard, thanks for the continued support of this excellent tool.
I've tried the new 5.1 version and I'd like to ask you about some possible changes to the UI that, in my opinion, would improve the user experience.

For the first one, I'd like you to see this [picture](https://i.imgur.com/zTvi6bF.jpg). The top screen is how I usually work with the tool, a single windows split between the library explorer, the character sheet, and trait/skill library, with the entire sheet width always visible. However, when I open a trait editor or another tab like class template, the new tab will push the left tab into the sheet, obscuring it. Would it be possible to prevent this behavior, such as always limiting any extra tab width to that of the trait/skill library or the edge of the character sheet?

For the rest, I prepared this [picture](https://i.imgur.com/LFd9DDr.jpg) to better explain my points.
Until version 4.X, whenever I opened a trait editor, the tool would automatically select the trait name so I could immediately change it and then press Enter to confirm/close it. On version 5.1, both behaviors are gone, slowing down the editing flow. Would it be possible to bring those back, in particular Enter key to apply/confirm/close the editor?
My third point is regarding the expansion and collapse of folders, primarily on the library explorer but also on the sheet. Previously, I could double click anywhere on the entry and it would work, but on the new version the behavior is limited to the small circle, requiring a bit of precision that wasn't required before. I believe the previous behavior worked better.
My fourth suggestion is regarding multi-selection of traits. Previously it was possible to select multiple separated traits by holding CTRL key, now it seems the tool will only accept multi-selection with SHIFT key, limiting it to traits continuous in the list. This change made organizing the sheet a little bit more troublesome.

**Comment by richardwilkes** [comment]
Could I get you to break each of these out into their own issue? Having them lumped together runs the risk of me closing it before all are considered.

A quick note about the selection: the alt/option key is used to do discontinuous selections. I thought that was the case before -- especially since the ctrl key is used for other things on Windows and Linux -- but it may be that I've changed that when compared to v4.x.

**Comment by Sorenant** [comment]
Of course, I'll do it right away.

I've tested on version 4.37.1 and at least on my end ALT selection doesn't seem to differ from normal selection, discontinuous selection is done with CTRL.
Now, on version 5.0.1, I can confirm ALT selection did work as discontinuous selection as you said. Thanks!

PS: I'll edit my main post to focus on the discontinuous selection issue and close it.
