### ISSUE TITLE
GCS5 UI Suggestion: Tab width

### ISSUE THREAD

**Issue by Sorenant** [richardwilkes/gcs#566]
Hello, I had previously opened a ticket suggesting some changes to the UI to improve user experience and was asked to break them down into individual entries. Here's the first one:

Using this [picture](https://i.imgur.com/zTvi6bF.jpg) as reference, the top screen is how I usually work with the tool, a single windows split between the library explorer, the character sheet, and trait/skill library, with the entire sheet width always visible. However, when I open a trait editor or another tab like class template, the new tab will push the left tab into the sheet, obscuring it. Would it be possible to prevent this behavior, such as always limiting any extra tab width to that of the trait/skill library or the edge of the character sheet?

**Comment by richardwilkes** [comment]
I'm definitely in favor of finding ways to make the many-tabs-in-a-window experience better. That said, I'm unclear as to how what you're proposing would work and how conflicts with different tabs wanting space would be resolved. If people have suggestions, please state them here as clearly and explicitly as possible.

**Comment by richardwilkes** [comment]
Closing this in favor of #588, which has more comments but is basically the same request.
