### ISSUE TITLE
GCS5 UI Suggestions: Expanding and collapsing folders

### ISSUE THREAD

**Issue by Sorenant** [richardwilkes/gcs#568]
Hello, I had previously opened a ticket suggesting some changes to the UI to improve user experience and was asked to break them down into individual entries. Here's the third one:

Previously, I could double click anywhere on the entry for a folder (library explorer or trait container) and it would expand or collapse it but on the new version the behavior is limited to the small circle (see this [picture](https://i.imgur.com/LFd9DDr.jpg) for reference), requiring a bit of precision that wasn't required before. I believe the previous behavior worked better.

**Comment by richardwilkes** [comment]
Yes, I've been meaning to allow double-click on a folder to open/close it for a long while now, but so far have managed to forget to actually do it. Thanks for filing this to remind me.

**Comment by Sorenant** [comment]
This is just perfect, thanks very much.
