### ISSUE TITLE
feature request: add default skills

### ISSUE THREAD

**Issue by Human** [richardwilkes/gcs#571]
GURPS has a lot of skills that either default to other skills with some penalty, or default to a stat with a larger penalty. My request is to add some form of "add default skills" feature that would let users drag such skills from a list, adding them at 0 points. Then, if a user added 1 point to them in a character sheet, the skill levels would recalculate as if the user bought the skill at 1 point.

The skill database appears to have all the required information, even including stat-based default skill calculations.

**Comment by richardwilkes** [comment]
You can already do this by creating your own library of "default" skills that you want to be added to a sheet, which you then add to each character.

Given the nature of GURPS, it is not practical to just scan through the libraries and add every single skill encountered that can be performed at default -- it would be a truly massive list and would definitely include skills not appropriate for a specific game.
