### ISSUE TITLE
Editing trait automatically moves to first tab

### ISSUE THREAD

**Issue by BitBlitObviMormon** [richardwilkes/gcs#575]
I have multiple character sheets open; when I edit a trait and finish it automatically opens the first character tab instead of the one I'm working on. Having to tab back to my character each time I edit something can be frustrating. This issue is for GCS 5.1.0.

**Comment by BitBlitObviMormon** [comment]
To clarify, this happens whenever editing a trait opens up a new window divider and the divider subsequently closes when I finish editing the trait.

**Comment by richardwilkes** [comment]
Yep. Already reported and fixed for the next release.
