### ISSUE TITLE
Can't use arrow keys for fonts

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#576]
I was told on Discord to mention this here. The dropdown menus for fonts can't be navigated with arrow keys. I've tried selecting it with Tab and even clicking on it to see the options, and in both cases, the arrow keys (and navigating through typing, if that was intended) don't do anything. I'm on Windows, if that matters.

**Comment by richardwilkes** [comment]
Not sure if this is a bug or an enhancement -- i.e. did I break the code that I thought was already there, or did I just forget to add it? Anyway, will take a look.
