### ISSUE TITLE
Pop-ups must be clicked on twice to register button presses

### ISSUE THREAD

**Issue by jcklemme** [richardwilkes/gcs#577]
whenever I get a popup such as what's in the picture I attached I have to click twice on "OK" or "Cancel" in order for it to register.  It might be that the pop-up isn't "in focus" and the first click focuses it and the second actually interacts with the box.  Not a huge deal but mildly obnoxious.
![image](https://user-images.githubusercontent.com/21014259/194369625-1aeb8319-e267-4419-be8e-2e62b2d5d83e.png)

**Comment by richardwilkes** [comment]
This only seems to happen on Windows & Linux. Found that those two platforms were consistently delivering the initial mouse events after a modal dialog was brought to the front to the previous window. I now try to detect that and forward them to the modal dialog instead.
