### ISSUE TITLE
 Search bar for character sheets

### ISSUE THREAD

**Issue by Haaiku** [richardwilkes/gcs#579]
Hello, I would like you to bring back the search bar for the character sheet section, the search bar is a useful feature to manage the characters, including but not limited to:

- Finding duplicated elements (skills, items, abilities, etc.)
- Finding elements hidden in collapsed containers, such as templates
- Finding notes entered via GCS in a character sheet.
- Quickly navigating through relevant elements of a playable character
- Micro-managing characters using the GCS software in the computer, instead of converting the file to other formats and using third party programs (PDF readers, web-browsers, etc.)

GCS is a great program, thanks a lot!

**Comment by CaptainJoy** [comment]
• Quickly finding a skill when you don’t have the luxury of using a large window size for the GCS program.
