### ISSUE TITLE
Suggestion: Character Template Choice - Display Notes

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#585]
It may be useful for the new Template Choice Picker dialog to display the Container's "Notes" text, in case the user ought to be prompted to make choices in a way the program cannot automate.

To illustrate my point, here is the weapon choice for the Barbarian DFRPG profession:
![image](https://user-images.githubusercontent.com/43256580/196358399-5121f2a8-bf4c-4fd4-8c43-2a8a27a50179.png)
You _could_ split up  the "Weapon and Shield" container further, as below, which would result in the "Weapon and Shield" choice always adding "Shield (Shield)" to the character. However, this would result in those skills being nested inside a container, which some users may find undesirable. However, if a note is displayed in the choice dialog, the user may be prompted to make a particular choice - in this case, always choosing "Shield (Shield)".
![image](https://user-images.githubusercontent.com/43256580/196358701-9673bf38-0278-439a-bf5e-151be8b941d4.png)
The above example isn't the _best_ illustration of the point I'm trying to make, since a choice named "Weapon and Shield" is already clear enough for most users to understand that one of their choices must be "Shield (Shield)", but there may be other cases where the choice is less obvious.

**Comment by richardwilkes** [comment]
Actually, that's not the way it works. Choice containers, once resolved, are eliminated from the hierarchy, so with a setup like:

- Pick 1
  - Axe/Mace
  - Broadsword
- Shield

After picking the actual selection (let's say, "Broadsword"), you end up with:

- Broadsword
- Shield

**Comment by richardwilkes** [comment]
Sure... although I would argue that is a bad way to implement the template. There is no need for that intervening node.

**Comment by richardwilkes** [comment]
Also, while I don't currently have any plans to change the data format, there is still the possibility that I do for one reason or another prior to releasing this for general use. Keep that in mind when doing any editing, since it may be wasted time.
