### ISSUE TITLE
Optional College column on character sheet

### ISSUE THREAD

**Issue by otteroe** [richardwilkes/gcs#586]
I'm in a group where we have a homebrew setting with magic based upon the magic-system, but building on top of it has lead to a lot of extra colleges popping up on spells for us. This is partially to be able to have spells of certain colleges being worse for certain mages by fiddling with the defaults as GCS always show the highest default, and a minus to skill on an advantage won't change that unless it covers all the angles.

So our solution is a bit messy, but to display our issue, with a normal spell it looks like this:
![Screenshot from 2022-10-18 14-59-25](https://user-images.githubusercontent.com/726626/196488516-8e71c136-dd22-4fe9-9b0e-a49e225f21f7.png)

Which is nice and neat, but for us it looks like this:
![Screenshot from 2022-10-18 15-00-03](https://user-images.githubusercontent.com/726626/196488599-25004f67-40ad-4957-95ff-73421f386c78.png)

Where the college column simply pushes everything else off the sheet, more specifically the spell name and description.

In the older java-version there was an option to omit the college column from the character sheet, this hasn't been added to the new version yet, or we simply can't find it. And we would very much like that functionality.

**Comment by richardwilkes** [comment]
Rather than having an option to omit that information, I've moved it into the description display like I did for most of the other data for spells when displayed on a sheet or template.

**Comment by richardwilkes** [comment]
(will be in the next release)
