### ISSUE TITLE
Containers applied from template cannot be deleted

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#589]
This happens only to containers one level below the "choice" container. This may not be very clear, so I have an example below.
To recreate:

1. Create a container inside a template. Set this container to be a "choice" container. I set mine to the following value.
![image](https://user-images.githubusercontent.com/43256580/197340789-67a05697-8005-4079-91be-dad272e2855c.png)
2. Create another container as a child to the first one, as shown:
![image](https://user-images.githubusercontent.com/43256580/197340837-e9a2e8ac-e6ff-4343-bcde-b2f809935ab7.png)
3. Apply the Template to a character.
4. The "Nested Container" cannot be deleted (or duplicated) from the character sheet. Any children of the Nested Container *can* be deleted.

**Comment by richardwilkes** [comment]
Thanks for the clear steps. Interestingly enough, if you save, then reload the sheet, you can now delete the nested container. Anyway, will look into it.
