### ISSUE TITLE
Printing character sheets does not work on some printers

### ISSUE THREAD

**Issue by hcp123** [richardwilkes/gcs#593]
Hi,
Printing character sheets does not work in MacOS (have not tested other OS).
This works in 4.37.1, but not in 5.x (tested 5.0.0, 5.0.1, 5.1.0, 5.2.0, 5.3.0).

Error message: "Printing 'charactername' failed Error code 0x0400: Missing required attributes"
<img width="1110" alt="Screenshot 2022-10-24 at 12 15 48" src="https://user-images.githubusercontent.com/28684289/197506057-ca5f6a40-c7dd-4a15-9552-0e0482a9ea8c.png">

Error from the log:
```
ERR | 2022-10-24 | 12:39:17.377 | Error code 0x0400:
                                  Missing required attributes!
                                      [github.com/richardwilkes/unison/printing.checkIPPStatus] github.com/richardwilkes/unison@v0.40.1/printing/printer.go:151
                                      [github.com/richardwilkes/unison/printing.(*Printer).Attributes] github.com/richardwilkes/unison@v0.40.1/printing/printer.go:98
                                      [github.com/richardwilkes/unison/printing.(*JobDialog).printerPopupSelectionHandler] github.com/richardwilkes/unison@v0.40.1/printing/job_dialog.go:223
                                      [github.com/richardwilkes/unison/printing.(*JobDialog).rebuildPrinterPopup] github.com/richardwilkes/unison@v0.40.1/printing/job_dialog.go:210
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.77.1/call.go:25
                                      [github.com/richardwilkes/unison.processNextTask] github.com/richardwilkes/unison@v0.40.1/task.go:51
                                      [github.com/richardwilkes/unison.processEvents] github.com/richardwilkes/unison@v0.40.1/app.go:171
                                      [github.com/richardwilkes/unison.(*Window).RunModal] github.com/richardwilkes/unison@v0.40.1/window.go:446
                                      [github.com/richardwilkes/unison.(*Dialog).RunModal] github.com/richardwilkes/unison@v0.40.1/dialog.go:189
                                      [github.com/richardwilkes/unison/printing.(*JobDialog).RunModal] github.com/richardwilkes/unison@v0.40.1/printing/job_dialog.go:103
                                      [github.com/richardwilkes/gcs/v5/ui/workspace/sheet.(*Sheet).print] sheet.go:451
                                      [github.com/richardwilkes/gcs/v5/ui/workspace/sheet.NewSheet.func24] sheet.go:284
                                      [github.com/richardwilkes/unison.(*Panel).PerformCmd.func1] github.com/richardwilkes/unison@v0.40.1/panel.go:720
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.77.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.77.1/call.go:19
                                      [github.com/richardwilkes/unison.(*Panel).PerformCmd] github.com/richardwilkes/unison@v0.40.1/panel.go:720
                                      [github.com/richardwilkes/unison.RouteActionToFocusExecuteFunc] github.com/richardwilkes/unison@v0.40.1/action.go:124
                                      [github.com/richardwilkes/unison.(*Action).Execute.func1] github.com/richardwilkes/unison@v0.40.1/action.go:103
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.77.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.77.1/call.go:19
                                      [github.com/richardwilkes/unison.(*Action).Execute] github.com/richardwilkes/unison@v0.40.1/action.go:103
                                      [github.com/richardwilkes/unison.(*Action).execute] github.com/richardwilkes/unison@v0.40.1/action.go:108
                                      [github.com/richardwilkes/unison.(*macMenuFactory).NewItem.func1.1] github.com/richardwilkes/unison@v0.40.1/menu_factory_darwin.go:68
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.77.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.77.1/call.go:19
                                      [github.com/richardwilkes/unison.(*macMenuFactory).NewItem.func1] github.com/richardwilkes/unison@v0.40.1/menu_factory_darwin.go:68
                                      [github.com/richardwilkes/unison/internal/ns.menuItemHandleCallback] github.com/richardwilkes/unison@v0.40.1/internal/ns/callbacks_darwin.go:49
                                      [_cgoexp_f6e5dc80cf49_menuItemHandleCallback] _cgo_gotypes.go:1177
                                      [github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEvents] _cgo_gotypes.go:2456
                                      [github.com/go-gl/glfw/v3.3/glfw.WaitEvents] github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:982
                                      [github.com/richardwilkes/unison.processEvents] github.com/richardwilkes/unison@v0.40.1/app.go:170
                                      [github.com/richardwilkes/unison.Start] github.com/richardwilkes/unison@v0.40.1/app.go:165
                                      [github.com/richardwilkes/gcs/v5/ui.Start] startup.go:39
                                      [main.main] github.com/richardwilkes/gcs/v5/main.go:71
ERR | 2022-10-24 | 12:39:19.387 | Error code 0x0400:
                                  Missing required attributes!
                                      [github.com/richardwilkes/unison/printing.checkIPPStatus] github.com/richardwilkes/unison@v0.40.1/printing/printer.go:151
                                      [github.com/richardwilkes/unison/printing.(*Printer).Print] github.com/richardwilkes/unison@v0.40.1/printing/printer.go:137
                                      [github.com/richardwilkes/gcs/v5/ui/workspace/sheet.backgroundPrint] sheet.go:460
````
Print dialog is different compared with 4.37.1.
In 4.37.1 this is the system dialog:
<img width="867" alt="Screenshot 2022-10-24 at 12 31 56" src="https://user-images.githubusercontent.com/28684289/197506685-15db9a86-e3e0-4318-b7e2-dfee580a8939.png">

While in 5.x it seems to be a custom dialog:
<img width="1100" alt="Screenshot 2022-10-24 at 12 15 37" src="https://user-images.githubusercontent.com/28684289/197506733-c15616d3-8258-470f-adb5-3140c571f44d.png">

**Comment by ethomas340** [comment]
Same in Windows 11.  Same error code but I didn't pull the log.

**Comment by richardwilkes** [comment]
In v5, GCS uses IPP (Internet Printing Protocol) to talk to printers. This means the native platform printing mechanism isn't used. This was intentional, since every platform had very different methods of printing, which wasn't practical for me to implement.

The error message indicates that some attribute required by your particular printer is not being filled in. Given the screen shot, it appears that your printer is responding to all of the standard queries for available settings with a "not applicable" response. That would indeed be a problem. Short of me having your particular printer to see how it responds, though, there is little I can do to remedy this.

In the meantime, you should be able to export to PDF and then use a PDF viewer on your system to print the result. Not ideal, but does allow you to print.

**Comment by hcp123** [comment]
Hi,

Can confirm this. Tried to add the printer with the IPP but was unable to communicate with it.
Seems like Canon Pixma printers might not work with ipp, but only with lpd or Canons own system.

**Comment by dripton** [comment]
I get a similar error in Ubuntu 22.04.1.  When I say print, I get a dialog that lists printers and gives me the opportunity to type some print options (good), but then when I click the Print button I get "Printing 'CHARACTER_NAME' failed unexpected http response code: 404"

**Comment by richardwilkes** [comment]
Some further investigation on one user's machine that is exhibiting this behavior seems to indicate that this can also be caused if the printer is setup to require authentication for AirPrint connections. I don't currently support that mode.

**Comment by JonCJones9999** [comment]
GCS 5.3.1 and 5.4.0, Windows 11, Brother HL-L2395DW (connected via USB). Seeing the error 0x0400 but without the missing attribute line.

ERR | 2022-11-27 | 14:00:33.096 | Error code 0x0400
                                      [github.com/richardwilkes/unison/printing.checkIPPStatus] github.com/richardwilkes/unison@v0.42.0/printing/printer.go:151
                                      [github.com/richardwilkes/unison/printing.(*Printer).Print] github.com/richardwilkes/unison@v0.42.0/printing/printer.go:137
                                      [github.com/richardwilkes/gcs/v5/ux.backgroundPrint] github.com/richardwilkes/gcs/v5/ux/sheet.go:476
![gcs-5_4_0-Printing-Error](https://user-images.githubusercontent.com/20045977/204155716-9a4c3b1b-2b23-41aa-b475-33c13088355e.png)

**Comment by Viridianus** [comment]
I might be dumb but would it be too difficult to build a two-step program that exports to PDF and prints that PDF inside GCS as "native printing"?

**Comment by richardwilkes** [comment]
That's essentially what happens now. The issue here is printers that don't support AirPrint or at least don't respond to the standard as expected. I intentionally use this standard since native OS printing varies dramatically between platforms and I'm unwilling to spend the time and effort necessary to build custom printing for each platform.

**Comment by Human** [comment]
Are there standard tests on various OSes that could be performed on a printer to check for AirPrint compatibility?

**Comment by richardwilkes** [comment]
I'm sure there are somewhere, but I don't know of any off the top of my head. GCS uses this protocol: https://www.rfc-editor.org/rfc/rfc8010

**Comment by richardwilkes** [comment]
If it helps, GCS uses https://github.com/OpenPrinting/goipp for the protocol portion.
