### ISSUE TITLE
Technique point cost calculation

### ISSUE THREAD

**Issue by cdanigel** [richardwilkes/gcs#60]
Hi, I've been working on a number of characters that have a lot of techniques and discovered that all techniques are not calculating properly for their difficulty. Hard Techniques add to the RSL as if they are average techniques meaning that it goes up for every point spent, not every 2 points.

**Comment by richardwilkes** [comment]
This is working as it should. Hard techniques do not cost 2 points per level. They do have a 2 point initial cost, however, which may be what you were thinking of. The table on page B230 clearly shows this.
