### ISSUE TITLE
Inconsistency between attribute editor and body type editor

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#601]
The body type editor has the "add sub-table" button *above* the "delete location" button, while the attribute editor has the "add threshold" button *below* the "delete attribute" button. Could this be changed for UI consistency? Preferably so that the "delete" button is on top in both cases (I just think it makes more sense since it's next to the "drag" button, which manipulates the attribute itself, whereas in both cases the "add" button relates not to the object itself but to its child)

**Comment by richardwilkes** [comment]
Yep, makes sense. Turns out two of the three places this was done are in the add then delete order, while the remaining one was in the delete then add order. Now they are all in the delete then add order.
