### ISSUE TITLE
Spell Bonuses don't apply under some circumstances

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#604]
Spell level/point bonus features don't seem to apply when any limiting criteria (except for Spell Name) are combined with Tag criteria for the feature.
Example:
![image](https://user-images.githubusercontent.com/43256580/200657243-c4638ab0-4395-4dca-9b54-eced7ec3153c.png)
The following features will not apply to the above spell:
![image](https://user-images.githubusercontent.com/43256580/200657972-75f6cbe3-a538-4077-91f7-9474323421ad.png)

Worth noting that setting the string-seeking criteria to "is anything" i.e. "spell whose power source is anything", the feature *does* work

**Comment by richardwilkes** [comment]
This isn't the first time that tag matching has screwed up bonuses. I think it is time to revisit the way I resolve bonuses to make them more robust, albeit probably slower to resolve.
