### ISSUE TITLE
Crossbows, Bows and ST?

### ISSUE THREAD

**Issue by ndrwstn** [richardwilkes/gcs#606]
It doesn't look like the ST of Bows and Crossbows is calculated correctly: Looking at Basic Set 270, it says the ST of a Bow is fixed at purchase and sets both range and damage. However, in GCS it's varying with ST.

Since GCS doesn't seem to keep track of what type of ranged weapon something is, an optional "Maximum ST" probably needs to be added to the ranged weapons editor and added to the weapons damage model?

**Comment by richardwilkes** [comment]
This is a matter of setting the data correctly. I thought the bows for the basic set had been setup properly, but haven't looked recently.

You must set the weapon damage explicitly. If you base it on ST, it will be based on the user's ST, so you must set it to a specific, fixed, value instead.

**Comment by richardwilkes** [comment]
I just checked, and every bow & crossbow in the basic set data does indeed have values fixed to a specific ST. So... I can only assume you are looking elsewhere. At any rate, if there are entries somewhere that aren't correct, that's a data issue and should be filed against the gcs_master_library project. I generally leave the data entry & updating to the community.

If I've not understood the issue, feel free to reopen and clarify.
