### ISSUE TITLE
Incorrect Jumping formulas

### ISSUE THREAD

**Issue by Rupert01** [richardwilkes/gcs#609]
The highjump formula should include the enhanced move component (B352 states "Those with the Enhanced Move (Ground) advantage may apply their movement multiplier to Basic Move before inserting it into _these formulas_ when they have a running start."

The broadjump formula should include the Jumping skill component - the entry on B203 does not distinguish between the two types.

EDIT: Should these include adjustment for the Super Jump advantage?

**Comment by richardwilkes** [comment]
I believe I've fixed things for the next release, including adjustments for Super Jump. I've also added the maximum running variants. I don't like the amount of dead space it creates on the sheet, but will live with that for now until I get around to making that top area more flexible in its layout.
