### ISSUE TITLE
Trait/Spell/etc version field

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#611]
I've been doing a lot of user stuff lately. And it turns out, I'm not perfect. I know, hard to believe. User libraries need some sort of version control. If the traits/spells/etc had a version field that would be a step in the right direction. Then I can tell when an old broken spell description is in use and needs the shiny new version.

The only field I can find of any use is Tags. But then what if I want to add an actual tag. That would look ugly. I know 'cause I tried. I can think of all sort of auto incrementing stuff, but a simple free form field, some place, that shows up in the tables, might be best.

Whatever it is, put is everywhere. User made templates, spells, skills, traits, etc.

**Comment by richardwilkes** [comment]
What you're asking for seems solvable with tags, as you mentioned. What's the downside of using them? i.e. you could literally just add a `v1`, `v2`, etc. to things you create. They only show up in the editors and library lists and not in the sheet, so they won't get in the way.

**Comment by outofnamespace** [comment]
You (and by extension me) are correct. Tags will work. It was a appearance thing.

tag: 1.0 some other tag

Shows this "1.0 some other tag" in the table.

Not very attractive. And what if the tag needs to be a number? Delimiters, or even the "v", would help. However, ugly or not, tags don't exist everywhere. Templates, for example. Templates do have notes instead. Which don't show anywhere unless you open the template. Not sure where else tags don't exist.

The fact the tags don't show up in the sheet is a bit of a problem. I would need to open each skill/trait to see the version number. I also agree that they would be in the way in the player's sheet. So, that is also a problem. Maybe non-printing fields?

I understand if you don't want to do it. Nobody likes feature creep/code bloat. Except Microsoft.

I also considered versioning the spell name, "Create Popcorn 1.0", but that gets REALLY ugly.

Bunch of problems no matter what you do.

"The only winning move is not to play. How about a nice game of chess?" - Joshua

**Comment by richardwilkes** [comment]
If you don't view tags as sufficient because they are essentially invisible on the character sheet, have you considered the notes field that is attached to every primary data type? By default, these do show up on the sheet (although that is configurable).

**Comment by outofnamespace** [comment]
I'm fine with the notes or tag field. they will work. this can be closed if you don't think it is worth the effort.

**Comment by outofnamespace** [comment]
Templates don't have a tag or notes field. Only the note block which would carry over to the character sheet as a game related note.

**Comment by outofnamespace** [comment]
For the templates, I am adding a note of "<template name> vX.X.
This works well. When the template is applied, the note gets added to the note block and is clearly seen but is out of the way at the same time.

I'm still working on figuring out the right approach to containers, traits, etc
