### ISSUE TITLE
UI Body Type inconsistancies

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#614]
The Settings menu lists "Body EntityType" and "Default Body EntityType". Everywhere else refers to just "Body Type".

Also, on the Body Type settings panel, the add/plus icon is not on the tool bar like other similar panels. It is below the tool bar next to the Name field.

**Comment by richardwilkes** [comment]
The EntityType bit was due to an earlier refactoring where the IDE got a little over-zealous. Thanks for catching it.

As for the button... that's intentionally not on the toolbar, as there can be many of them that control adding content to different areas within that panel.
