### ISSUE TITLE
Skill specializations not reliably displayed 

### ISSUE THREAD

**Issue by MichaelMalus** [richardwilkes/gcs#63]
Skill specializations aren't always displayed if the "Skills" column isn't wide enough - it sometimes skips them instead of displaying them on another line. This seems to happen mostly with some combination of a multi-word skill name ("Beam Weapons", "Electronics Operation") and being in a Skill Container. A wider-than-average Ref column also influenced it.

![image](https://user-images.githubusercontent.com/2191582/36600967-c329bf6e-18ab-11e8-9695-32b44e25fb5f.png)

In this case, Beam Weapons/TL10^ should be Beam Weapons/TL10^ (Pistol), and is displayed normally if I delete Dual-Weapon Attack or shorten its page reference entry.

**Comment by richardwilkes** [comment]
Is this still an issue with the latest release, @MichaelMalus ? If so, could I get you to attach an example sheet that illustrates the problem so that I can debug it?

**Comment by richardwilkes** [comment]
Since I've gotten no response, I'm going to assume this is no longer an issue. If you eventually come back and have a reproducible sheet, please re-open this issue and attach it.
