### ISSUE TITLE
alt+right and alt+left are misbehaving

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#640]
They do not behave the same. alt+right jumps to the end of each word. alt+left jump word boundaries. In both cases,  punctuation is treated as a separate word whether it is attached or detached from letter characters.

For windows, ctrl+arrow jumps to beginning of word regardless of direction, treating attached punctuation as part of the word and detached punctuation as a separate word.

Not sure who is right, but I think consistency is needed, whatever cross-platform behavior is correct.

**Comment by richardwilkes** [comment]
Alt-Left should jump to the beginning of each word, where word is typically runs of alphanumeric characters. Similarly, alt-right should jump to the end of each word.
