### ISSUE TITLE
Feature Request: info for Reaction and Condition ±

### ISSUE THREAD

**Issue by CaptainJoy** [richardwilkes/gcs#643]
It would be nice if hovering over a Reaction's or Condition's ± opened a pop-up that listed all the Advantages/Disadvantages/What-Have-You's that provide the bonus/penalty — same as it already does for RSL.

Or

(Maybe) better, since I believe each Reaction or Condition line-item is due to a single Advantages/Disadvantages/What-Have-You, add a column that the displays the relevant Advantages/Disadvantages/What-Have-You.

**Comment by richardwilkes** [comment]
These are not just 1:1 matches with traits. Whenever more than one thing provides the same text, the bonus is combined. Due to this, along with the fact that trait names can actually be quite lengthy, it isn’t reasonable to put that info into a column in that display. A tooltip will have to do.

**Comment by CaptainJoy** [comment]
Tootips would be great.

Also, one can just include the info in the ability’s Reaction/Condition.  E.g. Instead of just “to all influence rolls”, you could say “to all influence rolls due to Charisma”.

I’m not sure which is better.  Adding a tooltip ensures that every ± will have it’s source abilities identified.  Adding the info to each ability makes it visible at a glance, but requires making changes to the each ability in the Library.
