### ISSUE TITLE
Add an option to override language environment variable 

### ISSUE THREAD

**Issue by nowizh** [richardwilkes/gcs#646]
I found that setting LC_ALL or LANG to have appropriate value in Windows may be somewhat challenging for me and my friends.
It would be nice to have an option to override it inside the preference menu or by adding arguments at startup.

**Comment by richardwilkes** [comment]
Those environment variables aren't used on Windows. Only for unix-based OS's, such as macOS and Linux.

On Windows, GCS makes a system API call to determine the current user's default locale. You should be setting your system to use whatever language is preferred, then when GCS launches, it should try to use that, assuming the necessary translation files are in the right spot.

I'll update the translation repo's readme to note the difference for Windows.

**Comment by nowizh** [comment]
Thanks!
However, we are still not getting it working.
We just tried to change system locale to Korean (actually, we tried using Korean Windows environment frome one of us), but GCS seems not using `ko.i18n` file in the right location (for Windows, it was `.\gcs_i18n\`).
Is there a way to know which file path GCS is actually trying to read for localization? Perhaps setting logging to be more verbose is possible?

**Comment by richardwilkes** [comment]
If you open the General Settings, the translations directory path is listed.

**Comment by richardwilkes** [comment]
This will be in the next release, whenever that is.

**Comment by nowizh** [comment]
Directory path to translation files can be found in General Settings or with `./gcs --help`. But it is not clear which translation file GCS tried to load. Logging verbosity option might help :) Thanks!

**Comment by richardwilkes** [comment]
The recent release (v5.6) should help with this.

**Comment by nowizh** [comment]
That worked perfectly! Thanks!

FYI:
I found out that the problem was that Korean Windows tries to read `ko-kr.i18n` instead of `ko.i18n` as in Linux or Mac.
