### ISSUE TITLE
PDF Export - GCS crashes when overwriting a PDF opened and locked by an external PDF reader

### ISSUE THREAD

**Issue by YeshuaAgapao** [richardwilkes/gcs#649]
1. Export PDF
2. Open PDF with an external reader that locks the file out for writes when opening (PDF Xchange Editor does this)
3. Export the PDF again, overwrite the previously exported PDF while opened with external reader
4. Answer yes on the overwrite prompt
5. GCS just closes (silent CTD)

**Comment by richardwilkes** [comment]
This should already be fixed in the current code base. Made a change for it this morning. I still need to test it on Windows, however, since I don't currently have my Windows box handy for doing so.

**Comment by YeshuaAgapao** [comment]
cool, thanks for quick fix

**Comment by richardwilkes** [comment]
For reference, commit 791809302cc1c3fc8c177aa063906cbd1ce2af2f contains the fix referenced above. I still haven't had a chance to test it on Windows, though.

**Comment by richardwilkes** [comment]
Just verified the fix on Windows. Will be in the next release, whenever that is.
