### ISSUE TITLE
xattr command does not work

### ISSUE THREAD

**Issue by feelinclueless** [richardwilkes/gcs#65]
I've tried to install gcs 4.1 on my mac and run into the libraries problem mentioned on the home page.  I've tried the solution Richard describes.  However after entering the command I get the message: 

xattr: /Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac: No such xattr: com.apple.quarantine

and of course the Library files still don't show up.  

Have any other Mac users run into this problem?  How did you get through it?

**Comment by richardwilkes** [comment]
You didn’t give the command line you actually entered, but it appears like you specified the directory and not the app. Given what I see below, I would have expected you to enter a command like this:

```xattr -d com.apple.quarantine "/Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS Character Sheet.app”```

(all on one line)

Is that what you did?

**Comment by feelinclueless** [comment]
body{font-family: Geneva,Arial,Helvetica,sans-serif;font-size:9pt;background-color: #ffffff;color: black;}Mr. Wilkes.   Thank you for responding to my message.  I'm not certain if I tried the precise line you indicated.  I tried parsing the command a bunch of different ways before I wrote you.  With your response I copied and pasted the suggested command into Terminal (twice) and got the following:  Last login: Mon Apr  9 09:17:43 on console
You have mail.
Macintosh:~ edwardelder$ xattr -d com.apple.quarantine "/Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS Character Sheet.app”Note: after hitting return I got the ">" line.  I started GCS 4.1 to test and still had no libraries, so I tried pasting your line again and got:  
> xattr -d com.apple.quarantine "/Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS Character Sheet.app”
xattr: No such file: /Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS Character Sheet.app”
xattr -d com.apple.quarantine /Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS
xattr: No such file: Character
xattr: No such file: Sheet.app”
Macintosh:~ edwardelder$ The file path is drawn directly from the command-I info window, so I don't think that's the problem.  The second response makes me think the problem may lie in the file name itself.  Any ideas?  Ed-----Original Message-----

**Comment by richardwilkes** [comment]
So the path name you specify should be surrounded by quotes so that the command line will treat it as a single argument. What I'm seeing in your output above is that quotes weren't used (hence output about things like Sheet.app not being found, as there is a space in the path name at that point. The example command line I gave is a single line -- if you have more than one being pasted, then you need to fix that and ensure exactly one line is being pasted into terminal to execute.

**Comment by feelinclueless** [comment]
Hello.  Sorry to have to bug you again.  I tried what you instructed.  I copied and pasted the command line you provided 
xattr -d com.apple.quarantine "/Users/edwardelder/Desktop/Gaming/GURPS/gcs-4.10.0-mac/GURPS Character Sheet.app”


all one  line into Terminal.  The response it gave me was just a carrot “>”.  No error messages that time.  

When I call up GCS it still can’t find the library files.  Could it be my antivirus software?  Maybe a control character somewhere in the file path I can’t normally see?  

This seems very weird to me.  I’m seriously considering making an appointment with the local Apple Genius Bar to see if they can figure it out.

**Comment by richardwilkes** [comment]
Is there a Library folder inside the same folder that the GURPS Character Sheet app is in?

**Comment by richardwilkes** [comment]
If you are still unable to get this to work and know how to enable screen sharing, I'm happy to use that to help you get this running.

**Comment by feelinclueless** [comment]
body{font-family: Geneva,Arial,Helvetica,sans-serif;font-size:9pt;background-color: #ffffff;color: black;}Yes it is.  Should I move it?  Where would you recommend?  -----Original Message-----
