### ISSUE TITLE
Add sheet setting to enable/disable markdown in the notes

### ISSUE THREAD

**Issue by YeshuaAgapao** [richardwilkes/gcs#650]
Enable by default for new sheets and sheets loaded from GCS 5.5+

Disable by default for sheets loaded from older versions of GCS prior to GCS 5.5. 
Maily because single line breaks in the notes from sheets prior to GCS 5.5  will not render because they lack the double space at the end of the line.

The markdown is great btw.

**Comment by richardwilkes** [comment]
The GCS data files don't have fine-grained versioning information in them, so there is no way to reliably determine that a given data file was created with GCS v5.5 or newer.

I'm afraid this is just one of those things that folks will have to manually go in and fix up.
