### ISSUE TITLE
Show on Disk opens Command Prompt with title of path on disk

### ISSUE THREAD

**Issue by Swampyjim** [richardwilkes/gcs#656]
![image](https://user-images.githubusercontent.com/123213504/213818139-001828a0-2aa4-44a8-b8ae-203e5373f134.png)

When using the Show on Disk function in GCS a command prompt opens with it's title as the path on disk instead of opening with explorer.

**Comment by Legendsmith** [comment]
I am also experiencing this.

**Comment by richardwilkes** [comment]
This was fixed in commit 794c7fd0d1419d4473c3409aacd27f47494afc98
