### ISSUE TITLE
Allow specifying particular TL for a skill in a template

### ISSUE THREAD

**Issue by smithkm** [richardwilkes/gcs#658]
Some templates or styles specify particular TLs for their skills independent of the base TL of the character.  *La Verdadera Destreza* and *Armatura* from *Martial Arts* both specify certain skills need to be TL2.

**Comment by richardwilkes** [comment]
I'm not understanding what you are asking for that GCS doesn't already support. Please provide an example.

**Comment by richardwilkes** [comment]
Ah, nevermind. You're asking for the ability to specify the TL as a parameter in the prerequisite.

**Comment by smithkm** [comment]
No, although a TL specific prerequisite would also be useful.  If a TL specific skill is in a character sheet, it has a particular TL, if it is in a library or template, it can be marked as requiring a TL, but not given a particular value for the TL until it's applied to a character.   There are some situations where a template specifies a particular TL for a skill included in it that may differ from the automatic one from the character when the template is applied.

**Comment by richardwilkes** [comment]
With this change, if no TL is specified, but the checkbox to require a TL is checked, the behavior is as before (i.e. when added to a character sheet, the character's TL will be used). If, however, you do provide a TL, that TL will be used instead, regardless of the character's TL.
