### ISSUE TITLE
Allow users to define ammunition types (AP, APHC, APSD, etc) and have them affect firearm damage when selected

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#66]

**Comment by damokles66** [comment]
Hello, you can already do that (kind of) by defining several attacks for the ranged weapon in question.
Edit the added weapon, select the tab ranged weapon and add a new attack/usage with the +button.

**Comment by vilobion** [comment]
Why enter it manually when you could configure an adjustment and have the program do the math on the fly?
