### ISSUE TITLE
Modifier features based on parent trait level

### ISSUE THREAD

**Issue by smithkm** [richardwilkes/gcs#660]
Modifiers can currently grant a feature based on their own level, but there are cases like Reputation, Talent, or Delusion where it would be useful to grant a feature, particularly a Reaction Modifier or Conditional Modifier based on the level of the underlying trait.

For instance, Reputation could make the reputation modifier it grants more specific based on which of the "affected people" modifiers is applied and Talents could move the reaction bonus onto a modifier that could be disabled if an Alternate Benefit is being used.

**Comment by richardwilkes** [comment]
Except the level has nothing to do with who/what is affected, only the amount of the bonus/penalty.

**Comment by smithkm** [comment]
What I'm suggesting a way for the level of the trait to affect the amount of the bonus and the trait modifier to control the existence or the text of the bonus.  If you have "Bad Reputation (Everyone but Martians; Occasionally) 2"   then in the reaction modifier needs both the level of the Disadvantage (2), and text dependant on the who is affected modifier ("Everyone but Martians")

If the reaction modifier feature is defined on the trait, then it can set the size of the reaction modifier, but the text is fixed regardless of what trait modifiers are active. This could be parameterized, but that doesn't work well with the `Almost Everyone` or 
`Almost everyone except @large class of people@` trait modifiers.

If the reaction bonus feature is on the trait modifier, it can set the text of the reaction modifier but not the size of it. .

On Talents, whether or not there is a reaction modifier depends on whether the reaction modifier or alternate benefit modifier is taken.  

An alternative would be some sort of template where  the the text of something on the trait could substitute in values pulled from its modifiers.  That would allow both the "People Affected" and "Frequency of recognition" to contribute to the message.

> -2 Everyone but Martians, Recognized on 7 or less.

That would be nicer for Reputation, but wouldn't work for Talent, and seems like it would be more work.

All of this can be handled by editing the trait after the fact but this change would make it automatic.  Apply the trait, select modifiers, fill in the prompts and the trait is set up to provide a meaningful value in the reaction bonus table if appropriate as opposed to now where the results might be wrong or vague and need adjusting.
