### ISSUE TITLE
Please make the multiple tag selection optional

### ISSUE THREAD

**Issue by darkband** [richardwilkes/gcs#664]
I find it cumbersome to have to unselect a tag in order to switch to another tag rather than both tags. Please make to the multiselect for tags optional so that it is possible to use the old way for tag selection

**Comment by richardwilkes** [comment]
I've altered the code to require the shift or command/control key to be pressed when selecting items from the tag filter if you want to use multi-select. This way, the old behavior remains and is easy to use, while those that need/want the multi-select behavior can also easily add it when they actually need it.

**Comment by richardwilkes** [comment]
Changed in 0710821aaa5d5ca3d04d26b53fde61534e6d4522
