### ISSUE TITLE
FoundryVTT Error with GCS 5 Imported Files

### ISSUE THREAD

**Issue by GambitDeclined** [richardwilkes/gcs#666]
Reproducible error with FoundryVTT 10.291 and GURPS 4e Game Aid (Unofficial) 0.15.27 import from GCS 5. Some weapons return a “No melee or ranged named error such as “No melee or ranged attached named ‘Laser Pistol’ found on Jeff Green” when attempting to assign damage to target.

This error is not seen in GCS 4 files.
[Reproducible error with FoundryVTT 10.pdf](https://github.com/richardwilkes/gcs/files/10614116/Reproducible.error.with.FoundryVTT.10.pdf)

**Comment by richardwilkes** [comment]
This should be posted on / moved to the GGA repo. Unfortunately, I don't have the link for that offhand, but I'm sure you can get it from the Discord channel.

**Comment by GambitDeclined** [comment]
Rich, I'm not a programmer, but is this a naming thing in GCS or an import thing in GGA? The GCS 4 files are working correctly.

**Comment by richardwilkes** [comment]
Most likely an issue in GGA not understanding the current v5 format. It has likely already been addressed in the GGA v1 effort, but that hasn't been released yet.

**Comment by richardwilkes** [comment]
This is the repo where you should post it to get some attention: https://github.com/crnormand/gurps

I'd move it, but apparently it can't be moved to a repo that I don't own from this one.

**Comment by GambitDeclined** [comment]
Thanks. I'll recreate on that side.
