### ISSUE TITLE
Entering long text broken

### ISSUE THREAD

**Issue by mfilz** [richardwilkes/gcs#669]
When entering text longer than the text entry field can show, or loading a file with longer text than can fit, only the beginning of the entry will be shown, even when editing. This means the cursor will actually disappear and there is no way of accessing text beyond the beginning short of copying the whole field and pasting it somewhere else. Normal expected behaviour would be to scroll the text in the field, so that the cursor position will be visible. (As in virtually any text entry widget existing.)

I think the old GCS versions actually scaled the font down to fit the text, which was quite a nice feature. I realise that's probably not possible as the normal view no longer is a print preview, but it would be a nice feature for the PDF export, if at all possible. Alternatively multi-line might be a solution.

This happened for me in when entering a character's title, but seems to affect all text entry fields. Not critical, but quite annoying.

**Comment by richardwilkes** [comment]
Hmm... the fields are supposed to scroll themselves horizontally in that case -- and they used to. I must have broken something while fixing other things. (sigh)
