### ISSUE TITLE
Feature Request: Allow command line arguments to set path to logs, settings and libraries

### ISSUE THREAD

**Issue by woefulhc** [richardwilkes/gcs#673]
Please allow command line arguments to set paths for the settings file, libraries. This is already possible for log files. This feature will make it possible for a user to have GCS run consistently from a USB drive without needing to reconfigure it for each machine or needing to download the library for each new computer.

**Comment by richardwilkes** [comment]
I've added a `-s` or `--settings` option to the command line for setting the path to load/save settings.

Logs already have a `-l` or `--log-file` option.

Library locations are controlled within the settings file, so don't need a separate option.

I am also considering adding code to look for a file sitting next to the binary that contains a settings path to allow for those that have a hard time with command lines a way to use this as well...

**Comment by woefulhc** [comment]
The group of players I discussed this with would love that. However, we also discussed that making .sh (linux/mac) or .bat (windows) launcher files would ease the portability thing and also appropriately address windows being the oddball with file paths. I am good either way.

**Comment by richardwilkes** [comment]
Went with this:

In addition, if a file named "gcs_prefs.json" exists in the same directory as GCS, it will be used as the default settings file location rather than the normal location. The new command line option will still override this behavior, however.
