### ISSUE TITLE
Markup Links in Notes Don't Properly Wrap

### ISSUE THREAD

**Issue by ryder-james** [richardwilkes/gcs#675]
![image](https://user-images.githubusercontent.com/5988209/221474162-fc1605f2-547c-4531-b9e9-3ffe60c8bab8.png)
When adding Links to a markup note, the contents of the link don't wrap when they overflow the space for the note. Example shown here cuts off the link text at the Page Reference column line.

**Comment by richardwilkes** [comment]
After reviewing the changes that would be necessary to fix this, I've decided it isn't worth the effort. The links, by their nature, are effectively buttons, which is at odds with permitting them to wrap. I could probably make it work with enough effort, but I just don't believe this is worth spending any time on. I'm happy to review a PR (to my https://github.com/richardwilkes/unison project, as that's where I implemented the markdown renderer) to address this, but have no plans to do so myself.
