### ISSUE TITLE
Export to HTML, both @PORTRAIT and @PORTRAIT_EMBEDDED show no image in the HTML document.

### ISSUE THREAD

**Issue by mehalforc** [richardwilkes/gcs#679]
When I use the "Export" feature for making the HTML sheets, both @PORTRAIT and @PORTRAIT_EMBEDDED show no image. @PORTRAIT_EMBEDDED makes an invalid URL string in BASE64. According to @Neck on Discord, "instances of + are being replaced with - and / is being replaced with _" Also noticed that using the @PORTRAIT doesn't replace the path correctly, on Windows 11 for me, it replaces all "\" with "%5C".

**Comment by richardwilkes** [comment]
Interesting. Safari loads this just fine. Chrome and Firefox, however, don't.

**Comment by richardwilkes** [comment]
Turns out that Chrome and Firefox don't understand the "URL" variant of base64 and require the "Standard" variant. Safari supports either form. Anyway, I'll change GCS to emit the base64 in the "Standard" variant format.
