### ISSUE TITLE
Discord Rendering

### ISSUE THREAD

**Issue by haksanlulz** [richardwilkes/gcs#687]
I don't really know how to describe this but when Discord hooks into GCS it results in text not rendering properly seemingly at random, like this:
![image](https://user-images.githubusercontent.com/18426277/233802755-5ae7f3f7-ec53-4f01-9a82-83295930236a.png)

**Comment by richardwilkes** [comment]
This has been reported before. Unfortunately, there doesn't seem to be anything I can do about it. Discord is doing something odd behind my app's back and they are the ones that will need to address it.
