### ISSUE TITLE
Magic Spell Casting Cost/Time to Cast changes due to higher skill level.

### ISSUE THREAD

**Issue by dgtexan** [richardwilkes/gcs#69]
In the Basic Set and Magic books, it goes into how the higher your level in a spell, the lower it's cost to cast and time to cast can be (minimum 0 cost and 1s to cast). I don't see this having any effect or changes in your application. Is that possible to implement?

In the image below, Command base cost is 2 at lvl 16. At lvl 15, cost is reduced by 1 point, so should only cost 1 instead of 2. I know I can manually change it, but it would be a better following of the rules if it automagically did that. Cost is reduced by 1 point every and time is halved again every 5 lvls starting at 15. 

![image](https://user-images.githubusercontent.com/38168748/41995814-33b4eaae-7a10-11e8-8983-5ad0c0a2037e.png)

**Comment by richardwilkes** [comment]
Unfortunately, no, not at the moment. The problem is that the cost info isn't always just a number. If it were, it would be easy enough to handle. Unfortunately, as with a lot of GURPS rules, there are a lot of special cases that have to be handled and that can make it excessively complex.

**Comment by jutis** [comment]
You could just add another column with the reduced cost base don skill level

**Comment by dgtexan** [comment]
He has a point. There's too many spells with "varies", or other special costs. Also cost reduction is done after multipliers such as for area spells. If an area spell is 2 to cast, cost reduction is done after multiplying for range. Reducing the cost on the sheet would make it look like 1 to cast. Thus a 3 yard casting would look like 3 cost, when it should actually be 5 cost if skill level was at 15-19. And at 20-25, it would look free when it would actually be 4 cost.

**Comment by jutis** [comment]
What I was suggesting is adding another column to the spell. "Mod." or some such after Mana Cost, and just add the modifier to the cost there.
So when you have a spell with skill level -15 then the column shows -1 if you have a skill of -20 then it states -2. All the player needs to do is work out the cost and reduce it with the modifier

**Comment by richardwilkes** [comment]
This has been covered as far as GCS is ever likely to by the option added either earlier this year or sometime last year that will display a note in the spell description with any reductions you are entitled to due to skill.
