### ISSUE TITLE
Adding Traits Crashes Program

### ISSUE THREAD

**Issue by Karmalain** [richardwilkes/gcs#701]
My Wife and I have recently downloaded this program. Anytime either she or I try to drag the traits or save them to a character sheet the program freezes and won't let us save. If any assistance can be given it would be appreciated.

**Comment by richardwilkes** [comment]
Yes, a fix in v5.10.2 (and v5.10.3) that I made to fix a memory leak is causing a deadlock in some situations, primarily on Windows machines. I have a fix I'm testing right now. v5.10.4 will be released shortly to address the problem.

**Comment by Karmalain** [comment]
Thank you very much. We appreciate all your hard work

**Comment by richardwilkes** [comment]
OK, should be fixed now with commit da6ac83e343334139903723085232b72bbcadf89.

I just published the new release.
