### ISSUE TITLE
Attribute fields don't reset their red status, if the correct value is returned using the Undo option

### ISSUE THREAD

**Issue by saint-thomas-more** [richardwilkes/gcs#703]
Version: 5.10.4
Also happens in editors; for points

![image](https://github.com/richardwilkes/gcs/assets/126619536/035627e8-2ff2-4470-a8e3-8ce086dea547)

![image](https://github.com/richardwilkes/gcs/assets/126619536/96c64272-037e-4cf2-b2b6-2b46b48a7047)

**Comment by richardwilkes** [comment]
I wonder how long that's been the case? Anyway, thanks for creating an issue for it.
