### ISSUE TITLE
Half-Stat price alternative rule

### ISSUE THREAD

**Issue by WhiteLodgeOwl** [richardwilkes/gcs#71]
Would it be possible to include the alternate skill cost in "By Default" by Douglas Cole (Pyramid 3/65, Alternate GURPS III)?

It would halve the value of an attribute in order to buy a skill, also changing the skill defaulting cost.

Is this something you'd thinked about?

Thanks!!

**Comment by Cazacurdas** [comment]
Thanks for the quick reply!

Is there any way around in the program to simulate the rule? I already asked this at rpg.stackexchange and "all" I got was a couple of code blocks from a friendly user, but I asume that would imply having my own compilation of the program!

Here you have a link, https://rpg.stackexchange.com/questions/125626/how-can-i-write-custom-attribute-value-rules-for-the-gurps-character-sheet-tool.

If I can be of any help, please let me know!

Thanks a lot again!
