### ISSUE TITLE
Bug (?) Report: random_weight() will take Traits into account even if they are disabled

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#716]
I am just looking at the code for evalRandomWeight and noticed that when it checks for Traits such as "Skinny", "Fat", etc. it does not seem to check if the Trait is enabled. This may go against what users who end up using the attribute function would expect.

**Comment by richardwilkes** [comment]
Yes it does. The traversal function is being asked to only return those traits that match and are enabled.
