### ISSUE TITLE
Trait "Talent" does not apply to default calculation even if it should 

### ISSUE THREAD

**Issue by Andrea-DM95** [richardwilkes/gcs#726]
Basic set states in the advantage Talent that it gives the benefit "A bonus of +1 per level with all affected skills, even for default use.".
I think the program apply the bonus on top of default. For example say you take a blank character and have 8 point in Naturalist and you take a custom Talent 3 that only gives you a +1 per level to Naturalist; This will effectively give you "Naturalist 14". You later add Biology at 0 point to the sheet. Since Biology has default "Naturalist -6", it should display "Biology 8" but it instead display "Biology 5" as if the Talent is not counted in the default and applied after the calculation.
That is confirmed by the fact that if you remove the custom "Talent" Naturalist is 11, making "Biology 5" a correct calculation to default "Naturalist-6".

**Comment by Andrea-DM95** [comment]
Shouldn't the default just be calculated after every bonus is applied if it affects the general SL of a skill? Does that require a change in the data model as a whole or just to make the calculation afterward?

**Comment by richardwilkes** [comment]
That's just it -- the general rule is that defaults don't get to benefit from bonuses, because otherwise you effectively double-dip when both the default and the skill in question receive the bonus. This is an exception to that rule apparently, which means the data model has to reflect that exceptional state, since it only applies to *some* bonuses, not all. Not a huge deal, but not free, either.

I do appreciate you finding and reporting the issue. I just wanted to make sure you were aware that I'm unlikely to make a change for this in the near future, as I have other things that I'd rather spend my time on.

**Comment by Andrea-DM95** [comment]
Of course, i was unsure whether there was any easy solution mostly to check if it's something i could have look up into. But considering it might be a more in depth fix I might not be able to help with my limited knowledge of go.
I'm glad I could help with reporting at least, and thanks for the replies and letting me know!


-------- Original message --------
From: Richard Wilkes ***@***.***>
Date: 2023-07-05 17:23 (GMT+01:00)
To: richardwilkes/gcs ***@***.***>
Cc: Andrea-DM95 ***@***.***>, Author ***@***.***>
Subject: Re: [richardwilkes/gcs] Trait "Talent" does not apply to default calculation even if it should (Issue #726)


That's just it -- the general rule is that defaults don't get to benefit from bonuses, because otherwise you effectively double-dip when both the default and the skill in question receive the bonus. This is an exception to that rule apparently, which means the data model has to reflect that exceptional state, since it only applies to some bonuses, not all. Not a huge deal, but not free, either.

I do appreciate you finding and reporting the issue. I just wanted to make sure you were aware that I'm unlikely to make a change for this in the near future, as I have other things that I'd rather spend my time on.

**Comment by smithkm** [comment]
Could this be handled without altering the data model by looking for the category "talent" on the trait granting the bonus?

PU3 page 4 explains exactly how talent bonuses work:

> When skills that enjoy Talent bonuses are used in default calculations, always do the math and determine the point costs without the Talent level, and then add the Talent bonus at the end. The Talent only adds to the skills listed for it – never to skills that default to those skills, unless they’re noted under the Talent as well (in which case, adding Talent as the final step ensures that it isn’t counted twice).

**Comment by smithkm** [comment]
Just did a test and GCS 5.25.1 is behaving exactly as the rules describe.  I have Born Spacer talent, Aeorobatics, and Aquabatics and Aerobatics defaults to aquabatics, Aquabatics gets the talent bonus applied on top of the default.  If Aquabatics defaults to aerobatics, it's computed as if aerobatics didn't have the talent bonus.

**Comment by richardwilkes** [comment]
So, you're saying there is nothing to be done here after all, @smithkm?

**Comment by smithkm** [comment]
Yes, the current way GCS handles bonuses is how Power Ups 3 says Talents should work when doing defaults and I'm pretty sure that's meant as a clarification of what's in Basic Set, not a new rule.
