### ISSUE TITLE
Option for Blank Lines?

### ISSUE THREAD

**Issue by atomfullerene** [richardwilkes/gcs#73]
I was hoping to use GCS to make some character sheets for my players, but I'd like the option to leave in some blank space in case they gain new weapons, skills, or advantages/disadvantages.  However I can't seem to find a good way to do this.   Is this possible, and if not, could it be added?

**Comment by richardwilkes** [comment]
I assume you are printing these out, which is why they can't just use the program to add additional items? Your best approach to this would be to alter the HTML template to include some empty rows where you needed them and export to HTML.

**Comment by atomfullerene** [comment]
thanks
