### ISSUE TITLE
Feature Request: Apply search field text as filter text when following a search result.

### ISSUE THREAD

**Issue by Human** [richardwilkes/gcs#732]
The new search is great! But the current UX is that you have to enter your search term twice: Once in the library explorer search box, and then again in the filter when you click a search result in the library explorer. I propose auto-applying the search term that you "followed" as the content filter.

**Comment by richardwilkes** [comment]
How would I determine that you “followed” a result?

**Comment by Human** [comment]
Well, for example, when I search for "necklace" the search feature knows that there are two results and what those results are: 

* Dungeon Fantasy 1 Equipment
* Dungeon Fantasy RPG Equipment

So it would seem to me that if you clicked on either of those two search results while a search was active, that would count as following a result.

**Comment by richardwilkes** [comment]
Sure... but the problem comes in when you don't then clear the search field. Every file you open from that point forward will attempt to filter if using that stance, since most people when using the field don't clear it until they decide to search for something else in the library explorer.

**Comment by Human** [comment]
>Every file you open from that point forward will attempt to filter if using that stance

I wouldn't want it to work that way, either. Sorry if my suggestion was unclear, but I thought of this as something that would only apply when opening files that were found in the search.

**Comment by Human** [comment]
Thank you very much!
