### ISSUE TITLE
Add the ability to use 'Page Up' and 'Page Down' keys to scroll up add down quickly through a page or section.

### ISSUE THREAD

**Issue by NewOrderrr** [richardwilkes/gcs#741]
As it says in the title, enable Page Up and Page Down keys to move up and down through a section. Home and End keys move to the top and bottom respectively, allowing page keys to move up and down would help a lot.

Thanks in advance!

**Comment by richardwilkes** [comment]
Implemented page up/down by keyboard in the underlying unison scroll panel. Holding down shift allows scrolling horizontally, too.

Note that this requires that the current keyboard focus be within the scroll panel in question AND that the component that currently has keyboard focus not do anything with those keys. Text fields, for example, do respond to page up/down, so when a text field is the focus, using these keys will not scroll the outer view.
