### ISSUE TITLE
Bow damage not calculating correctly, perhaps since update

### ISSUE THREAD

**Issue by Tackarii** [richardwilkes/gcs#743]
First, thank you for GCS!!!

I'm not an old hand, but
Long bow in gcs deals 1d+1 imp damage, not matching the manual number shown as thr+2 
Composite in gcs deals 1d+1 imp damage, not thr+3
"Normal" bow in gcs deals 1d-1 imp damage, which is at least less than above bows, but still not thr+1
Shortbow in gcs deals 1d-3, not thr flat.

The stats do not change with strength alteration in gcs v5.15.0. That's the flat damage roll for each.

In the basic manual on page 275 it has the stats, and the the table is on pg 16. I may be confused about how the math of thrusting attacks works, but the numbers just don't seem to line up.

Thank you!

**Comment by richardwilkes** [comment]
Bows are an odd weapon, in that they use a rule where they are all rated with their own ST, independent of the user of the bow. A standard Longbow, for example, has a +2 damage modifier and a default ST rating of 11 (its minimum), which gives thr damage of 1d-1, which gives a final damage of 1d+1. This is reflected in on the sheet correctly. You can open up the bow entry and change the "Rated ST" field to change its damage and range characteristics. B270, under the heading "Bows, Crossbows, and ST", discusses this.

**Comment by richardwilkes** [comment]
Oh, I should also mention that GCS support for Rated ST on weapons didn't exist until v5.11, so it's fairly new. Prior to that, you had to hand-edit the damage fields to get correct values, which most people probably didn't even realize was necessary.

**Comment by Tackarii** [comment]
Ahhh. That makes sense, thank you for taking the time to help me out there!
--
*Taylor Goodwin, ND*
Naturopathic Doctor
InnerVectorNaturopaths.com
(918) 280-8640
