### ISSUE TITLE
Add ability to move or copy items from one library to another of the same type

### ISSUE THREAD

**Issue by SilntObsvr** [richardwilkes/gcs#745]
We can copy items from a library to a template or character sheet, and then copy from the sheet or template to a library, but there doesn't seem to be a way (for customizing a setting-specific library, for instance) to copy items directly from one library to another of the same type.

Example: if I want to pull equipment from Low Tech to add to my setting's equipment library, I have to copy each item to a template or character sheet, and then copy from there to the setting library.  I'd like to be able to just drag and drop, preferably with a prompt to "copy or move" (though copy only would cover my immediate needs), including a multi-selection.

**Comment by richardwilkes** [comment]
What's wrong with drag and drop? That's the expected way to copy content from one place to another. The specialized menu items for apply templates and such primarily exist to allow disjoint types of data to be copied all at once.

**Comment by SilntObsvr** [comment]
When I posted this, I hadn't discovered that GCS could tile Libraries inside the main window, which appears to be the only way drag-and-drop works.  All this time, I've only been seeing Libraries open on top of each other, all of them collectively tiled to the right (or left) of a character sheet or template that was open first.  Please close it -- drag and drop works fine now that I can use it.
