### ISSUE TITLE
Study

### ISSUE THREAD

**Issue by XerWolf** [richardwilkes/gcs#748]
Can we get some way to have Study impact the skill level without it also affecting points spent?  Not sure the rules around this.

**Comment by richardwilkes** [comment]
That's not the way the study rules work. Studying grants bonus points after a certain amount of time has been spent doing it, which is adjusted depending upon they method of study. GCS already does what the rules outline. I'm unlikely to change this, but if you have something specific in mind, you'll need to spell out exactly what you're looking for.

**Comment by XerWolf** [comment]
how do the bonus points work in calculations?

**Comment by richardwilkes** [comment]
GCS doesn't actually give you the points. It just tracks when you'd be eligible for them. i.e. once you've accumulated the necessary 200 effective training hours, you may then remove 200 hours worth of study and add a point to the skill.
