### ISSUE TITLE
Simple Text Export

### ISSUE THREAD

**Issue by Angular-Angel** [richardwilkes/gcs#75]
A way to export characters into simple text for posting to internet forums and the like would be really useful. Something like this: 

> Wonder Woman
> 
> 
> 2,611 points
> Attributes:
> ST 36/1,020 [100]*
> DX 15 [100]
> IQ 12 [40]
> HT 15 [50]
> 
> Secondary Characteristics:
> Dmg 4d-1/6d+1 (103d/105d)
> BL 259 lbs. (208,080 lbs/100 tons).
> HP 36 [0]
> Will 15 [15]
> Per 13 [5]
> FP 20 [15]
> Basic Speed 8.00 [10]
> Basic Move 8 [0]
> Dodge 15
> 
> Languages:
> Ancient Greek (Native) (Native Language [0]
> Ancient Scythian (Native Spoken/Illiterate) [3]
> English (Accented) [4]
> 
> Cultural Familiarities:
> Themyscira (Native) [0]
> 
> Advantages:
> Appearance (Transcendent) [20]
> Catfall (Divine, -10%) [9]
> Claws (Blunt Claws) [3]
> Damage Resistance 100 (No Signature, +20%; Tough Skin, -40%; Divine, -10%)
> Enhanced Block 3 [15]
> Enhanced Dodge 3 [45]
> Enhanced Move (Ground) 2 (Ground Move 32/64 mph) [40]
> Enhanced Parry (All Parries) 3[30]
> Enhanced Time Sense [45]
> Hard to Kill 3 [6]
> Hard to Subdue 3 [6]
> High Pain Threshold [10]
> Immunity to Sickness (Divine, -10%) [14]
> Injury Tolerance (Damage Reduction /100) (Divine, -10%) [270]
> Lasso of Truth [305]
> – Binding 40 (Extended Duration: Permanent, +150% Gadget/Can Be Stolen: Quick Contest of DX/ST, -30%; Gadget/Unique, -25%; Melee Attack: Reach 1-4, -15%; One-Shot, -10%; Persistent, +40%; Unbreakable, +40%; Magical, -10%) [192]
> – Mind Control (Accessibility: Only When Using Binding, -10%; Conditioning, +50%; Extended Duration (×100), +80%; Gadget/Can Be Stolen: Quick Contest of DX/ST, -30%; Gadget/Unique, -25%; Independent, +70%; Magical, -10%) [113]
> Resistant to Poisons (+8) (Divine, -10%) [7]
> Super Jump 3 (Divine, -10%) [27]
> Super ST +16/+1,000 (Super-Effort, +300%; Divine, -10%) [624]
> Super Throw 3 (Divine, -10%) [27]
> Trained By A Master [30]
> Unaging (Divine, -10%) [14]
> Very Fit [15]
> Very Rapid Healing [15]
> Wealth (Very Wealthy) [30]
> Weapon Master (Broadsword and Shield) [25]
> 
> Perks:
> Courtesy Status 6 [6]
> Power Grappling [1]
> Style Familiarity (Ancient Greek Boxing) [1]
> Style Familiarity (Greco-Roman Wrestling) [1]
> Style Familiarity (Heroic Spear Fighting) [1]
> Style Familiarity (Hoplomachia) [1]
> Style Familiarity (Pankration) [1]
> Style Familiarity (Scythian Horseback Combat) [1] (effectively the same as Armatura Equestris)
> Sure-Footed (Uneven) [1]
> 
> Disadvantages:
> Charitable (9) [-22]
> Code of Honor (Soldier's) [-10]
> Impulsiveness (12) [-10]
> Overconfidence (9) [-7]
> Secret Identity (Utter Rejection) [-10]
> Social Stigma (Minority Group) [-10]
> Stubbornness [-5]
> Vow (Chastity) [-10]
> Xenophilia [-10]
> 
> Quirks:
> Devout Believer (Women's Suffrage) [-1]
> Dislikes Chauvinistic Men [-1]
> Enamored of Steve Trevor [-1]
> Expression ("Great Hera!") [-1]
> Proud [-1]
> 
> Skills:
> Acrobatics (H) DX+0 [4] – 15
> Bow (A) DX+5 [20] – 20
> Boxing (A) DX+5 [20] – 20
> Breaking Blow (H) IQ+2 [12] – 14
> Breath Control (H) HT+0 [4] – 15
> Broadsword (A) DX+5 [20] – 20
> Climbing (A) DX+1 [4] – 16
> Fast-Draw (Arrow) (E) DX+1 [1] – 16†
> Forced Entry (E) DX+0 [1] – 15
> Games (Boxing) (E) IQ+2 [4] – 14
> Games (Pankration) (E) IQ+2 [4] – 14
> Games (Wrestling) (E) IQ+2 [4] – 14
> Hiking (A) HT-1 [1] – 14
> Hobby Skill (Feats of Strength) (E) DX+3 [8] – 18
> Immovable Stance (H) DX+3 [16] – 18
> Intimidation (A) Will+0 [2] – 15
> Judo (H) DX+5 [24] – 20
> Jumping (E) DX+2 [4] – 17
> Karate (H) DX+5 [24] – 20
> Lasso (A) DX+5 [20] – 20
> Lifting (A) HT+0 [2] – 15
> Observation (A) Per+1 [4] – 14
> Parry Missile Weapons (H) DX+5 [24] – 20
> Power Blow (H) Will+1 [8] – 16
> Pressure Points (Human) (H) IQ+2 [12] – 14
> Riding (Equines) (A) DX+1 [4] – 16
> Running (A) HT+0 [2] – 15
> Savoir-Faire (High Society) (E) IQ+0 [1] – 12
> Shield (E) DX+5 [16] – 20
> Shortsword (A) DX+5 [8] – 20‡
> Spear (A) DX+5 [20] – 20
> Staff (A) DX+5 [8] – 20§
> Swimming (E) HT+0 [1] – 15
> Tactics (H) IQ+2 [12] – 14
> Throwing (A) DX+1 [4] – 16
> Thrown Weapon (Spear) (E) DX+5 [16] – 20
> Wrestling (A) DX+5 [20] – 20
> Wrestling Sport (A) DX+5 [12] – 20#
> 
> Techniques:
> Acrobatic Stand (A) def+6 [6] – 15
> 
> * Includes +16/+1,000 from Super ST.
> † Includes +1 from Enhanced Time Sense.
> ‡ Defaulted from Broadsword.
> § Defaulted from Spear.
> \# Defaulted from Wrestling.
> 
> Role-Playing Notes:
> Princess Diana is in all respects a warrior first, princess and hero second. She hasn't yet acclimated to Man's World, and is still making false assumptions, especially about the place of women in the world. She will do what needs to be done to end the fight quickly.

**Comment by richardwilkes** [comment]
You can already do this using the text templates output feature.

**Comment by Angular-Angel** [comment]
Actually, it might be cool to have the templates under output_templates each outamitaccly generate a menu option to export as them? Not sure how easy that is to do, though. :/

**Comment by Angular-Angel** [comment]
Also your text_template.txt was missing notes, so I went and added them. I'd put in a pull request, but for something so small it doesn;t really seem worth the trouble, so heres the change:

Notes:@NOTES_LOOP_START 
@NOTE @NOTES_LOOP_END

Just slap that on the end of the file and you're good to go. XD

**Comment by TheFabulousIronChef** [comment]
Ah, never mind. For those who didn't understand at first, like me, I figured it out: There are TXT templates in ***\gcs-4.11.1\Library\Output Templates. Go to Edit/Output/Preferences, click "Choose" next to Text Export Template, and then choose one of those. You can then export to a text file. 

> I do not see how to export to text. As Angular-Angel commented:
> 
> > Actually, it might be cool to have the templates under output_templates each automatically generate a menu option to export as them? Not sure how easy that is to do, though. :/
> 
> I am not familiar with programming, so I apologize if this is obvious to many...but it doesn't seem obvious as to how to do it, since the only export option in the menu is "Export to GURPS Calculator." The program is awesome, BTW, I just don't know how to do this.

**Comment by richardwilkes** [comment]
Added the suggested notes to the text output template.
