### ISSUE TITLE
GCS Character Sheet has a 'Calculator' button

### ISSUE THREAD

**Issue by troydt** [richardwilkes/gcs#754]
I've been looking for any info on where the files associated with the items on it are located.  I'd like to add some more 'calculations'

Also, the Discord server is no longer available(?), is there anywhere to post questions on a GURPS GCS community forum?
Discord reports the Envite is no longer valid...

**Comment by richardwilkes** [comment]
I have no idea what you're asking for regarding "calculations". Please be more specific.

As for the Discord server, it hasn't gone away and the invite link still works -- tested it just now. Did you try it from the main GCS web site page?

**Comment by troydt** [comment]
Sorry for the d-lay, real life got in the way.  :-)On the character sheet is a button just to left of the search box, Calculator.It opens a panel for that character so you can check Jumping, Throwing and Hiking information for given parameters.Is there a way to enter custom ones: Turning Radius, Acceleration/Deceleration, Take-Off distances for fliers, suffocation...  Some script/xml I could provide to id parms, formulas and UI?Oh, I got that error for invalid Discord invite from everywhere.  I had it auto logging in and my account needed to be verified again.  It's been a while since I used it.  Had to Continue, then log out/in.  I finally got the real error and made it in.  I've posted the question there with a screen shot...Thanks,TroyOn Oct 22, 2023 6:56 PM, Richard Wilkes ***@***.***> wrote:
I have no idea what you're asking for regarding "calculations". Please be more specific.
As for the Discord server, it hasn't gone away and the invite link still works -- tested it just now. Did you try it from the main GCS web site page?

**Comment by richardwilkes** [comment]
There is no provision for adding your own calculations there. If you have suggestions for specific additions, please create a new issue for each and detail what it is you'd like to see.
