### ISSUE TITLE
The less than 1/3 rule for HP and FP is working incorrectly

### ISSUE THREAD

**Issue by VanessaWGames** [richardwilkes/gcs#760]
This rule doesn't work properly with the way that attributes are set up. Specifically when you have a multiple of 3 as your HP or FP. For instance if you have 12 FP then you will be set to Tired and have your attributes reduced at 4 FP when it should trigger first at 3 FP.

**Comment by richardwilkes** [comment]
Doesn't for me with the stock attribute configuration. If you have 12 FP when full, then the range 11 to 4 marks you as "Tiring", while the range 3 to 1 marks you as "Tired" (and has the appropriate effects). The range 0 to -11 will mark you as "Collapse", which requires rolls to stay conscious, and at -12, you are marked "Unconscious".

I suspect you aren't using the stock configuration. You may want to reset things, both in the default settings and in your specific sheet's settings.

**Comment by saint-thomas-more** [comment]
Three different people tested it separately.
![image](https://github.com/richardwilkes/gcs/assets/126619536/75ae2130-e709-4e58-abf5-4e9ccab8369e)

**Comment by richardwilkes** [comment]
Yep, as I already pointed out, you're not using the current set of default attributes. The current set uses `ceil($fp/3)-1` for the "Tired" state. Something similar is done with HP. Essentially, you need to go back and reset the settings to the factory settings.

**Comment by saint-thomas-more** [comment]
Ah, I see now. I have no idea why my default attribute setting weren't, well, default. I've never changed them, as far as I know. Thanks!

**Comment by VanessaWGames** [comment]
Fair enough! I assumed that new updates would override old settings so I assume it was an issue at some point that was fixed but you have to manually update it now.

Doing so fixed it so thanks!

**Comment by richardwilkes** [comment]
Yes, I believe the defaults were at one time slightly different. Unfortunately, I can't have GCS just update them for you, since you may have made intentional changes. I do point out when these type of changes have been made in the release notes, but that's not something a lot of people tend to read (and even when they do, they may not realize that there is an action they should take).
