### ISSUE TITLE
Add option for skill features based on weapon usage

### ISSUE THREAD

**Issue by Zuljita** [richardwilkes/gcs#763]
Request is motivated by Throwing Art, which adds damage per die when throwing a weapon so long as skill is DX+2.  Using tags at the weapon level doesn't work for weapons with both a melee and a thrown use, so I'd like to be able to add damage per die based on use.

I'm open to another approach if one's already been adopted by the community.

What exists:
![image](https://github.com/richardwilkes/gcs/assets/33107187/f314b076-815c-4854-8bd6-53b827156587)

What I'd like to see is that with one more line that says "And who's usage is"

**Comment by richardwilkes** [comment]
Hmm... the problem here is that whole clause is referring to the skill, not the weapon. You'll note that if you switch that second popup (the one that reads "to weapons whose required skill name") to either of the other two possibilities, you then get usage, because you're now referring to the weapon. What am I missing?

**Comment by saint-thomas-more** [comment]
> Hmm... the problem here is that whole clause is referring to the skill, not the weapon. You'll note that if you switch that second popup (the one that reads "to weapons whose required skill name") to either of the other two possibilities, you then get usage, because you're now referring to the weapon. What am I missing?

I've discussed this in the Discord server. You get the usage, but you lose the RSL condition. (Funnily enough, it stays until you save, but disappears after, since it belonged to the other condition tree). The only way that I had found is to tag the appropriate weapons manually.

**Comment by richardwilkes** [comment]
Hmm... thanks for pointing out the bug regarding the extra lines that stick around when they aren't supposed to. I'll fix that bit.
