### ISSUE TITLE
Upper- and lowercase for names generated from .names files not preserved

### ISSUE THREAD

**Issue by Nedorus** [richardwilkes/gcs#765]
Actually I'm unsure whether this is an enhancement or a bug. The current behavior seems to be quite deliberate.

**Current behavior:**
Names taken from the .names files are changed to "first letter uppercase, rest lowercase". This is independent of the way they are listed in the .names file.
e.g. the name "van Neumann" fro the .names file is changed to "Van neumann".

**Wanted behavior:**
The case of the name in the .names file should be preserved and not be changed.
e.g.

1. the name "van Neumann" from the .names file should be shown as "van Neumann"
2. the name "eDgeLoRd" from the .names file should be shown as "eDgeLoRd" (sorry had to use this example)

**Why is this benefitial:**
The “van Neumann” example is just one case where it shouldn’t be the first letter that is uppercase. Any double name “Walter-Maria” or two word nickname like “Silver Serpentis” also looks weird. So preserving case from the .names file seems to be the easiest to solve this.

**Comment by richardwilkes** [comment]
If you want multi-segment name generation, I believe there is already support for that. I'm unlikely to change the data normalization for that use case, given there is already a way to do it.

I'm not somewhere I can pull up an example of how to do that right now, but am happy to provide one later when I have time -- and if it turns out this can't be done, then I'll consider ways to make it possible.

**Comment by Nedorus** [comment]
Right now I'm doing multi-segment names doing this:

```				
"name_generators": [
    "Shadowrun - First - Female",
    "Shadowrun - Last",
    "Opening Bracket",
    "Article",
    "Shadowrun - Nick",
    "Closing Bracket"
]
```

But there are lots of cases where names or nicknames wouldn't be multi-segment per-se but need inner-characters in uppercase. The "Walter-Maria" example is one typical one.
[Google Search](https://www.google.com/search?q=deutsche+doppelnamen+m%C3%A4dchen&sca_esv=582743473&rlz=1C1FNES_deDE1011DE1011&sxsrf=AM9HkKmetfNMxZnvnNCkqeL8Pkbd39Gwzg%3A1700078889481&ei=KSVVZaT1HLSFxc8P74CTwAQ&oq=deutsche+doppelname&gs_lp=Egxnd3Mtd2l6LXNlcnAiE2RldXRzY2hlIGRvcHBlbG5hbWUqAggBMgUQABiABDIFEAAYgAQyBRAAGIAEMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB5I00hQAFiOMnABeACQAQCYAWqgAd4OqgEEMTYuNLgBA8gBAPgBAcICBxAjGIoFGCfCAgwQIxiKBRgTGIAEGCfCAgsQABiABBixAxiDAcICCxAuGIAEGLEDGIMBwgIREC4YgAQYsQMYgwEYxwEY0QPCAgcQABiKBRhDwgIHEC4YigUYQ8ICDhAuGIAEGMcBGK8BGI4FwgINEC4YigUYsQMYgwEYQ8ICCBAAGIAEGLEDwgITEC4YigUYsQMYgwEYxwEY0QMYQ8ICFhAuGIoFGEMYlwUY3AQY3gQY3wTYAQHCAhQQLhiABBixAxiDARjHARivARiOBcICCxAAGIoFGLEDGIMBwgIUEC4YgAQYxwEYrwEYmAUYmQUYjgXCAgsQLhiABBjHARjRA8ICCBAuGIAEGLEDwgIOEC4YgAQYsQMYxwEY0QPCAgsQLhiABBjHARivAcICCBAuGLEDGIAEwgIXEC4YsQMYgAQYlwUY3AQY3gQY3wTYAQHCAgUQLhiABMICCBAuGBYYHhgPwgIUEC4YgAQYlwUY3AQY3gQY3wTYAQHCAggQABjLARiABOIDBBgAIEGIBgG6BgYIARABGBQ&sclient=gws-wiz-serp)

**Comment by richardwilkes** [comment]
You'd need to use one of the other generator types, i.e. not the "simple" one. I don't have a list of possible options off the top of my head though, so will have to wait until I find a few spare cycles.

**Comment by richardwilkes** [comment]
In commit 3664e46c, I've added the ability to control whether lowercase is forced as well as whether the first character is forced to uppercase. An example of using that (which won't work unless you build GCS from source or wait until v5.18 is released):

```json
{
  "type": "compound",
  "no_lowered": true,
  "no_first_to_upper": true,
  "separator": " ",
  "compound": [
    {
      "type": "simple",
      "training_data": [
        "van",
        "VON"
      ]
    },
    {
      "type": "simple",
      "no_lowered": true,
      "no_first_to_upper": true,
      "training_data": [
        "derHoven",
        "Sparkle"
      ]
    }
  ]
}
```

**Comment by richardwilkes** [comment]
Oh, I should also note that I've also added some documentation about the .names file format at https://github.com/richardwilkes/gcs_master_library/blob/master/Library/Markdown/Help/Name%20Generators.md, which will show up in the GCS Master Library when I do the next release for it.
