### ISSUE TITLE
Some options from .names files are never chosen

### ISSUE THREAD

**Issue by Nedorus** [richardwilkes/gcs#766]
How to reproduce the issue:
create the following file as a .names files
Test male:
`{
  "type": "simple",
  "training_data": [
    "1",
    "2",
	"3"
  ]
}`

Tet Female:
`{
  "type": "simple",
  "training_data": [
    "c",
    "a",
	"b"
  ]
}`

Create an ancestry file with the following “gender options” section:
`	"gender_options": [
		{
			"weight": 1,
			"value": {
				"name": "Male",
				"name_generators": [
					"Test Male"
				]
			}
		},
		{
			"weight": 1,
			"value": {
				"name": "Female",
				"name_generators": [
					"Test Female"
				]
			}
		}
	]`

Create a new character and apply template with the new ancestry.

For male “3” is never chosen for a name.
For female “C” is never chosen for a name.

Expected behavior:
All options listed in the .names files are chosen as names.
Male names “1”, “2” and “3”
Female names “A”, “B” and “C”

**Comment by richardwilkes** [comment]
Hmm... I that should be working. I'll have to verify in the code again. It is easily possible to just not have a value selected for a long period, though. I use the hardware random number generator when available, so it should be as random as possible.

**Comment by richardwilkes** [comment]
Yep, turns out there was a problem where the total range of values chosen via randomization was one less than it should have been, which meant with weightings of 1 for each, you end up missing out on one. I've corrected this with the latest commit, which will be part of the next release.
