### ISSUE TITLE
Expression Function for Weapon Damage

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#768]
Simply put, some kind of ``weapon_damage(name, usage)`` function that returns a dice value that can be modified, by adding or subtracting other (same size) dice values from it, such as:
`1d+1d=2d`
`1d3+0d3+1=1d3+1`

Hopefully this isn't too hard a request. The notes expressions are super useful and let me calculate the numbers for modified traits within GCS that functionally import into Foundry or Print.
I can even implement entire house rules or without needing more functionality built into the program or to duplicate traits in the traits list. However when it comes to traits that modify weapon damage across the board, there's no way to retrieve it.

**Comment by richardwilkes** [comment]
You're actually asking for more than just a new `weapon_damage()` function, since you also want some way to decompose the damage into a dice expression -- which isn't always possible. Third, you also want to be able to add two dice expressions together and have them merge into a new, consolidated version.

**Comment by richardwilkes** [comment]
btw, glad to hear someone is getting use out of the ability to place expressions into the notes!

**Comment by richardwilkes** [comment]
Commit fcaf5d46bfbeff156958dc6c4dda4330a608bfab adds support for these additional functions:

add_dice(dice_spec1, dice_spec2)
dice_count(dice_spec)
dice_modifier(dice_spec)
dice_multiplier(dice_spec)
dice_sides(dice_spec)
subtract_dice(dice_spec1, dice_spec2)

**Comment by richardwilkes** [comment]
Added `weapon_damage(description, usage)`.

I suspect this by itself won't be adequate, due to the likely need to decompose the "damage" string further. Leaving that for a future issue for now.
