### ISSUE TITLE
Build fails on linux: Error: "Unknown argument: --module-path"

### ISSUE THREAD

**Issue by Angular-Angel** [richardwilkes/gcs#77]
I'm trying to build this project as directed in the command line instructions in the readme, but I can't get the "ant bundle" task to complete. It keeps giving me the error "Unknown argument: --module-path". I think this is because this argument is being used on javac, which doesn't have that option, only --processor-module-path and --upgrade-module-path? I'm not sure though. I have confirmed that my java _does_ have this option, though.

The relevant versions of ant, javac, and os are as follows:

Apache Ant(TM) version 1.10.3 compiled on July 19 2018
javac 10.0.2
Xubuntu 18.04 (bionic)

I managed to get the project to compile in eclipse, so this isn't an urgent problem, but it might be something worth looking into.

**Comment by richardwilkes** [comment]
Did you ever determine what the issue was?

**Comment by Angular-Angel** [comment]
I think I did and it was something to do with permissions? I don't remember though, I've been distracted with other things for a while now. XD

**Comment by ilikerobots** [comment]
I ran into this issue as well on ubuntu 18.04 with openjdk 11.  The problem appears to involve javapackager, specifically that it doesn't it exist on openjdk11.  On my system, the build falls back to using my older java 8 version of javapackager, which doesn't have the module-path arg.  

Solution should be to obtain a 11 compatible javapackager.   Some hints here: https://mail.openjdk.java.net/pipermail/openjfx-dev/2018-September/022500.html, but I have not tried this yet.

**Comment by richardwilkes** [comment]
Yes, Java 11 and 12 have removed javapackager without providing a replacement. I have experimented locally with creating packaged builds with Java 11+ despite this with some success, but got sidetracked and I don't believe I ever committed those changes. When I find some spare time, I'll look at getting that checked in.
