### ISSUE TITLE
Add "Calc" Value to Notes in JSON

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#771]
I **love** Markdown Expressions and consider them an extremely useful feature. But when importing GCS sheets into other things (Like GGA), all my work writing expressions to represent various calculations of special traits is meaningless, because the formulas are just plain text, and that is what is imported.
However if there was  a `calc` field similar to other fields, that was the note text, but with the expressions 'solved', that would solve that problem. I am *not* asking for it to be formatted in any other way. Simply the existing text of the note, but with the expression results, rather than the formula, such as:
``Strong Arm BL: ||round(($st+trait_level(Arm ST))^2/5)||`` as ``Strong Arm BL: 24`` in the `calc` value in the data.

Maybe this could be something that is optionally done in sheet settings (default off?) or only on notes that have expressions in them in the first place so every note doesn't have to be replicated in the file.

**Comment by richardwilkes** [comment]
Actually, I think it makes sense to do that by default when exporting such things. It just never occurred to me. I have a hard time thinking the unresolved value is useful for export at all, given it relies on things that are very specific to GCS -- i.e. it is unlikely that the specific functions, variable notation, and possibly even operator choices I made in GCS are replicated exactly elsewhere.

**Comment by richardwilkes** [comment]
In commit 2c4e984d, added logic to add a `resolved_notes` field (or, in the case of the actual notes objects, a `resolved_text` field) to the `calc` section of the data.
