### ISSUE TITLE
Let "Per Level" be "Per Quantity" for Equipment

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#777]
Another low priority feature IMO but one that I have run into this several times over time: I want Features that currently have a "per level" option to function per quantity when applied to Equipment.

For example, I once, many years ago provided players with rings that gave full body DR bonuses. They could stack.
I desired to have it as such: Ring Of Protection, Quantity, 4, and then a feature of +1 DR, with 'per level' checked, thinking that it'd count the qty as level and give +4 DR. It didn't, so I needed individual instances of "ring of protection" (each with +1 DR).

Much much later I had forgotten that experience I attempted to model [No School Grognard's Better Fantasy Armor](https://noschoolgrognard.blogspot.com/p/better-fantasy-armor.html). BFA gives 'lbs per DR" and $ per DR. I was thinking thinking that I could represent the thickness of the armor, with *quantity* and thus specify an item, a base material like Steel, with the base $ and lb, and 1 DR, and simply increase the # to provide a simple easy way to represent "how thick is this custom armour" via the quantity.

(Of course that is incompatible with the approach for multiple rings, since the qty is specifying non discrete physical item but it's not like I'd need to do both at once for anything).

**Comment by richardwilkes** [comment]
I was browsing through the issues today and after re-reading this one, it seems a better solution that doesn't conflate quantity with something unrelated would be to just add a "Leveled" capability to equipment, just as traits have. Without some feature interacting with it, it would do nothing except display a number after the name (like traits do). However, you could then add features that did per-level adjustments.

Does this make sense, or did I miss an important aspect of what you're asking for that really needs to use the quantity field for this purpose?

**Comment by Legendsmith** [comment]
That sounds good to me, yes.
