### ISSUE TITLE
Add book codes for new Fantasy Folk books 

### ISSUE THREAD

**Issue by ethorad** [richardwilkes/gcs#789]
Proposed codes for the new books (consistent with FFE for Fantasy Folk: Elves) are:

- FFGH for Fantasy Folk: Goblins and Hobgoblins
- FFK for Fantasy Folk: Kobolds
- FFWF for Fantasy Folk: Winged Folk

**Comment by richardwilkes** [comment]
Added to the web site page reference list with commit 44e83fa3e50d81bf85d88d1deee8617726b5eb53.
