### ISSUE TITLE
Strongbow Trait; Dungeon Fantasy RPG Library

### ISSUE THREAD

**Issue by amenditman** [richardwilkes/gcs#790]
When you add the Strongbow trait the character is able to use a bow that requires +2 ST above their current ST. Gains the damage and range benefits without the SL penalty.

It is very much Striking ST for the bow only.

Can we add a modification to the Features where we can do the following
'Conditional modifier: Bow SL DX+1, +1 Striking ST(Bow only); Bow SL DX+2, +2 Striking ST(Bow only) ' ?

**Comment by amenditman** [comment]
patch installed 5.20
Strongbow sort of works, but it also adds 2 ST to other weapons also.
Tried to upload a sample character but GitHub won't allow .gcs.
Changed the name to .gif and uploaded, just change it back and see what it does in GCS.
![Vorgruk3](https://github.com/richardwilkes/gcs/assets/63029572/de3678d5-5470-48ee-8c73-2c5cae64ed8d)

**Comment by richardwilkes** [comment]
That just means you aren't constraining what it applies to adequately. I see no upload to look at, unfortunately.

**Comment by richardwilkes** [comment]
Jump over to the GCS Discord and post the file there and tag me.
