### ISSUE TITLE
Loops of defaults between techniques and skills cause skill levels to repeatedly increase every time the sheet updates.

### ISSUE THREAD

**Issue by dec-00** [richardwilkes/gcs#791]
I found this bug while trying to create a character using a house rule that allows improving default skills as techniques.

To summarize: if you set up a technique that defaults to a skill that itself has that technique as one of its defaults, both skills/techniques will mutually default between each other, causing their skill levels (SL) to continuously increase every time the character sheet is updated in some way.

### Reproduction:

1. Add a skill to a character sheet that has another skill as a default. For example, Broadsword from Basic Set Skills.
2. Create a new technique for that character. Give the technique the name of one of the previous skill's defaults. Continuing the previous example, create a technique named "Shortsword".
3. Set that technique's "Defaults To" field as the name of the original skill. Continued example: Have the Shortsword technique default to Broadsword at -2.
4. Increase the skill points of the skill and technique by some amount. In my testing, 12 in the skill and 2 in the technique will cause this. The higher the values you put in, the more prominent the bug will be.

Below is an example image demonstrating the bug. In this example I set the skill and technique to those point values, and then repeatedly updated the sheet (clicking the randomize buttons in the Description section) to watch the skill levels increase rapidly:

![image](https://github.com/richardwilkes/gcs/assets/118613102/34084872-2cb7-4eb4-9ad8-5847a7fcbeb0)

### Suggested Solutions:

1. The original skill should be prevented from defaulting to techniques that have the original skill's name in the "Defaults To" field of the technique. This would be the ideal solution.
2. Loops of defaults should be detected and the technique's skill value should become "-", with a warning of the mutual defaults, similar to the warning for "Unsatisfied prerequisites". This would at least signify to the user to delete the default from the skill, which is an easy workaround for this issue.

**Comment by richardwilkes** [comment]
There is existing logic to prevent skills from defaulting to each other in circular loops. It doesn't, however, account for techniques as the rules as written never (that I am aware of, anyway) have scenarios where a skill defaults to a technique and it didn't occur to me that anyone would do this.

Anyway, I should be able to augment the existing pruning to include techniques.
