### ISSUE TITLE
Crash when creating two techniques that default to each other

### ISSUE THREAD

**Issue by dec-00** [richardwilkes/gcs#792]
If you create two techniques in a character sheet, each defaulting to the other one, GCS will crash immediately.

For example, when creating a technique called "Broadsword" that defaults to "Shortsword", and a "Shortsword" technique that defaults to "Broadsword", GCS will crash as soon as you apply your changes to the latter technique.

Ideally, GCS should not allow the techniques to try to default to each other and instead give a warning for the mutual defaulting.

For most users, this crash would likely never occur unintentionally, but if a skill library was set up with many skill defaults as techniques (to support an uncommon house rule, see #791), then the user might accidentally add two mutually defaulting techniques to their sheet.

**Comment by richardwilkes** [comment]
Hmm... another thing that I didn't think ever happens in the official rules (techniques defaulting to other techniques), but I could be wrong. At any rate, again, techniques weren't considered when I wrote the safe-guards for skills, so I'll have to extend those to techniques here, too.
