### ISSUE TITLE
Feature's option "as a %" just not working

### ISSUE THREAD

**Issue by TkabRft** [richardwilkes/gcs#794]
When I create Feature, for example, "Gives a weapon half-damage range modifier of", then enter "+50" and toggle "as a %": weapon with base 1/2D=1000 gains flat 50 meters of range, not 500

Also it doesn't work for other stats, not just range, for example Shots - when I add +50% I expect 20-rounders to become 30-rounders, not 70-rounders
![image](https://github.com/richardwilkes/gcs/assets/58793765/517ef22d-450e-428f-8105-c6ffd0a0c464)
![image](https://github.com/richardwilkes/gcs/assets/58793765/2e415d62-b2b0-4734-9457-a45a625661ca)

**Comment by richardwilkes** [comment]
Yep, looks like I completely missed implementing the "as a %" variants. (sigh)
