### ISSUE TITLE
Add support for Prerequisites on Trait Containers

### ISSUE THREAD

**Issue by DeckardDetribine** [richardwilkes/gcs#795]
Working on porting racial templates from a GURPS book, and I've ran into an issue where one race has a bunch of subraces with different varying traits. I would like to enforce having the base race to avoid issues resulting from accidentally choosing that subrace without the required main race, but it seems there's no prerequisite support for Trait Containers.

I could also see this having use for other templates and meta-traits that require a pre-requisite.

**Comment by richardwilkes** [comment]
I'm not sure what you're actually asking for here, as you can already create a prerequisite in the form "has a trait whose name is XXX", which works whether the trait is a container or not.

**Comment by NocTempre** [comment]
I'd like to see this too.  I'm pretty sure I'm on the latest and I do not see prerequisites as an option.
![image](https://github.com/richardwilkes/gcs/assets/158857236/ea4599b6-02f0-4be8-9a72-4ca59f4df112)

**Comment by richardwilkes** [comment]
Ah, I misunderstood. You can check if a trait container exists or not using a prereq... but you're right that containers themselves don't currently have prereqs.
