### ISSUE TITLE
Using Emojis on Linux is broken

### ISSUE THREAD

**Issue by CReimer** [richardwilkes/gcs#796]
I'm unable to use Emojis in GCS on Linux. The same file opened on Windows shows all Emojis without problem

You can easily check this by changing e.g. "HP" to "💗 HP"

**Comment by richardwilkes** [comment]
The emoji support relies on your platform having the emojis available for me to use. If it isn't displaying, then GCS is unable to find/access the relevant font data. This isn't something I'm likely to be able to fix.

**Comment by CReimer** [comment]
![Screenshot](https://github.com/richardwilkes/gcs/assets/1853907/e3c7fee3-d50c-4e44-8281-dcac5fa78b20)

Here's a screenshot of GCS side by side with gedit.
gedit shows the Emoji without problem. GCS does not.

**Comment by CReimer** [comment]
The Arch Wiki mentions something about Emoji fallback
https://wiki.archlinux.org/title/Fonts (at 3.4)

Maybe that's what's not working here.

GCS defaults to 'Roboto' for almost all fonts. That's not even installed on my system. And I believe it's not a default font for Windows either.

Either way. Roboto does not provide any Emojis. GCS has to fall back on another font for that. On Linux in my case it is the Noto Color Emoji font

**Comment by richardwilkes** [comment]
Have you checked to see if GCS shows that fallback font in its font list? If not, that would likely be the problem. The underlying Skia graphics package is used to find and load fonts, including the fallback font. If it does see it, then for whatever reason, Skia isn't selecting it when GCS asks it to find a fallback font that contains the given missing character.

**Comment by CReimer** [comment]
"Noto Color Emoji" is available in the font list. I tried setting it as font for "Page Primary Labels" and I expected to only see the Emojis now. Instead there's nothing at all.

It could be possible that the right fallback font is selected but GCS (or Skia) is unable to render the font.

Is there any way I can help debug this problem?

**Comment by richardwilkes** [comment]
Can't hurt to post something to the GCS Discord asking for suggestions -- someone there may have more experience with Linux and/or Skia than I do and have may a solution.

**Comment by CReimer** [comment]
Tried the Windows version on Linux. It looks different but still broken

![grafik](https://github.com/richardwilkes/gcs/assets/1853907/fd49653a-c937-48cb-a497-056c3daeea9a)

**Comment by richardwilkes** [comment]
I recently discovered that the font support I have in skia (the underlying graphics library GCS uses) doesn't support certain types of fonts. Specifically, the Noto Color Emoji font is a newer type of color font that isn't supported. That would explain why attempts to use it don't show any actual emojis.

**Comment by richardwilkes** [comment]
The info I've read so far seems to indicate it is a limitation in the current skia font support code. Skia is a C++ source base. I'm sure support can be added, but the effort involved looks like it is substantially more than I'm interested in tackling at the moment.
