### ISSUE TITLE
Conversion from feet to centimetres is wrong

### ISSUE THREAD

**Issue by kirkeugle** [richardwilkes/gcs#797]
GCS converts 6' to 200 cm, which should be about 180 cm resulting in excessively tall "metric" characters.

The conversion rate seems to be 2.77 cm/in but should be 2.54 cm/in.

**Comment by richardwilkes** [comment]
GCS deliberately uses the GURPS simplified metrics, where 1 meter is equal to 1 yard and 1 kilogram is equal to 2 pounds. Yes, this is incorrect from a reality point of view, but makes for mostly nice, round numbers given the source data. Years ago, I had an option to use actual conversions, but got endless complaints due to the excessive number of decimal digits that inevitably introduced into nearly everything when it was enabled.

I won't be reintroducing that.

**Comment by kirkeugle** [comment]
I am fine with rounded or approximated values and actually the current implementation does introduce awkward decimals as it uses 1/36 of a metre per inch. I would be totally happy to convert 30 cm to the foot and 2.5 cm to the inch (as is actually suggested in the simplified conversion table). 

![Bildschirmfoto_2024-01-07_18-35-08](https://github.com/richardwilkes/gcs/assets/155855732/e83aca1c-07a6-4693-9ddc-11a29f637e82)
![Bildschirmfoto_2024-01-07_18-34-57](https://github.com/richardwilkes/gcs/assets/155855732/656187ad-684c-4e1c-8a91-048c46b503e1)

My problem is mainly that in the case characters height a difference of 7" (6'~180cm and 6'7"~200cm) is quite noticeable.

I am totally fine with converting a yard to the metre in cases of larger dimensions.

**Comment by richardwilkes** [comment]
That's not practical, despite what the Basic Set suggests. You end up with values that are converted at different rates depending on size, which has some very odd effects. It is something I tried out when I originally went to the simplified model, but it just didn't work well.

**Comment by richardwilkes** [comment]
As for the height & weight fields, I'd recommend you manually adjust those to your liking -- i.e. just type in "1.6m" (or whatever) to get the actual value you'd prefer. Its the conversions for the equipment where the long strings of decimals occurred, and with the current method, that's much more controlled, albeit still inaccurate.

**Comment by richardwilkes** [comment]
Happy to discuss this on the [GCS Discord](https://discord.gg/SxuvXVh), if you'd like a more interactive back-and-forth.
