### ISSUE TITLE
Add option for simpler character layout

### ISSUE THREAD

**Issue by rathdrummer** [richardwilkes/gcs#80]
I find the current character layout extremely useful, getting a load of derived stats into a small space while staying easy to understand. The thing is, since GURPS already has the reputation of being very number-intensive in RPG circles, showing character sheets with that layout can make it (incorrectly) seem like a really inaccessible system.
It would be a really useful tool if it were possible to switch the layout to one with the same amount of content as the standard GURPS character sheet:
![image](https://user-images.githubusercontent.com/21983443/45693802-c9f9b680-bb55-11e8-9eac-f4d318394b99.png)
maybe without all the encumbrance values as well. Just to be clear, I don't necessarily think this layout is best, more the amount of content.

Not only would it make it more aesthetically pleasing for rules-casual games, but it would help motivate newcomers to play GURPS.

**Comment by trooper6** [comment]
Or perhaps an option for an NPC Card, which is really, really simple?

**Comment by rathdrummer** [comment]
That would be an absolute lifesaver, and I honestly think I would use it
for characters in last-minute improvised games

**Comment by richardwilkes** [comment]
Have you considered modifying the existing HTML output template for this purpose (or creating your own from scratch)? I'm exceedingly unlikely to modify the standard sheet I provide the UI in, since that would make it difficult to do some operations.

**Comment by rathdrummer** [comment]
Thanks for pointing me towards that, I've brushed up on my git and css skills and made a template. I have submitted it as a [pull request to the gcs-library repo](https://github.com/richardwilkes/gcs_library/pull/74)

**Comment by richardwilkes** [comment]
Glad to hear it. I've merged your npc card template. If you'd like to try a stab at creating one for the character sheet from the book, I'm open to including that as well.
