### ISSUE TITLE
"Gives a weapon secondary projectiles (mode 1) modifier of" doesn't work

### ISSUE THREAD

**Issue by TkabRft** [richardwilkes/gcs#801]
When you add equipment modifier with this feature (doesn't matter mode 1 or 2) to a weapon, it errors: you can't move weapon inside your equipment list and you can't save your character sheet. Also weapon turns red in equipment list.
This errors only if selected Mode HAS non-zero RoF, if it IS zero, than it can be saved.
Also, even when you remove this Feature, weapon still remains bugged and requires complete deletion from equipment.

Basically now I can't make shotguns be shotguns through features/modifiers...
![image](https://github.com/richardwilkes/gcs/assets/58793765/ff0149a7-f323-41aa-a3da-d898fc916974)
![image](https://github.com/richardwilkes/gcs/assets/58793765/214d6542-7937-4773-9798-07e027d9b07b)
![image](https://github.com/richardwilkes/gcs/assets/58793765/91d1fd0c-7e02-407b-b70e-b2ff53683647)
![image](https://github.com/richardwilkes/gcs/assets/58793765/1beb6797-f0dc-4e41-8ee0-03958320fc8a)

**Comment by richardwilkes** [comment]
I see that when I try this, I get an error dumped into the log, which will let me figure out where the problem is. Thanks for reporting it.
