### ISSUE TITLE
Features Category bonus

### ISSUE THREAD

**Issue by Zuljita** [richardwilkes/gcs#81]
It'd be handy to be able to set a talent to give +1 to things like "Skills whose category is".  Particularly useful for things like spells or imbuements.

**Comment by crnormand** [comment]
Similar to #35.    Pull Requests #117 (Skills/Techniques), #118 (Spells) and #119 (Weapons Bonuses) now allow you to set a criteria based on categories.   When you are building the Talent, you can set the particular bonus based on the category.
