### ISSUE TITLE
Add TL discriminator for skill defaults

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#813]
Some skills have different defaults depending on TL. An example of this is the Armoury skill in Basic Set, which has different defaults based on its TL.

I propose adding a NumericCriteria to the SkillDefaults object, omitted from the data if set to "any", which causes the skill default to apply only if the criteria is met.

An alternative to this would be making duplicate listings in the various libraries for skills to which this applies. However, this seems more elegant and should be simple to implement.

**Comment by smithkm** [comment]
There are other conditional defaults like certain techniques that have a different default depending on whether the character has an appropriate cinematic combat trait TBaM/WM/Heroic Archer/Gunslinger. It would be good to handle this in a general way that accommodates both, or makes other conditional defaults easier to build in future.

**Comment by richardwilkes** [comment]
The upcoming commit will add support for TL, but will not add support for other prereq-like discrimination. The reason for this is that some of them could result in circular references and I don't want to deal with that at this time.

If you have a concrete case where other things are actually needed, please open a separate issue for that and include the specifics. Thanks.
