### ISSUE TITLE
Misclicked PDF mapping, no way to undo it

### ISSUE THREAD

**Issue by fdenzer** [richardwilkes/gcs#816]
In the Default Sheet Settings, I linked a PDF, but it is the wrong one. How can I unlink it?
I tried exporting the settings, then searching and deleting for said path. But the JSON data did not contain the path for my PDF.

**Comment by fdenzer** [comment]
I looked in General Settings.
Speaking of
"~/Library/Application Support/com.trollworks.gcs/gcs_prefs.json"
needed escaping because of the whitespace, then I found the path in there. Withdrawn, but required using a text editor, in this workflow.

**Comment by richardwilkes** [comment]
You do not need to edit the preference file directly. Just open up the Settings > Page Reference Mappings, then hit the trash can button for the one you messed up.

Also, the path as shown in the General settings panel is exactly the path used. If you need escaping to use it in a shell, that's for the user to deal with, as there is no way for me to know what you're going to do with it once copied, nor what shell (and therefore what kind of escaping), etc.
