### ISSUE TITLE
Jumping calculation error

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#824]
When a character sheet uses ST/4 as the variable for its calculation of jump distances, it should round down but doesn't. See the "Optional Jumping Rules" sidebar on B352.

**Comment by richardwilkes** [comment]
I was going to fix this today, but I'm not sure where I should be looking for this. I was assuming it was in the "Calculator" view for a sheet, so I created a new sheet, set its ST to 50, then opened the calculator for it. I don't see long jump anywhere. I do see broad jump, which is calculated to be 7 yards (21 feet), which seems right. What am I missing?

Also, looking at the code, where it uses ST and divides by 4, it then truncates, which is the effect you (and the rules) called for.

**Comment by richardwilkes** [comment]
Looks like this wasn't actually referring to the built-in calculator but instead to some custom attribute definitions that came with an old version of GCS. Those formulas need to be adjusted to get the right result, but have no bearing on the current release's code, so closing this.
