### ISSUE TITLE
Add attribute type: Pool (Display Only)

### ISSUE THREAD

**Issue by NocTempre** [richardwilkes/gcs#830]
Request to add reference "pool" attributes for Maximum (basic) values.

**Comment by richardwilkes** [comment]
What is the use case for such a thing? If you can't modify it, then it really isn't a pool anymore, but is just a static value (the maximum), so why not use a non-pool value?

**Comment by NocTempre** [comment]
The main reason is for holding "pools" that are not attributes directly bought with character points.  An example could be control maximum from FDG.  I had been using "basic stat" Display Only secondaries to hold the static value and setting the cost to adjust to 9999 as a workaround. A flag to make the maximum a reference value while maintaining a pool that can change value within that range would be preferable.

**Comment by richardwilkes** [comment]
If I'm understanding you correctly, you want a pool where the "current" value is still modifiable via a text field, but the "maximum" value is not?
