### ISSUE TITLE
i Modifier for weapon reload

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#833]
allow a Equipment Modifier to add an "i" to the reload time

**Comment by richardwilkes** [comment]
I assume you're referring to the "per shot" modifier for reload times. This can already be done by creating a feature to "Set the weapon flag" "Reload Time Is Per Shot" "to true".

Note that it only displays, though, if you actually have a reload time greater than 0.

**Comment by SavarWallk** [comment]
Thank you,
I did not know what set the weapon flag meant
