### ISSUE TITLE
pow function returning <nil>

### ISSUE THREAD

**Issue by CtelinAjira** [richardwilkes/gcs#838]
![2024-05-26 (2)](https://github.com/richardwilkes/gcs/assets/6075940/eecb7f5f-5319-467f-b584-b2727bec2d79)

So I tried to get Super Jump to display the calculated jumping move using this function.  And I ran into `<nil>` as a return value.

Repeatedly.

Eventually, I just decided to pass it two integers instead of a trait_level call.
![2024-05-26](https://github.com/richardwilkes/gcs/assets/6075940/c40b3e1f-6d0a-4f74-849a-70d6fbb0a3f0)

Still got `<nil>`.
![2024-05-26 (1)](https://github.com/richardwilkes/gcs/assets/6075940/4e93c190-a24e-4651-a4f4-bc6c14b5df67)

**Comment by richardwilkes** [comment]
Looking through the code, it appears `pow` was removed at some point, probably by accident, since the code to implement it is still present, just not connected. (sigh)

**Comment by richardwilkes** [comment]
Went to go fix this just now and realized why the function was removed: it is redundant with the power operator: ^

i.e. you should just do this: ||2^3|| instead of ||pow(2,3)||

I do need to update the places where this is documented incorrectly, though.

**Comment by richardwilkes** [comment]
Fixed the FAQ and the Help content in the master library (for a future release)
