### ISSUE TITLE
Weapon Damage Specific Skills or ST Striking

### ISSUE THREAD

**Issue by Burnum** [richardwilkes/gcs#84]
Weapons Damage from skills such as Throwing Art, or Weapon Master, are not being applied.
ST Strike Damage limited to single weapon, are also not being applied.

**Comment by richardwilkes** [comment]
This is unlikely to be done any time soon, as it would require information not currently available in the data.

**Comment by Burnum** [comment]
Thank you responding so quickly. It's not a huge deal by any mean. Love all  the work you've put into this.

**Comment by richardwilkes** [comment]
Applying damage bonuses more selectively is now possible. Individual advantages will need to be modified to use the new capabilities, however -- but that's something any user can do... and then contribute the change back to the library project.
