### ISSUE TITLE
+ST from skills for specific effects

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#842]
Wrestling gives a + to strength that is based on how high your skill is developed. 
This bonus is for specific grappling effects. 

I see no way to automate this as a modifier? 
I was looking at it as a conditional modifier.

**Comment by richardwilkes** [comment]
There is no mechanism for adding ST for a specific thing like this at the moment. You can add strength for purposes of striking, lifting and throwing, but those then apply to everything that uses such things, which is too broad.
