### ISSUE TITLE
Windows: Some skill/trait groups not using dark colors in "Light" theme.

### ISSUE THREAD

**Issue by RevenantBob** [richardwilkes/gcs#843]
Some groups can't be read because they are drawing with light colors on light background while "Light" theme is selected.

Dark mode shows the right colors (Although, that might be because it's not switching from white).

Screenshots below.

Unselected Groups not legible.
![image](https://github.com/richardwilkes/gcs/assets/1105676/7e0e3c47-4d27-4344-b887-1f9b04382a93)

What the text is when selected.
![image](https://github.com/richardwilkes/gcs/assets/1105676/6bf06b55-8c12-45fe-8c34-a524ffcf3678)

**Comment by richardwilkes** [comment]
Ugh. I thought I had looked at that. Serves me right for spending most of my time in dark mode.
