### ISSUE TITLE
Illegible colors of new traits, skills, and the like

### ISSUE THREAD

**Issue by Dorovich** [richardwilkes/gcs#844]
I'm on linux trying the new version of GCS (5.22.0), and when adding new things to a character sheet, their foreground color is white. It does not happen using the dark colors:

![imagen](https://github.com/richardwilkes/gcs/assets/86064861/d1bc3256-f9bf-4ea5-b687-e56e8b595612)
![imagen](https://github.com/richardwilkes/gcs/assets/86064861/631991ce-897e-47ca-b26d-84854b9f973d)

**Comment by richardwilkes** [comment]
This was fixed already. Issue #843. I just haven't gotten around to making a new release with the changes yet.

**Comment by Dorovich** [comment]
> This was fixed already. Issue #843. I just haven't gotten around to making a new release with the changes yet.

Ah, i see. Thanks!
