### ISSUE TITLE
 "as a %" mode doesn't work for "Gives a weapon effective ST modifier" feature

### ISSUE THREAD

**Issue by TkabRft** [richardwilkes/gcs#847]

**Comment by richardwilkes** [comment]
In the future, please give actual detail of what the issue is and ideally, a sample sheet with the bare minimum on it that illustrates the issue.

In this case, I was able to determine pretty quickly what you were having trouble with, but that's not always the case.

**Comment by richardwilkes** [comment]
The "as a %" checkbox, when applied to effective ST, doesn't treat it as a percentage like it should. It instead seems to ignore the checkbox and add the modifier to the effective ST instead.

**Comment by TkabRft** [comment]
> The "as a %" checkbox, when applied to effective ST, doesn't treat it as a percentage like it should. It instead seems to ignore the checkbox and add the modifier to the effective ST instead.

Also, this is the exact same issue as before, when feature "Gives a weapon minimum ST modifier of" was implemented. That's the reason why this time I didn't add the screenshots. 
May I recommend you to review this checkbox' code from the very beginning?

**Comment by richardwilkes** [comment]
The processing of that checkbox is not generic and needs to be handled specially for many cases. GURPS rules in general are not designed for a computer to handle easily and as such have many, many edge cases. Combine that with the fact that I do this in my spare time for fun and have many other things in my day-to-day work/life to juggle, remembering one particular issue is not something that is going to happen, hence the need to be specific when filing issues if you want to see them addressed.
