### ISSUE TITLE
Spell Containers not loading?

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#849]
I made a copy of the ritual magic spells from the magic library. 
I was going to go through the spell list and throw the individual spells into containers based upon their college. 
However I could not move the spells into the container even though I could create a container.

I just realized it wasn't letting me edit when I had the tag filter active.

**Comment by richardwilkes** [comment]
GCS has prevented moving & deleting things in the lists when filtered for years now. This was done because too many people were unintentionally deleting things they didn't realize where present due to the filters.
