### ISSUE TITLE
Issue exporting to GURPS calculator from macOS

### ISSUE THREAD

**Issue by terrordactylyou** [richardwilkes/gcs#85]
When I try to export characters to GURPS Calculator from macOS, I see the successful export dialog window, but the character isn't present in GURPS Calculator. Using GCS 4.11.1 and macOS 10.14 GCS reports Java 10.0.1.

**Comment by richardwilkes** [comment]
I'm assuming this has been addressed by something on the gCalc side of things. If not, and there is something concrete that needs to be done on the GCS side, please reopen with details on what that is.

**Comment by terrordactylyou** [comment]
I actually never received any response from anyone with GURPS Calculator, and eventually just gave up on using it. :(

**Comment by richardwilkes** [comment]
That's a shame. You might want to try the Discord... Jeff used to frequent it. There's a link to it on the main GCS page, if you're not already a member.
