### ISSUE TITLE
Add Prerequisite Count Column for Ritual Magic Spells in Spell Library

### ISSUE THREAD

**Issue by TheCalculusKid** [richardwilkes/gcs#850]
Ritual Magic Enjoyer here. 

Would it be possible to add an extra column in Spell Libraries for displaying prerequisite counts? It would a huge quality of life improvement for ritual mages selecting spells. 

Right now I drag the entire school into a blank character sheet so i can sort it by prereq count and its fairly annoying especially when I am trying to communicate that as a workaround to my ritual mage players.

Thank you.

![image](https://github.com/richardwilkes/gcs/assets/36708261/c31cc4dc-d46a-4db3-bcfb-3a4fb3d6d95c)

**Comment by richardwilkes** [comment]
What does prerequisite count actually mean? Is it just the immediate prereqs? Or does it include all derived prereqs? What about when there are multiple possible ways to satisfy things? Some prereqs are themselves counts of things. How are those accounted for?

This seems fraught with ambiguity.

**Comment by TheCalculusKid** [comment]
So prerequisite count is already a tracked attribute with ritual magic spells. I don't think this would be at all necessary at all to try and apply something like this for regular spells because regular spells do not have a prerequisite count they track prerequisite themselves.

**Comment by richardwilkes** [comment]
I misunderstood the request. I thought you wanted an automatically calculated value, based on the actual prereqs listed for a spell.

So... this is actually just a request to show the prereq count field in the library list view (and not on a character sheet or template)?

**Comment by TheCalculusKid** [comment]
Yes, sorry I might have been vague.

You are correct. It would be nice to have a prerequisite count be able to be displayed in the library view which is what my request is.

Currently it is displayed when the spell is on a character sheet but not when it is in the library.

**Comment by richardwilkes** [comment]
I don't believe it actually shows up on the sheet currently. Is this something that should show up there? I was assuming not, but could add it if it is valuable.

**Comment by richardwilkes** [comment]
Also... do you have a suggestion for the column title? I'll have the tooltip for it spell the whole thing out ("Prerequisite Count")... but something shorter would be better for the displayed header. I have it set to "Prereq" right now... but I was hoping to find something a bit better (and preferably a little shorter, too).

**Comment by TheCalculusKid** [comment]
Oh you are right. It does not show up. It does have Relative Skill Level (RSL) which is practically the same thing which is what made me think it was there. 

Probably fine to leave the character sheet display where it is so it does not unnecessarily clutter things up there at least in my opinion. I just think since almost all other spell attributes are displayed in the library it would be nice if Prerequisite count was also displayed alongside the other attributes to make it easy to organize the list of spells by that count so wizards can pick up low count spells from high count spells.

I mean it could be added in as text below the spell kinda like casting cost and time and college and other such attributes but that is absolutely not necessary (back to my point that RSL is basically prerequisite count).

My suggestion would maybe be P# or PC? Kinda like You abbreviated RSL?
