### ISSUE TITLE
Weapon tables and Skills disappearing

### ISSUE THREAD

**Issue by krusherzero** [richardwilkes/gcs#859]
Importing into Foundry causes weapon tables and skill lists to disappear. Tried with 5.23 and issue did not happen. Used Foundry 11 on both. Updated a sheet last saved in 5.23 so it would save in 5.24 and the issue was repeatable.

**Comment by richardwilkes** [comment]
Mentioned this already on the Discord, but the foundry folks will need to update their code to handle the GCS v5.24 data format.
