### ISSUE TITLE
Bug Report: Sync Column errors, esp Quirks, Talents, and TL or specialization skills

### ISSUE THREAD

**Issue by ArchangelBeth** [richardwilkes/gcs#861]
When a Quirk's name is changed from, e.g., @ Mental Quirk @ to, e.g., "Likes bunnies," the Sync Column goes "!"
When I sync the quirk, it reverts to "@ Mental Quirk @".

When I load a talent from the Basic Set Traits, changing the level of the talent from 1 to 2 _definitely_ made it go !
When I loaded a talent from the Power Ups traits, even at level 1, the sync column went ! at me. In both cases, talents refused to "sync" with the dropdown menu. (Or they did sync, and that didn't make them think that they _weren't_ synced.

Skills that have an optional specialization (e.g., Area Knowledge) also gain the !, I see now; reverting them goes to @ City @.
Skills that were drawn from Basic Set Skills, pre-specialized, gain the !... Because they are TL skills! When I sync them, I lose the TL11, and it becomes only "TL."

**Comment by richardwilkes** [comment]
Fixed in a series of commits ending with f2731cb74dc02db0f1688077cfdc2c9cf78ee87a
