### ISSUE TITLE
GCS 5.25.1 - character files have the 'type' attribute missing

### ISSUE THREAD

**Issue by giggioz** [richardwilkes/gcs#865]
GCS 5.25.1 (Edit: i also tried 5.24.1 same issue, 5.23.0 works!)

Master Library v4.20

I created a basic character, I did not change anything.
If I import it in Foundry VTT it does not have the melee section (natural attacks)

![image](https://github.com/user-attachments/assets/ecc7f528-82dd-402d-9019-e6010b8f6e63)

Checking the gcs file and comparing it to the previous versions of GCS files I Noticed one attribute (type) is missing!

I Edited the file and now it works in foundry vtt.

"traits": [
{
"id": "t5FXRZIuzyPetnLei",
"name": "Natural Attacks",
"reference": "B271",
"weapons": [
{
"id": "wAt5ww9QhYUbjWAMj",
"type": "melee_weapon", <=== THIS LINE IS MISSING, I EDITED IT
"damage": {
"type": "cr",
"st": "thr",
"base": "-1"
},
"usage": "Bite",
"reach": "C",
"defaults": [
{
"type": "dx"
},
{
"type": "skill",
"name": "Brawling"
}
],
"calc": {
"level": 10,
"damage": "1d-3 cr"
}
},
{
"id": "wMuTWN5Z3_VBEJTrz",
"type": "melee_weapon", <=== THIS LINE IS MISSING, I EDITED IT
"damage": {
"type": "cr",
"st": "thr",
"base": "-1"
},
"usage": "Punch",
"reach": "C",
"parry": "0",
"defaults": [
{
"type": "dx"
},
{
"type": "skill",
"name": "Boxing"
},
{
"type": "skill",
"name": "Brawling"
},
{
"type": "skill",
"name": "Karate"
}
],
"calc": {
"level": 10,
"damage": "1d-3 cr",
"parry": "8"
}
},
{
"id": "wiYACbL0e48CKCmQc",
"type": "melee_weapon", <=== THIS LINE IS MISSING, I EDITED IT
"damage": {
"type": "cr",
"st": "thr"
},
"usage": "Kick",
"reach": "C,1",
"defaults": [
{
"type": "dx",
"modifier": -2
},
{
"type": "skill",
"name": "Brawling",
"modifier": -2
},
{
"type": "skill",
"name": "Kicking"
},
{
"type": "skill",
"name": "Karate",
"modifier": -2
}
],
"calc": {
"level": 8,
"damage": "1d-2 cr"
}
}
],
"calc": {
"points": 0
}
}
],

**Comment by richardwilkes** [comment]
Yes, there was a file format change that the GGA / GCSGA folks need to update their logic for. This is not an issue in GCS and the relevant people working on the Foundry game aid(s) are aware of what they need to do.
