### ISSUE TITLE
An option to export PDFs and/or PNGs whenever a sheet is saved.

### ISSUE THREAD

**Issue by Lovewyrm** [richardwilkes/gcs#87]
Well, what the title states.

It would make keeping a repository synced up with changes easier.

**Comment by Lovewyrm** [comment]
Alternatively, tell me the procedure to save PDF files and I'll write a standalone tool that converts the xml to PDFs.

I know enough java to probably port it, but I am kinda sick of grepping through java code to piece together the process from internal data to final file.

**Comment by richardwilkes** [comment]
This isn't something I have an interest in adding to the software. If you really want such a capability, you can use the command line to automate the process by having a script watch for changes to GCS files and then running an export for you.

**Comment by Lovewyrm** [comment]
I implemented it myself lol, so, fair enough.
