### ISSUE TITLE
Increment/Decrement hotkeys don't work with +/- keys on numeric keypad

### ISSUE THREAD

**Issue by dripton** [richardwilkes/gcs#871]
The ctrl-plus and ctrl-minus hotkeys work fine to increment or decrement trait levels work fine for me using the +/- keys on the top row of the main keyboard, but don't work for the +/- keys on the numeric keypad.  This is true whether the keypad's Num Lock state is on or off.  This is on a standard 101-key US PC keyboard, on Linux.

Obviously not a big deal as I can just use the ones on the main keyboard, but it's kind of a surprising bug, as I don't think GCS should care *which* plus or minus key I use.

**Comment by richardwilkes** [comment]
Yeah, that takes extra effort to make work, but is quite doable. Just hasn't been a priority.

**Comment by richardwilkes** [comment]
Hmm... I just realized this isn't really solvable the way I had originally thought, thanks to the fact that I allow you do redefine the key mappings -- and only one combo can be assigned. What you're asking for here (I assume) is for two different combos to trigger the same menu item: CTRL-PLUS as well as CTRL-KEYPAD-PLUS. If you always want to use the keypad, you could reassign the menu item to that, of course, but then the existing one won't trigger it.

**Comment by dripton** [comment]
I think the trick is working at the level of logical keys rather than scan codes, so both of the plus keys are the same key, but I don't know if that's possible cross-platform.  It's not a huge deal in any case; just reported it because it was slightly annoying and might confuse someone.

**Comment by richardwilkes** [comment]
It isn't with what I have access to currently.
