### ISSUE TITLE
Can there be a toggle to revert to the older color scheme with yellow.

### ISSUE THREAD

**Issue by ChangeIsBad** [richardwilkes/gcs#875]
I had updated the program after not updating for a while and it changed my color scheme and fonts. I failed to locate an option to revert to the old version and would like to revert.

![Screenshot (8)](https://github.com/user-attachments/assets/c77e2801-12a0-4d3f-91c7-e56634bc54d0)

**Comment by richardwilkes** [comment]
You can always download an older copy of GCS from GitHub.

I have no plans to switch back to the old color set, as there were way, way too many and it greatly complicated things. I could, however, add a specific "banding" color, which would allow the surface and the stripes on the surface to be independently controlled -- which appears to be the one thing you are looking for.

**Comment by richardwilkes** [comment]
Added a banding color that can be used
