### ISSUE TITLE
Increased strength for a weapon not increasing the range for throwing weapons

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#876]
You recently allowed traits to affect strength for using a weapon and it affects the damage codes properly however it does not seem to make changes to the ranges for a throwing weapons and I don't know about other missile weapons that would be strength-based

**Comment by richardwilkes** [comment]
It appears I failed to add the additional code necessary to find the adjusted ST for range. Thanks for pointing that out.
