### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SavageGM** [richardwilkes/gcs#880]
May we have units of measure for volumes such as gallons, pints, and such.

**Comment by richardwilkes** [comment]
Where would this be used?

**Comment by SavageGM** [comment]
Never mind, I figured a workaround.
I have to find things like the weight of a gallon of mead or a pint of brandy.

**Comment by richardwilkes** [comment]
OK, I'm going to close this. Volumes -> weight isn't really possible, without knowing the more about the material occupying the volume than GCS has information on. Most people just fudge it and say 1 gallon of a liquid equals 8 lbs, as that's roughly what it is for water.
