### ISSUE TITLE
Don't replace unison dependency with local path 

### ISSUE THREAD

**Issue by TomaSajt** [richardwilkes/gcs#891]
Currently the build assumes `unison` is in a sibling directory, which is not usually the case.
This has been like this since https://github.com/richardwilkes/gcs/commit/1213010d59990b6ae6614d9fd9d29d32de4fe97e

Consider removing the `replace` from `go.mod`

**Comment by richardwilkes** [comment]
Ugh. Thanks for pointing that out. That was never meant to be committed.

I'll fix it the next time I'm near the computer.

**Comment by richardwilkes** [comment]
Fixed in 3494593e6d4123741863ceef7b83e45c6afdc7a1
