### ISSUE TITLE
commas in equipment weights throw off sorting

### ISSUE THREAD

**Issue by Human** [richardwilkes/gcs#895]
When sorting by weight, we see examples such as `8 lb` followed by `8,000 lb` followed by `9 lb`. Equipment with decimal weights is unaffected.

![Screenshot_20241102_162907](https://github.com/user-attachments/assets/47a7725d-c003-487e-8304-392ef4e74222)

**Comment by richardwilkes** [comment]
Hmm... probably doing a text comparison rather than a numerical one. Thanks for reporting this.
