### ISSUE TITLE
Feature Request: Filtering multiple tags in Traits, Skills, Spells, etc. lists

### ISSUE THREAD

**Issue by SilntObsvr** [richardwilkes/gcs#898]
Today, I had a need to look for Mental Disadvantages -- and realized that I could filter either Disadvantage, or Mental, but not both at the same time.  This might also come up in looking for Skills (looking for Weapon, Techniques, for instance), Spells (two College spells), possibly even Equipment.

It ought to be relatively easy to add to the code, just nest two or three levels of the existing filter code and ensure that the list is marked with each selected tag so the user can keep track of what they're looking at.

**Comment by richardwilkes** [comment]
As noted on the Discord server, this already exists.
