### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Genesis1980** [richardwilkes/gcs#90]
I was trying to build from the Github but I could not. I would like to switch on the KYOS rules just for the Lifting and without changing the Thr damage. Is it possible?

**Comment by richardwilkes** [comment]
I was upgrading the current code to use Java 11 when I discovered that a key tool, javapackager, had been removed from the Java 11 release for some reason. Even stranger, it is being reinstated in the Java 12 release... so I chose to wait for the Java 12 release to fix things up and create a new GCS release.

In the meantime, you can just roll back to the previously released version of GCS and its dependencies to build with Java 10.
