### ISSUE TITLE
Equipment weight modifiers

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#902]
When I am trying to create a percentage with the weight modifier in the equipment modifier editor It keeps changing the value to pounds it does not allow me to set a percentage regardless of the dropdown of being original weight or base weight. Even though the drop-down menu list percentages within its description.

**Comment by richardwilkes** [comment]
This works fine for me. Note that only the first choice ("to original weight") allows adding a percentage. All the rest only allow multiplying by a percentage.

**Comment by SavarWallk** [comment]
Tested good on second pass
