### ISSUE TITLE
Equipment modifiers tool tip error 

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#910]
The modifier is going into effect correctly but when you hover the mouse over the modified trait it shows incorrect math in the tool tip.![Screenshot 2024-12-14 192533.png](https://github.com/user-attachments/assets/7b2a8830-415b-45db-b35f-22e6e66dd3e3)

**Comment by richardwilkes** [comment]
Please attach an example sheet that illustrates the problem (or send it to me on Discord). Thanks.

**Comment by SavarWallk** [comment]
Uploaded to discord. I can't find how to up load anything but images here
