### ISSUE TITLE
Selectable Hit locations for non-humanoid

### ISSUE THREAD

**Issue by afeeny** [richardwilkes/gcs#92]
p. 552 of the Basic set offers a series of alternative hit location tables for non-human characters.

I would like to see the ability to select one of these alternative hit location configurations.

**Comment by richardwilkes** [comment]
All of the standard ones in the Basic Set should already be present. Just have to choose it from the menu.

**Comment by afeeny** [comment]
Well thanks,

I thought it odd that it didn’t have it.  Mind you it's really not obvious how to select...

**Comment by richardwilkes** [comment]
The menu in the upper left corner of the view that holds the sheet in question seems pretty obvious. Where else would you suggest?

**Comment by afeeny** [comment]
Yeah, I found it. I guess I’ve used the app for years without ever paying attention to that dropdown.

Perhaps all that is required is an added entry in the Help system to point to it on Hit Location keywords

Thanks BTW for the great work you’ve been doing over the years. I really love your product!

AMF

**Comment by richardwilkes** [comment]
There is no help system implemented, unfortunately. The perils of a single developer that does the work in his not-so-free time.

Glad to hear you've found GCS useful!
