### ISSUE TITLE
Unable to enter negative levels for Status

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#93]
The advantage Status (B28) allows for negative levels (to become a disadvantage).   When I try to enter a number below 0 for "level", it just assumes 0.

**Comment by richardwilkes** [comment]
You have to model this as a disadvantage. i.e. -5 points per level. I believe two entries are already present in the libraries, one as an advantage and one as a disadvantage. In general, negative levels are not permitted. At some future point, I may add a way to allow them, but for now, you'll have to settle for the work-around.

**Comment by crnormand** [comment]
I was using a library limited to the Lite advantages, and it did not have the "Disadvantage" version.   I copied it from the Basic Set library and it works just fine.

Thank you.
Chris

    On Monday, February 11, 2019, 1:48:21 PM EST, Richard Wilkes <notifications@github.com> wrote:  
 
 
You have to model this as a disadvantage. i.e. -5 points per level. I believe two entries are already present in the libraries, one as an advantage and one as a disadvantage. In general, negative levels are not permitted. At some future point, I may add a way to allow them, but for now, you'll have to settle for the work-around.
